#!/bin/bash

###################################################################
#Script Name	  : mo_download_ihec.sh
#Description	  : download ihec ATAC-seq data bed files
#Args           : 
#Author       	: Roy Oelen
###################################################################

SAVE_DIR='/groups/umcg-franke-scrna/tmp02/external_datasets/ihec/chromatin'

wget https://epigenomesportal.ca/tracks/Roadmap/hg38/94962.Roadmap.ENCBS010LQV.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/94961.Roadmap.ENCBS010LQV.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/89198.ENCODE.ENCBS049FLD.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/89200.ENCODE.ENCBS049FLD.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/89202.ENCODE.ENCBS049FLD.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/89204.ENCODE.ENCBS049FLD.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/89197.ENCODE.ENCBS049FLD.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/89199.ENCODE.ENCBS049FLD.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/89201.ENCODE.ENCBS049FLD.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/89203.ENCODE.ENCBS049FLD.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/96038.Roadmap.ENCBS217PJS.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/96037.Roadmap.ENCBS217PJS.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/95976.Roadmap.ENCBS375RID.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/95975.Roadmap.ENCBS375RID.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87378.ENCODE.ENCBS414HDG.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87380.ENCODE.ENCBS414HDG.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87377.ENCODE.ENCBS414HDG.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87379.ENCODE.ENCBS414HDG.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/95307.Roadmap.ENCBS469TSJ.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/95306.Roadmap.ENCBS469TSJ.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87440.ENCODE.ENCBS477CHZ.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87439.ENCODE.ENCBS477CHZ.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/95271.Roadmap.ENCBS495KDC.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/95270.Roadmap.ENCBS495KDC.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87432.ENCODE.ENCBS545WKJ.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87434.ENCODE.ENCBS545WKJ.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87431.ENCODE.ENCBS545WKJ.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87433.ENCODE.ENCBS545WKJ.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/94476.Roadmap.ENCBS653EZT.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/94475.Roadmap.ENCBS653EZT.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87374.ENCODE.ENCBS852WTL.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87376.ENCODE.ENCBS852WTL.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87373.ENCODE.ENCBS852WTL.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87375.ENCODE.ENCBS852WTL.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87382.ENCODE.ENCBS857VGC.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87384.ENCODE.ENCBS857VGC.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87381.ENCODE.ENCBS857VGC.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/87383.ENCODE.ENCBS857VGC.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/95375.Roadmap.ENCBS881BDJ.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Roadmap/hg38/95374.Roadmap.ENCBS881BDJ.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/88728.ENCODE.ENCBS911HVB.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/88730.ENCODE.ENCBS911HVB.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/88732.ENCODE.ENCBS911HVB.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/88734.ENCODE.ENCBS911HVB.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/88727.ENCODE.ENCBS911HVB.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/88729.ENCODE.ENCBS911HVB.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/88731.ENCODE.ENCBS911HVB.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/ENCODE/hg38/88733.ENCODE.ENCBS911HVB.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59501.Blueprint.ERS1164742.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59500.Blueprint.ERS1164742.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/57990.Blueprint.ERS1231393.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/57989.Blueprint.ERS1231393.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/58000.Blueprint.ERS1231394.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/57999.Blueprint.ERS1231394.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59767.Blueprint.ERS150394.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59766.Blueprint.ERS150394.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59769.Blueprint.ERS150397.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59768.Blueprint.ERS150397.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59773.Blueprint.ERS150419.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59772.Blueprint.ERS150419.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59771.Blueprint.ERS206426.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59770.Blueprint.ERS206426.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/60129.Blueprint.ERS206572.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/60128.Blueprint.ERS206572.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/60135.Blueprint.ERS206579.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/60134.Blueprint.ERS206579.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/62456.Blueprint.ERS206603.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/62455.Blueprint.ERS206603.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/60123.Blueprint.ERS206615.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/60122.Blueprint.ERS206615.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59499.Blueprint.ERS206618.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59498.Blueprint.ERS206618.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/60133.Blueprint.ERS206634.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/60132.Blueprint.ERS206634.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/60131.Blueprint.ERS222272.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/60130.Blueprint.ERS222272.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/60125.Blueprint.ERS222279.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/60124.Blueprint.ERS222279.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61565.Blueprint.ERS222308.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61564.Blueprint.ERS222308.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61569.Blueprint.ERS222370.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61568.Blueprint.ERS222370.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61567.Blueprint.ERS222372.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61566.Blueprint.ERS222372.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59503.Blueprint.ERS227599.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59502.Blueprint.ERS227599.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59449.Blueprint.ERS227605.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59448.Blueprint.ERS227605.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/62692.Blueprint.ERS257236.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/62691.Blueprint.ERS257236.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/62690.Blueprint.ERS337146.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/62689.Blueprint.ERS337146.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/62694.Blueprint.ERS337153.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/62693.Blueprint.ERS337153.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61571.Blueprint.ERS391270.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61570.Blueprint.ERS391270.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61311.Blueprint.ERS534747.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61310.Blueprint.ERS534747.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61313.Blueprint.ERS534748.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61312.Blueprint.ERS534748.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61315.Blueprint.ERS534749.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61314.Blueprint.ERS534749.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61333.Blueprint.ERS534754.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61332.Blueprint.ERS534754.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61335.Blueprint.ERS534755.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61334.Blueprint.ERS534755.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61337.Blueprint.ERS534756.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61336.Blueprint.ERS534756.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61331.Blueprint.ERS534760.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61330.Blueprint.ERS534760.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61323.Blueprint.ERS534764.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61322.Blueprint.ERS534764.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61317.Blueprint.ERS534765.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61316.Blueprint.ERS534765.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61319.Blueprint.ERS534766.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61318.Blueprint.ERS534766.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61321.Blueprint.ERS534767.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61320.Blueprint.ERS534767.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61325.Blueprint.ERS534774.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61324.Blueprint.ERS534774.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61327.Blueprint.ERS534775.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61326.Blueprint.ERS534775.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61329.Blueprint.ERS534776.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/61328.Blueprint.ERS534776.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59471.Blueprint.ERS642886.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59470.Blueprint.ERS642886.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59475.Blueprint.ERS642898.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59474.Blueprint.ERS642898.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59477.Blueprint.ERS642909.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59476.Blueprint.ERS642909.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59479.Blueprint.ERS642921.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59478.Blueprint.ERS642921.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59473.Blueprint.ERS642933.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59472.Blueprint.ERS642933.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59469.Blueprint.ERS642999.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59468.Blueprint.ERS642999.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59481.Blueprint.ERS643011.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59480.Blueprint.ERS643011.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/62696.Blueprint.ERS643219.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/62695.Blueprint.ERS643219.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59457.Blueprint.ERS643298.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59456.Blueprint.ERS643298.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59453.Blueprint.ERS643313.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59452.Blueprint.ERS643313.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59451.Blueprint.ERS643328.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59450.Blueprint.ERS643328.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59461.Blueprint.ERS643335.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59460.Blueprint.ERS643335.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59455.Blueprint.ERS643344.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59454.Blueprint.ERS643344.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59467.Blueprint.ERS643358.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59466.Blueprint.ERS643358.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59463.Blueprint.ERS643372.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59462.Blueprint.ERS643372.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59465.Blueprint.ERS643384.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59464.Blueprint.ERS643384.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59459.Blueprint.ERS643398.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59458.Blueprint.ERS643398.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59489.Blueprint.ERS643459.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59488.Blueprint.ERS643459.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59511.Blueprint.ERS643470.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59510.Blueprint.ERS643470.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59487.Blueprint.ERS696964.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59486.Blueprint.ERS696964.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59483.Blueprint.ERS696978.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59482.Blueprint.ERS696978.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59493.Blueprint.ERS696991.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59492.Blueprint.ERS696991.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59485.Blueprint.ERS697004.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59484.Blueprint.ERS697004.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59491.Blueprint.ERS697018.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/59490.Blueprint.ERS697018.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/57960.Blueprint.ERS822880.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/57959.Blueprint.ERS822880.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/58002.Blueprint.ERS823973.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/58001.Blueprint.ERS823973.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/57966.Blueprint.ERS861225.Chromatin_Acc.peak_calls.bigBed ${SAVE_DIR}
wget https://epigenomesportal.ca/tracks/Blueprint/hg38/57965.Blueprint.ERS861225.Chromatin_Acc.signal_unstranded.bigWig ${SAVE_DIR}
