---
title: "mo_plot_celltype_proportions"
output: html_document
date: "2023-11-30"
---
```{r header, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#!/usr/bin/env Rscript
############################################################################################################################
# Authors: Roy Oelen
# Name: mo_plot_celltype_proportions.Rmd
# Function: plot the cell type proportions
############################################################################################################################
```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
####################
# libraries        #
####################
library(ggplot2)
library(cowplot)
library(RColorBrewer)

```

```{r functions, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

####################
# Functions        #
####################

#' get a list of colours per category that are present
#' 
#' @returns a list of colours, with the categories as names
#' 
get_color_coding_dict <- function(){
  # set the condition colors
  color_coding <- list()
  color_coding[["UT"]] <- "lightgrey"
  color_coding[["24hCA"]] <- "forestgreen"
  color_coding[["24hCa"]] <- "forestgreen"
  # set the cell type colors
  color_coding[["Bulk"]] <- "black"
  color_coding[["CD4T"]] <- "#153057"
  color_coding[["CD8T"]] <- "#009DDB"
  color_coding[["monocyte"]] <- "#EDBA1B"
  color_coding[["NK"]] <- "#E64B50"
  color_coding[["B"]] <- "#71BC4B"
  color_coding[["DC"]] <- "#965EC8"
  color_coding[["CD4+ T"]] <- "#153057"
  color_coding[["CD8+ T"]] <- "#009DDB"
  # other cell type colors
  color_coding[["HSPC"]] <- "#009E94"
  color_coding[["platelet"]] <- "#9E1C00"
  color_coding[["plasmablast"]] <- "#DB8E00"
  color_coding[["other T"]] <- "#FF63B6"
  color_coding[["hemapoietic_stem"]] <- "#8B8000"
  color_coding[["hemapoietic stem"]] <- "#8B8000"
  return(color_coding)
}

#' get a list of nicer names per category that are present
#' 
#' @returns a list of nicer names, with the categories as names
#' 
label_dict <- function(){
  label_dict <- list()
  # condition combinations
  label_dict[["UT"]] <- "UT"
  label_dict[["24hCa"]] <- "24hCA"
  label_dict[["24hCA"]] <- "24hCA"
  # major cell types
  label_dict[["Bulk"]] <- "bulk-like"
  label_dict[["CD4T"]] <- "CD4+ T"
  label_dict[["CD8T"]] <- "CD8+ T"
  label_dict[["monocyte"]] <- "monocyte"
  label_dict[["NK"]] <- "NK"
  label_dict[["B"]] <- "B"
  label_dict[["DC"]] <- "DC"
  label_dict[["HSPC"]] <- "HSPC"
  label_dict[["plasmablast"]] <- "plasmablast"
  label_dict[["platelet"]] <- "platelet"
  label_dict[["T_other"]] <- "other T"
  label_dict[["hemapoietic_stem"]] <- "hemapoietic stem"
  # minor cell types
  label_dict[["CD4_TCM"]] <- "CD4 TCM"
  label_dict[["Treg"]] <- "T regulatory"
  label_dict[["CD4_Naive"]] <- "CD4 naive"
  label_dict[["CD4_CTL"]] <- "CD4 CTL"
  label_dict[["CD8_TEM"]] <- "CD8 TEM"
  label_dict[["cMono"]] <- "cMono"
  label_dict[["CD8_TCM"]] <- "CD8 TCM"
  label_dict[["ncMono"]] <- "ncMono"
  label_dict[["cDC2"]] <- "cDC2"
  label_dict[["B_intermediate"]] <- "B intermediate"
  label_dict[["NKdim"]] <- "NK dim"
  label_dict[["pDC"]] <- "pDC"
  label_dict[["ASDC"]] <- "ASDC"
  label_dict[["CD8_Naive"]] <- "CD8 naive"
  label_dict[["MAIT"]] <- "MAIT"
  label_dict[["CD8_Proliferating"]] <- "CD8 proliferating"
  label_dict[["CD4_TEM"]] <- "CD4 TEM"
  label_dict[["B_memory"]] <- "B memory"
  label_dict[["NKbright"]] <- "NK bright"
  label_dict[["B_naive"]] <- "B naive"
  label_dict[["gdT"]] <- "gamma delta T"
  label_dict[["CD4_Proliferating"]] <- "CD4 proliferating"
  label_dict[["NK_Proliferating"]] <- "NK proliferating"
  label_dict[["cDC1"]] <- "cDC1"
  label_dict[["ILC"]] <- "ILC"
  label_dict[["dnT"]] <- "double negative T"
  return(label_dict)
}

#' get a dataframe with the proportons and cell numbers per sample
#' 
#' @param metadata the metadata to calculate the cell type numbers and proportions from
#' @param sample_column the sample denoting the sample
#' @param cell_type_column the column denoting the cell type
#' @returns a dataframe with the proportion and number of each cell type per sample
#' 
get_celltype_numbers <- function(metadata, sample_column='sample', cell_type_column='cell_type') {
  # get the numbers in total
  numbers_totals <- data.frame(table(metadata[, c(sample_column, cell_type_column)]))
  # init proportion
  numbers_totals[['prop']] <- 0
  # now add proportions
  for (sample_name in unique(metadata[[sample_column]])) {
    # subset to that sample
    numbers_sample <- numbers_totals[!is.na(numbers_totals[[sample_column]]) & numbers_totals[[sample_column]] == sample_name, ]
    # get the total for that sample
    numbers_sample_total <- sum(numbers_sample[['Freq']])
    # check each cell type
    for (cell_type in unique(numbers_sample[[cell_type_column]])) {
      # get the number
      numbers_celltype_sample <- numbers_sample[!is.na(numbers_sample[[cell_type_column]]) & numbers_sample[[cell_type_column]] == cell_type, 'Freq']
      # get the proportion
      prop_celltype_sample <- numbers_celltype_sample / numbers_sample_total
      # add to the table
      numbers_totals[!is.na(numbers_totals[[sample_column]]) & 
                       numbers_totals[[sample_column]] == sample_name &
                       !is.na(numbers_totals[[cell_type_column]]) & 
                       numbers_totals[[cell_type_column]] == cell_type, 'prop'] <- prop_celltype_sample
    }
  }
  # set the column names
  colnames(numbers_totals) <- c(sample_column, cell_type_column, 'number', 'proportion')
  return(numbers_totals)
}

#' get a dataframe with the proportons and cell numbers per sample
#' 
#' @param celltype_numbers the metadata to calculate the cell type numbers and proportions from
#' @param sample_column the sample denoting the sample
#' @param cell_type_column the column denoting the cell type
#' @param number_column the column denoting number to plot
#' @param use_label_dict update labels with nicer ones, using the label dict
#' @param pointless plot the ticks and names on the x axis
#' @param legendless plot the legend
#' @param paper_style use paper style plot, with more whitespace
#' @param angle_x_labels angle the x label 90 degrees
#' @param use_colour_coding_dict use colors from the color dict
#' @returns a plot of cell numbers/proportions per sample
#' 
plot_celltype_abundance <- function(celltype_numbers, sample_column='sample', cell_type_column='cell_type', number_column='proportion', use_label_dict=T, pointless=F, legendless=F, paper_style=T, angle_x_labels=F, use_colour_coding_dict=T) {
  # use some better labels if requested
  if (use_label_dict) {
    celltype_numbers[[cell_type_column]] <- as.vector(unlist(label_dict()[as.character(celltype_numbers[[cell_type_column]])]))
  }
  
  # init plot
  p <- ggplot(data = NULL, mapping = aes(x = celltype_numbers[[sample_column]], y = celltype_numbers[[number_column]], fill = celltype_numbers[[cell_type_column]])) +
    geom_bar(stat = 'identity', position = 'stack') +
    xlab(sample_column) +
    ylab(number_column)
  
  # add colours if requested
  if (use_colour_coding_dict) {
    p <- p + scale_fill_manual(name = cell_type_column, values = get_color_coding_dict())
  }

  # all our options
  if(pointless){
    p <- p + theme(axis.text.x=element_blank(), 
                   axis.ticks = element_blank(),
                   axis.title.x = element_blank())
  }
  if(legendless){
    p <- p + theme(legend.position = 'none')
  }
  if(paper_style){
    p <- p + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white"))
  }
  if(angle_x_labels){
    p <- p + theme(axis.text.x = element_text(angle = 90))
  }
  return(p)
}

```

```{r setup_main, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
####################
# Main Code        #
####################

# read the metadata
celllevel_metadata_loc <- '/groups/umcg-franke-scrna/tmp01/projects/multiome/ongoing/metadata/mo_cellevel_metadata.tsv'
celllevel_metadata <- read.table(celllevel_metadata_loc, header = T, sep = '\t')

```

```{r calculate_numbers, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# add a column denoting sample+lane
celllevel_metadata[['sample_lane']] <- paste(celllevel_metadata[['lane']], celllevel_metadata[['soup_cluster']])
# get the numbers
celllevel_ct_numbers <- get_celltype_numbers(celllevel_metadata, sample_column = 'sample_lane', cell_type_column = 'cell_type_lowerres_imputed')
# just per lane as well
celllevel_ct_numbers_lane <- get_celltype_numbers(celllevel_metadata, sample_column = 'lane', cell_type_column = 'cell_type_lowerres_imputed')

```

```{r plot_numbers, include=TRUE, fig.width=20, fig.height=10}
knitr::opts_chunk$set(echo = FALSE)

plot_celltype_abundance(celllevel_ct_numbers, sample_column = 'sample_lane', cell_type_column = 'cell_type_lowerres_imputed', angle_x_labels = T) + guides(fill = guide_legend(title = 'cell type'))
plot_celltype_abundance(celllevel_ct_numbers, sample_column = 'sample_lane', cell_type_column = 'cell_type_lowerres_imputed', number_column = 'number', angle_x_labels = T) + guides(fill = guide_legend(title = 'cell type'))
plot_celltype_abundance(celllevel_ct_numbers_lane, sample_column = 'lane', cell_type_column = 'cell_type_lowerres_imputed', angle_x_labels = T) + guides(fill = guide_legend(title = 'cell type'))
plot_celltype_abundance(celllevel_ct_numbers_lane, sample_column = 'lane', cell_type_column = 'cell_type_lowerres_imputed', number_column = 'number', angle_x_labels = T) + guides(fill = guide_legend(title = 'cell type'))

```

```{r calculate_numbers_onlycor, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# subset to correlations that are high enough
celllevel_metadata_mincor <- celllevel_metadata[!is.na(celllevel_metadata[['soup_best_match_correlation']]) & celllevel_metadata[['soup_best_match_correlation']] > 0.7, ]
# add the sample and lane as joint column
celllevel_metadata_mincor[['sample_lane']] <- paste(celllevel_metadata_mincor[['soup_best_match_sample']], celllevel_metadata_mincor[['lane']])
# get the numbers
celllevel_ct_numbers_mincor <- get_celltype_numbers(celllevel_metadata_mincor, sample_column = 'sample_lane', cell_type_column = 'cell_type_lowerres_imputed')
```

```{r plot_numbers_onlycor, include=TRUE, fig.width=20, fig.height=10}
knitr::opts_chunk$set(echo = FALSE)

plot_grid(
  plot_celltype_abundance(celllevel_ct_numbers_mincor[celllevel_ct_numbers_mincor[['sample_lane']] %in% unique(celllevel_ct_numbers_mincor[['sample_lane']])[1:100], ], sample_column = 'sample_lane', cell_type_column = 'cell_type_lowerres_imputed', angle_x_labels = T) + guides(fill = guide_legend(title = 'cell type')),
  plot_celltype_abundance(celllevel_ct_numbers_mincor[celllevel_ct_numbers_mincor[['sample_lane']] %in% unique(celllevel_ct_numbers_mincor[['sample_lane']])[101:200], ], sample_column = 'sample_lane', cell_type_column = 'cell_type_lowerres_imputed', angle_x_labels = T) + guides(fill = guide_legend(title = 'cell type')),
  plot_celltype_abundance(celllevel_ct_numbers_mincor[celllevel_ct_numbers_mincor[['sample_lane']] %in% unique(celllevel_ct_numbers_mincor[['sample_lane']])[201:300], ], sample_column = 'sample_lane', cell_type_column = 'cell_type_lowerres_imputed', angle_x_labels = T) + guides(fill = guide_legend(title = 'cell type')),
  plot_celltype_abundance(celllevel_ct_numbers_mincor[celllevel_ct_numbers_mincor[['sample_lane']] %in% unique(celllevel_ct_numbers_mincor[['sample_lane']])[301:400], ], sample_column = 'sample_lane', cell_type_column = 'cell_type_lowerres_imputed', angle_x_labels = T) + guides(fill = guide_legend(title = 'cell type')),
  plot_celltype_abundance(celllevel_ct_numbers_mincor[celllevel_ct_numbers_mincor[['sample_lane']] %in% unique(celllevel_ct_numbers_mincor[['sample_lane']])[401:500], ], sample_column = 'sample_lane', cell_type_column = 'cell_type_lowerres_imputed', angle_x_labels = T) + guides(fill = guide_legend(title = 'cell type')),
  plot_celltype_abundance(celllevel_ct_numbers_mincor[celllevel_ct_numbers_mincor[['sample_lane']] %in% unique(celllevel_ct_numbers_mincor[['sample_lane']])[501:600], ], sample_column = 'sample_lane', cell_type_column = 'cell_type_lowerres_imputed', angle_x_labels = T) + guides(fill = guide_legend(title = 'cell type')),
  nrow = 6
)

```

