---
title: "mo_compare_tf_to_region_ieqtls"
author: "Roy Oelen"
date: "2026-03-19"
output: html_document
---

```{r header, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#!/usr/bin/env Rscript
############################################################################################################################
# Authors: Roy Oelen
# Name: mo_compare_tf_to_region_ieqtls.Rmd
# Function: compare the TF-i-eQTLs with region and TF as interaction terms
############################################################################################################################
```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

####################
# libraries        #
####################

library(data.table)
library(ggplot2)
library(roycols)
library(cowplot)
library(stringr)


```

```{r functions, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# Functions        #
####################


#' get the eGenes per cell type from QTL output
#' 
#' @param qtl_output_loc base location of the QTL output per cell type
#' @param output_file which output file to read for the results
#' @param gene_column which column to use as the gene identifier
#' @returns a list with the output tables per cell type
#' 
get_output_per_celltype_limix <- function(qtl_output_loc, output_file='qtl_results_all_qval_allchroms_fdr005_significant_cs.tsv.gz', gene_column='feature_id', significance_column='feature_q_value', significance_cutoff=0.05, verbose=T, add_nominal_cutoff=T, nominal_p_value_column='p_value') {
  # get the folders in the directory, which should be the cell types
  cell_types <- list.dirs(qtl_output_loc, full.names = F, recursive = F)
  # we will store the results in a list for now
  egenes_per_celltype <- list()
  # check each cell type
  for (cell_type in cell_types) {
    # paste together the full path
    full_cell_type_path <- paste(qtl_output_loc, '/', cell_type, '/', output_file, sep = '')
    # log if requested
    if (verbose) {
      print(paste('reading', full_cell_type_path))
    }
    # read the file
    cell_type_output <- read.table(full_cell_type_path, sep = '\t', header = T)
    # filter the results on significance
    if (!is.null(significance_column)) {
      # print progress if requested
      if (verbose) {
        print(paste('variant+phenotype before filtering', nrow(cell_type_output)))
      }
      # filter
      cell_type_output <- cell_type_output[
        !is.na(cell_type_output[[significance_column]]) &
          cell_type_output[[significance_column]] < significance_cutoff, 
      ]
      if (verbose) {
        print(paste('variant+phenotype after filtering', nrow(cell_type_output)))
      }
      # add nominal cutoff by first getting the top effects
      cell_type_output_top <- cell_type_output[order(cell_type_output[[nominal_p_value_column]]), ]
      cell_type_output_top <- cell_type_output_top[!duplicated(cell_type_output_top[[gene_column]]), ]
      # get the highest still significant p value
      max_sig_p <- max(cell_type_output_top[[nominal_p_value_column]])
      # and add that to the output
      cell_type_output[['nominal_p_value_cutoff']] <- max_sig_p
    }
    # add to the list
    egenes_per_celltype[[cell_type]] <- cell_type_output
  }
  # turn into a dataframe
  return(egenes_per_celltype)
}


add_associated_region <- function(eqtl_outputs, scenic_output, eqtl_gene_column='feature_id', scenic_gene_column='Gene', scenic_region_column='Region') {
  # keep a list per cell type
  cs_output_per_ct_region <- list()
  # check each cell type
  for (cell_type in names(eqtl_outputs)) {
    # extract for cell type
    cs_output_ct <- eqtl_outputs[[cell_type]]
    # subset scenic
    scenic_relevant <- scenic_output[, c(..scenic_gene_column, ..scenic_region_column)]
    # with standardised columns
    colnames(scenic_relevant) <- c('feature', 'region')
    # add associated region to gene
    cs_output_ct <- merge(
      cs_output_ct, 
      scenic_relevant, 
      by.x = eqtl_gene_column, 
      by.y = 'feature'
    )
    # put back in the list
    cs_output_per_ct_region[[cell_type]] <- cs_output_ct
  }
  return(cs_output_per_ct_region)
}


get_top_effect_per_cs <- function(cs_output_per_ct, feature_column='feature_id', variant_column='snp_id', sort_column='p_value', cs_column='CS', decreasing_sort=F) {
  # store the variant-feature confinement per ct
  var_feature_per_ct <- list()
  # check each cell type
  for (cell_type in names(cs_output_per_ct)) {
    # get output for this cell type
    cs_output_ct <- cs_output_per_ct[[cell_type]]
    # order
    cs_output_ct <- cs_output_ct[order(cs_output_ct[[sort_column]], decreasing = decreasing_sort), ]
    # check if there are entries where the CS is not known
    cs_output_ct_cs_na <- is.na(cs_output_ct[[cs_column]])
    # if there are more than zero
    if (length(cs_output_ct_cs_na) > 0) {
      # set the CS as 'U'
      cs_output_ct[cs_output_ct_cs_na, ][[cs_column]] <- 'U'
      # get the top variant per feature and cs
      cs_output_ct <- cs_output_ct[!duplicated(paste(cs_output_ct[[feature_column]], cs_output_ct[[cs_column]])), ]
      # get the entries where the CS is 'U'
      cs_output_ct_u <- cs_output_ct[cs_output_ct[[cs_column]] == 'U', ]
      # count the credible sets with unknown credible sets
      cs_output_ct_u_ct_counts <- data.frame(table(cs_output_ct_u[[feature_column]]))
      # get the ones that have a credible set in addition to the U one
      cs_output_ct_u_ct_also_not_u <- cs_output_ct_u_ct_counts[cs_output_ct_u_ct_counts[['Freq']] > 1, ]
      # check if there are any
      if (nrow(cs_output_ct_u_ct_also_not_u) > 1) {
        # get the features
        cs_output_ct_u_ct_also_not_u_features <- cs_output_ct_u_ct_also_not_u[[feature_id]]
        # then keep only what is not U and at the same time also not-U
        cs_output_ct <- cs_output_ct[
          !(cs_output_ct[[cs_column]] == 'U' & cs_output_ct[[feature_column]] %in% cs_output_ct_u_ct_also_not_u_features), 
        ]
      }
    }
    # get the variant and feature
    top_var_feature_per_cs <- data.frame('cell_type' = rep(cell_type, times = nrow(cs_output_ct)), 'variant' = cs_output_ct[[variant_column]], 'feature' = cs_output_ct[[feature_column]])
    # put in the list
    var_feature_per_ct[[cell_type]] <- top_var_feature_per_cs
  }
  # merge all
  var_feature_all <- do.call('rbind', var_feature_per_ct)
  return(var_feature_all)
}


get_closest_flanks <- function(position_table, left_flank_column1, right_flank_column1, left_flank_column2, right_flank_column2) {
  # get the distance between left flanks
  dist_left_flank1_to_left_flank2 <- position_table[[left_flank_column1]] - position_table[[left_flank_column2]]
  # distance between the right flanks
  dist_right_flank1_to_right_flank2 <- position_table[[right_flank_column1]] - position_table[[right_flank_column2]]
  # distance between left flank 1 and right flank 2
  dist_left_flank1_to_right_flank2 <- position_table[[left_flank_column1]] - position_table[[right_flank_column2]]
  # distance between right flank 1 and left flank 2
  dist_right_flank1_to_left_flank2 <- position_table[[right_flank_column1]] - position_table[[left_flank_column2]]
  # put in a table for convenience sake
  distances_tbl <- data.table(
    'lf1_to_lf2' = dist_left_flank1_to_left_flank2, 
    'rf1_to_rf2' = dist_right_flank1_to_right_flank2, 
    'lf1_to_rf2' = dist_left_flank1_to_right_flank2, 
    'rf1_to_lf2' = dist_right_flank1_to_left_flank2
  )
  # add the minimum absolute distance
  distances_tbl[['min_dist']] <- apply(distances_tbl, 1, function(x) {
    return(min(abs(x)))
  })
  # but set this to zero if any of the flanks end in the bodies
  #              -----
  #                 ++++
  distances_tbl[(distances_tbl[['lf1_to_lf2']] < 0 & distances_tbl[['lf1_to_rf2']] > 0) |
                  #                   ----
                #                 ++++
                (distances_tbl[['rf1_to_lf2']] > 0 & distances_tbl[['lf1_to_rf2']] < 0) |
                  #                   ----
                #                 +++++++++
                (distances_tbl[['lf1_to_lf2']] > 0 & distances_tbl[['rf1_to_rf2']] < 0) |
                  #                 ---------
                #                   ++++
                (distances_tbl[['lf1_to_lf2']] < 0 & distances_tbl[['rf1_to_rf2']] > 0)
                , 'min_dist'] <- 0
  return(distances_tbl)
}


plot_concondance <- function(dataset_to_compare, d1_effect_column='d1_zscore', d2_effect_column='d2_zscore') {
  # get the minimal significant z for k1
  min_sig_z_d1 <- min(abs(dataset_to_compare[[d1_effect_column]]))
  min_sig_z_d2 <- min(abs(dataset_to_compare[[d2_effect_column]]))
  # and the max z
  max_sig_z_d1 <- max(abs(dataset_to_compare[[d1_effect_column]]))
  max_sig_z_d2 <- max(abs(dataset_to_compare[[d2_effect_column]]))
  
  # calculate concordance
  n_significant_both <- nrow(dataset_to_compare)
  n_significant_directed_both <- sum(sign(dataset_to_compare[[d1_effect_column]]) == sign(dataset_to_compare[[d2_effect_column]]))
  concordance <- round(n_significant_directed_both / n_significant_both, digits = 3)
  
  # plot the concordance of the two
  p <- ggplot(data = dataset_to_compare, mapping = aes(x = !! rlang::sym(d1_effect_column), y = !! rlang::sym(d2_effect_column))) + 
    geom_point(size = 0.2) + 
    xlim(c(max_sig_z_d1 * -1.1, max_sig_z_d1 * 1.1)) +
    ylim(c(max_sig_z_d2 * -1.1, max_sig_z_d2 * 1.1)) + 
    # left to right block of non-significant effects
    geom_rect(aes(xmin = -1 * max_sig_z_d1, xmax = max_sig_z_d1, ymin = -1 * min_sig_z_d2, ymax = min_sig_z_d2), 
              fill = "white", alpha = 0.005) +
    # bottom to top block of non-significant effects
    geom_rect(aes(xmin = -1 * min_sig_z_d1, xmax = min_sig_z_d1, ymin = -1 * max_sig_z_d2, ymax = max_sig_z_d2), 
              fill = "white", alpha = 0.005) +
    # bottom left block
    geom_rect(aes(xmin = -1 * max_sig_z_d1, xmax = -1 *min_sig_z_d1, ymin = -1 * max_sig_z_d2, ymax = -1 * min_sig_z_d2), 
              fill = "#0072B2", alpha = 0.01) +
    # bottom right block
    geom_rect(aes(xmin = min_sig_z_d1, xmax = max_sig_z_d1, ymin = -1 * max_sig_z_d2, ymax = -1 * min_sig_z_d2), 
              fill = "#D55E00", alpha = 0.01) +
    # top left block
    geom_rect(aes(xmin = -1 * max_sig_z_d1, xmax = -1 *min_sig_z_d1, ymin = min_sig_z_d2, ymax = max_sig_z_d2), 
              fill = "#D55E00", alpha = 0.01) + 
    # top right block
    geom_rect(aes(xmin = min_sig_z_d1, xmax = max_sig_z_d1, ymin = max_sig_z_d2, ymax = min_sig_z_d2), 
              fill = "#0072B2", alpha = 0.01) + 
    # labels for x and y axis
    xlab('effect in dataset1') +
    ylab('effect in dataset2') +
    # vertical negative z ccombinedoff line
    geom_vline(xintercept=c(-1 *min_sig_z_d1), color="black", size=0.5, linetype = "dashed") +
    # horizonal negative z ccombinedoff line
    geom_hline(yintercept=c(-1 *min_sig_z_d2), color="black", size=0.5, linetype="dashed") +
    # vertical positive z ccombinedoff line
    geom_vline(xintercept=c(min_sig_z_d1), color="black", size=0.5, linetype = "dashed") +
    # horizonal positive z ccombinedoff line
    geom_hline(yintercept=c(min_sig_z_d2), color="black", size=0.5, linetype="dashed") +
    # make backgrounds white
    theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) + 
    # add the concordance
    annotate("label", x = max_sig_z_d1 * 0.75 , y = max_sig_z_d2 * -0.75, label = paste('concordance', concordance, sep = ':\n')) +
    # add the names of the concordant and non-concordant blocks
    annotate("text", x = max_sig_z_d1 * -0.70 , y = max_sig_z_d2 * 0.75, label = 'discordant', colour = '#D55E00', fontface = 'bold') +
    # add the names of the concordant and non-concordant blocks
    annotate("text", x = max_sig_z_d1 * 0.70 , y = max_sig_z_d2 * 0.75, label = 'concordant', colour = '#0072B2', fontface = 'bold') +
    # add the title
    ggtitle('Concordance of effects between datasets')
  return(p)
}



```

```{r settings, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# Settings         #
####################


```

```{r path_setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

####################
# Main Code        #
####################

# location of the tf-i-ieqtls
tf_ieqtl_loc <- '/groups/umcg-franke-scrna/tmp02/projects/multiome/ongoing/cre_detection/limix_sc/output/tf_interaction/sc/all/lane_donor_countrna_inclcaqtls_varinregion/merged/results_fdr.tsv.gz'
# location of the region-i-ieqtls
region_ieqtl_loc <- '/groups/umcg-franke-scrna/tmp02/projects/multiome/ongoing/cre_detection/limix_sc/output/region_interaction/sc/all/lane_donor_countrna_inclcaqtls_varinregion/merged/results_fdr.tsv.gz'

```

```{r read_inputs, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# read the inputs
tf_ieqtls <- fread(tf_ieqtl_loc, header = T, sep = '\t')
region_ieqtls <- fread(region_ieqtl_loc, header = T, sep = '\t')

```

```{r filter_inputs, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# get what is significant
tf_ieqtls_sig <- tf_ieqtls[
  !is.na(tf_ieqtls[['region:genotype_bh']]) &
  tf_ieqtls[['region:genotype_bh']] < 0.05 & 
    tf_ieqtls[['anova_bh']] < 0.05 & 
    # tf_ieqtls[['region_bh']] < 0.05 & 
    # tf_ieqtls[['genotype_bh']] < 0.05,
    tf_ieqtls[['region_bh']] < 0.05, 
]
region_ieqtls_sig <- region_ieqtls[
  !is.na(region_ieqtls[['region:genotype_bh']]) &
  region_ieqtls[['region:genotype_bh']] < 0.05 & 
    region_ieqtls[['anova_bh']] < 0.05 & 
    # region_ieqtls[['region_bh']] < 0.05 &
    # region_ieqtls[['genotype_bh']] < 0.05,
    region_ieqtls[['region_bh']] < 0.05,
]

```

```{r overlap_effects, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# merge the tf and region qtls
tf_region_ieqtls_overlap <- merge(
  tf_ieqtls_sig[tf_ieqtls_sig[['genotype_bh']] < 0.05, ], 
  region_ieqtls_sig[region_ieqtls_sig[['genotype_bh']] < 0.05, ], 
  by.x = c('variant', 'gene'), 
  by.y = c('variant', 'gene')
)

```

```{r read_scenic, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# the location of SCENIC output
scenic_output_loc <- '/groups/umcg-franke-scrna/tmp02/projects/multiome/ongoing/scenicplus_workdir/scplus_pipeline_merged_major_and_minor_celltypes/output/eRegulon_both.tsv.gz'
# read the scenic output
scenic_output <- fread(scenic_output_loc, header = T, sep = '\t')
# remove what SCENIC thinks is less likely
scenic_output <- scenic_output[scenic_output[['Gene_signature_direction']] %in% c('+/+', '-/+'), ]
# order by the extended
scenic_output <- scenic_output[order(scenic_output[['is_extended']]), ]
# get which are non-extended if it was both extended and non-extended
scenic_eregs <- unique(scenic_output[, c('TF', 'Gene_signature_direction', 'Gene_signature_name', 'source')])
scenic_eregs <-scenic_eregs[order(scenic_eregs[['source']]), ]
scenic_eregs_to_keep <- scenic_eregs[!duplicated(paste(scenic_eregs[['TF']], scenic_eregs[['Gene_signature_direction']])), ]
# then use that to filer
scenic_output <- scenic_output[scenic_output[['Gene_signature_name']] %in% scenic_eregs_to_keep[['Gene_signature_name']], ]
# rename the regions
scenic_output[['region_cpeaks']] <- gsub(':', '-', scenic_output[['Region']])

```

```{r rename_tf, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# remove the TF-i-eGene that was removed from the name (it was added in the second pass)
tf_region_ieqtls_overlap[['region.x']] <- gsub('\\)_.*', ')', tf_region_ieqtls_overlap[['region.x']])

```

```{r filter_scenic, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

tf_region_ieqtls_overlap <- tf_region_ieqtls_overlap[
  paste(tf_region_ieqtls_overlap[['gene']], tf_region_ieqtls_overlap[['region.y']], tf_region_ieqtls_overlap[['region.x']]) %in% paste(scenic_output[['Gene']], gsub(':', '-', scenic_output[['Region']]), scenic_output[['Gene_signature_name']]), 
]

```

```{r tf_region_infl, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# location of the QTL outputs
eqtl_output_loc <- '/groups/umcg-franke-scrna/tmp02/projects/multiome/ongoing/qtl/finemapping/eqtl/sc-eqtlgen/combined_with_qtl/combined/L1/'
# read the eQTL output
eqtl_outputs <- get_output_per_celltype_limix(eqtl_output_loc)

# location of the QTL outputs
caqtl_output_loc <- '/groups/umcg-franke-scrna/tmp02/projects/multiome/ongoing/qtl/finemapping/caqtl/sc-eqtlgen/combined_with_qtl/combined/L1/'
# read the eQTL output
caqtl_outputs <- get_output_per_celltype_limix(caqtl_output_loc)
# get the top effects per credible set
caqtl_top_var_feature_per_cs <- get_top_effect_per_cs(caqtl_outputs)

# add scenic region info
eqtl_outputs_scenic_regions <- add_associated_region(eqtl_outputs, scenic_output, scenic_region_column = 'region_cpeaks')
# read the cpeaks annotation
cpeaks_anno_loc <- '/groups/umcg-franke-scrna/tmp02/external_datasets/cPeaks/cPeaks_wscreenv4.tsv.gz'
cpeaks_anno <- fread(cpeaks_anno_loc, header = T, sep = '\t')
# add the Signac style name
cpeaks_anno[['signac_hg38']] <- paste(cpeaks_anno[['chr_hg38']], cpeaks_anno[['start_hg38']], cpeaks_anno[['end_hg38']], sep = '-')
# as well as the SCENIC+ style name
cpeaks_anno[['scenic_hg38']] <- paste0(cpeaks_anno[['chr_hg38']], ':', cpeaks_anno[['start_hg38']], '-', cpeaks_anno[['end_hg38']])
# set names
colnames(cpeaks_anno) <- paste('atac', colnames(cpeaks_anno), sep = '_')
# store filtered regions
eqtl_outputs_scenic_regions_filtered <- list()
# the region location for each cpeaks region
for (ct in names(eqtl_outputs_scenic_regions)) {
  # get the table
  eqtl_outputs_scenic_regions_ct <- eqtl_outputs_scenic_regions[[ct]]
  # add to the overlap table
  eqtl_outputs_scenic_regions_ct <- cbind(eqtl_outputs_scenic_regions_ct, cpeaks_anno[match(eqtl_outputs_scenic_regions_ct[['region']], cpeaks_anno[['atac_signac_hg38']]), c('atac_chr_hg38', 'atac_start_hg38', 'atac_end_hg38', 'atac_housekeeping', 'atac_screen_all')])
  # get the distances
  eqtl_outputs_scenic_regions_ct_gene_distances <- get_closest_flanks(eqtl_outputs_scenic_regions_ct, 'atac_start_hg38', 'atac_end_hg38', 'feature_start', 'feature_end')
  # add that to the original table
  eqtl_outputs_scenic_regions_ct[['region_gene_distance']] <- eqtl_outputs_scenic_regions_ct_gene_distances[['min_dist']]
  # get the distances
  eqtl_outputs_scenic_regions_ct_esnp_distances <- get_closest_flanks(eqtl_outputs_scenic_regions_ct, 'atac_start_hg38', 'atac_end_hg38', 'snp_position', 'snp_position')
  # add that to the original table
  eqtl_outputs_scenic_regions_ct[['region_esnp_distance']] <- eqtl_outputs_scenic_regions_ct_esnp_distances[['min_dist']]
  # now keep only where the variant is in the chromatin region, and the chromatin region does not overlap the gene
  eqtl_outputs_scenic_regions_ct <- eqtl_outputs_scenic_regions_ct[
    !is.na(eqtl_outputs_scenic_regions_ct[['region_gene_distance']]) &
      !is.na(eqtl_outputs_scenic_regions_ct[['region_esnp_distance']]) &
      eqtl_outputs_scenic_regions_ct[['region_gene_distance']] > 0 &
      eqtl_outputs_scenic_regions_ct[['region_esnp_distance']] == 0,  
  ]
  # put that back into the list
  eqtl_outputs_scenic_regions_filtered[[ct]] <- eqtl_outputs_scenic_regions_ct
}
# get the top effects per credible set again, after filtering
eqtl_top_var_feature_per_cs_filtered <- get_top_effect_per_cs(eqtl_outputs_scenic_regions_filtered)
# merge the output
eqtl_outputs_scenic_regions_filtered_merged <- rbindlist(eqtl_outputs_scenic_regions_filtered)
# and add the region to the top effects
eqtl_top_var_feature_per_cs_filtered[['region']] <- eqtl_outputs_scenic_regions_filtered_merged[
  match(paste(eqtl_top_var_feature_per_cs_filtered[['variant']], eqtl_top_var_feature_per_cs_filtered[['feature']]), 
        paste(eqtl_outputs_scenic_regions_filtered_merged[['snp_id']], eqtl_outputs_scenic_regions_filtered_merged[['feature_id']])
        ), 
][['region']]


```

```{r tf_region_ld, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# get normal top effect per gene
eqtl_top_var_cs <- get_top_effect_per_cs(eqtl_outputs)
# get LD information as well
ld_info_loc <- '/groups/umcg-franke-scrna/tmp02/projects/multiome/ongoing/qtl/caqtl/sc-eqtlgen/GWAS_enrichment/GWAS_vars/moldpairs/1000G_HC/eurpop/immune-gwas-catalog-download-associations-alt-full-moldpairs_ld_pairs.tsv.gz'
# read the ld info
ld_info <- fread(ld_info_loc, header = T, sep = '\t')
# make one set with ld onto itself
eqtl_top_var_cs_self <- cbind(eqtl_top_var_cs, data.frame('ld_variant' = eqtl_top_var_cs[['variant']], 'R2' = rep(1, times = nrow(eqtl_top_var_cs))))
# add ld info to the top variants
eqtl_top_var_cs_other <- merge(x = eqtl_top_var_cs, y = ld_info, by.x = 'variant', by.y = 'index_variant')
# now merge them
eqtl_top_var_cs_ld <- rbind(eqtl_top_var_cs_self, eqtl_top_var_cs_other)
# filter by LD
eqtl_top_var_cs_ld <- eqtl_top_var_cs_ld[eqtl_top_var_cs_ld[['R2']] > .75, ]

```

```{r overlap_effects, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# read the location of the UCSC annotations
gene_anno_loc <- '/groups/umcg-franke-scrna/tmp02/projects/multiome/ongoing/scenicplus_workdir/scplus_pipeline_merged_major_and_minor_celltypes/output/genome_annotation.tsv'
gene_anno <- fread(gene_anno_loc, header = T, sep = '\t')
# rename columns to be the same as in limix
colnames(gene_anno) <-c('chrom', 'start', 'end', 'strand', 'gs','Transcription_Start_Site','Transcript_type')
# get gene info
tf_region_ieqtls_overlap_gene_info <- gene_anno[match(tf_region_ieqtls_overlap[['gene']], gene_anno[['gs']]), ]
# make columns gene specific
colnames(tf_region_ieqtls_overlap_gene_info) <- c('gene_chromosome', 'gene_start', 'gene_end', 'gene_strand', 'gs', 'gene_tss', 'gene_tt')
# remove gs column
tf_region_ieqtls_overlap_gene_info[['gs']] <- NULL
# add to the overlap table
tf_region_ieqtls_overlap <- cbind(tf_region_ieqtls_overlap, tf_region_ieqtls_overlap_gene_info)

# read the cpeaks annotation
cpeaks_anno_loc <- '/groups/umcg-franke-scrna/tmp02/external_datasets/cPeaks/cPeaks_wscreenv4.tsv.gz'
cpeaks_anno <- fread(cpeaks_anno_loc, header = T, sep = '\t')
# add the Signac style name
cpeaks_anno[['signac_hg38']] <- paste(cpeaks_anno[['chr_hg38']], cpeaks_anno[['start_hg38']], cpeaks_anno[['end_hg38']], sep = '-')
# as well as the SCENIC+ style name
cpeaks_anno[['scenic_hg38']] <- paste0(cpeaks_anno[['chr_hg38']], ':', cpeaks_anno[['start_hg38']], '-', cpeaks_anno[['end_hg38']])
# get cpeak info
tf_region_ieqtls_overlap_peak_info <- cpeaks_anno[match(tf_region_ieqtls_overlap[['region.y']], cpeaks_anno[['signac_hg38']]), c('chr_hg38', 'start_hg38', 'end_hg38')]
# make columns gene specific
colnames(tf_region_ieqtls_overlap_peak_info) <- c('peak_chromosome', 'peak_start', 'peak_end')
# add to the overlap table
tf_region_ieqtls_overlap <- cbind(tf_region_ieqtls_overlap, tf_region_ieqtls_overlap_peak_info)

# read the variant annotation
variant_anno_loc <- '/groups/umcg-franke-scrna/tmp02/projects/multiome/ongoing/qtl/eqtl/annotations/mo_qtl_variants_tested_cpeaks_overlap.tsv.gz'
variant_anno <- fread(variant_anno_loc, header = T, sep = '\t')
# get info
tf_region_ieqtls_overlap_variant_info <- variant_anno[match(tf_region_ieqtls_overlap[['variant']], variant_anno[['snp_id']]), c('snp_chromosome', 'snp_position')]
# add to the overlap table
tf_region_ieqtls_overlap <- cbind(tf_region_ieqtls_overlap, tf_region_ieqtls_overlap_variant_info)

# get distances
peak_gene_distances <- get_closest_flanks(tf_region_ieqtls_overlap, 'peak_start', 'peak_end', 'gene_start', 'gene_end')
# add that to the original table
tf_region_ieqtls_overlap[['peak_gene_dist']] <- peak_gene_distances[['min_dist']]
# same for variant to peak
var_peak_distances <- get_closest_flanks(tf_region_ieqtls_overlap, 'snp_position', 'snp_position', 'peak_start', 'peak_end')
tf_region_ieqtls_overlap[['var_peak_dist']] <- var_peak_distances[['min_dist']]
# same for variant to gene
var_gene_distances <- get_closest_flanks(tf_region_ieqtls_overlap, 'snp_position', 'snp_position', 'gene_start', 'gene_end')
tf_region_ieqtls_overlap[['var_gene_dist']] <- var_gene_distances[['min_dist']]

# add caQTL annotation
caqtl_outputs_all <- rbindlist(caqtl_outputs, fill = T)
tf_region_ieqtls_overlap[['is_caqtl']] <- paste(tf_region_ieqtls_overlap[['variant']], tf_region_ieqtls_overlap[['region.y']]) %in% paste(caqtl_outputs_all[['snp_id']], caqtl_outputs_all[['feature_id']])

# add qtl info
eqtl_outputs_all <- rbindlist(eqtl_outputs)
# filter also by variant-level significance
eqtl_outputs_all <- eqtl_outputs_all[eqtl_outputs_all[['p_value']] <= eqtl_outputs_all[['pval_nominal_threshold_global']], ]
tf_region_ieqtls_overlap[['is_eqtl']] <- paste(tf_region_ieqtls_overlap[['variant']], tf_region_ieqtls_overlap[['gene']]) %in% paste(eqtl_outputs_all[['snp_id']], eqtl_outputs_all[['feature_id']])


```

```{r plot_overlaps, include=TRUE, fig.width=10, fig.height=10}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# plot the region-gene relation and the TF-gene relation
plot_concondance(tf_region_ieqtls_overlap, d1_effect_column = 'region_beta.y', d2_effect_column = 'region_beta.x') + ggtitle('peak-gene vs TF-gene beta')
# plot the genotype-gene relation
plot_concondance(tf_region_ieqtls_overlap, d1_effect_column = 'genotype_beta.y', d2_effect_column = 'genotype_beta.x') + ggtitle('peak vs TF eQTL beta model')

# add a signed beta to show how the effect size becomes stronger
tf_region_ieqtls_overlap[['region:genotype_beta.x_directed']] <- sign(tf_region_ieqtls_overlap[['genotype_beta.x']]) * tf_region_ieqtls_overlap[['region:genotype_beta.x']]
tf_region_ieqtls_overlap[['region:genotype_beta.y_directed']] <- sign(tf_region_ieqtls_overlap[['genotype_beta.y']]) * tf_region_ieqtls_overlap[['region:genotype_beta.y']]
# then plot that
plot_grid(
  plot_concondance(tf_region_ieqtls_overlap[tf_region_ieqtls_overlap[['is_eqtl']], ], d1_effect_column = 'region:genotype_beta.y_directed', d2_effect_column = 'region:genotype_beta.x_directed') + ggtitle('is eQTL i-egene beta'),
plot_concondance(tf_region_ieqtls_overlap[tf_region_ieqtls_overlap[['is_eqtl']] & tf_region_ieqtls_overlap[['is_caqtl']], ], d1_effect_column = 'region:genotype_beta.y_directed', d2_effect_column = 'region:genotype_beta.x_directed') + ggtitle('is caQTL+eQTL i-egene beta'),
plot_concondance(tf_region_ieqtls_overlap[tf_region_ieqtls_overlap[['is_eqtl']] & !(tf_region_ieqtls_overlap[['is_caqtl']]), ], d1_effect_column = 'region:genotype_beta.y_directed', d2_effect_column = 'region:genotype_beta.x_directed') + ggtitle('only eQTL i-egene beta'),
plot_concondance(tf_region_ieqtls_overlap[(!(tf_region_ieqtls_overlap[['is_eqtl']])) & (tf_region_ieqtls_overlap[['is_caqtl']]), ], d1_effect_column = 'region:genotype_beta.y_directed', d2_effect_column = 'region:genotype_beta.x_directed') + ggtitle('only caQTL i-egene beta'), 
plot_concondance(tf_region_ieqtls_overlap[((tf_region_ieqtls_overlap[['is_eqtl']])) & (tf_region_ieqtls_overlap[['is_caqtl']]) & tf_region_ieqtls_overlap[['var_peak_dist']] == 0, ], d1_effect_column = 'region:genotype_beta.y_directed', d2_effect_column = 'region:genotype_beta.x_directed') + ggtitle('only caQTL+eQTL in chromatin region i-egene beta'), 
plot_concondance(tf_region_ieqtls_overlap[((tf_region_ieqtls_overlap[['is_eqtl']])) & (tf_region_ieqtls_overlap[['is_caqtl']]) & tf_region_ieqtls_overlap[['var_peak_dist']] == 0, ], d1_effect_column = 'region:genotype_beta.y_directed', d2_effect_column = 'region:genotype_beta.x_directed') + ggtitle('only caQTL+eQTL in chromatin region i-egene beta'), 
plot_concondance(tf_region_ieqtls_overlap[tf_region_ieqtls_overlap[['var_peak_dist']] == 0, ], d1_effect_column = 'region:genotype_beta.y_directed', d2_effect_column = 'region:genotype_beta.x_directed') + ggtitle('in chromatin region i-egene beta')
)
plot_concondance(tf_region_ieqtls_overlap[((tf_region_ieqtls_overlap[['is_eqtl']])) & (tf_region_ieqtls_overlap[['is_caqtl']]) & tf_region_ieqtls_overlap[['var_peak_dist']] == 0, ], d1_effect_column = 'region:genotype_beta.y_directed', d2_effect_column = 'region:genotype_beta.x_directed') + ggtitle('only caQTL+eQTL in chromatin region i-egene beta')


```

```{r filter_inputs, include=TRUE, fig.width=10, fig.height=10}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# get the replication set
tf_ieqtl_rep_loc <- '/groups/umcg-franke-scrna/tmp02/projects/multiome/ongoing/cre_detection/limix_sc/output/tf_interaction/sc/all/lane_donor_countrna_inclcaqtls_varinregion_significant/merged/results_fdr.tsv.gz'
tf_ieqtls_rep <- fread(tf_ieqtl_rep_loc, header = T, sep = '\t')

# remove the TF-i-eGene that was removed from the name (it was added in the second pass)
tf_ieqtls_rep[['region']] <- gsub('\\)_.*', ')', tf_ieqtls_rep[['region']])

# get what is significant
tf_ieqtls_rep_sig <- tf_ieqtls_rep[
  tf_ieqtls_rep[['region:genotype_bh']] < 0.05 & 
    tf_ieqtls_rep[['anova_bh']] < 0.05 & 
    # tf_ieqtls_eqtl[['region_bh']] < 0.05 &
    # tf_ieqtls_eqtl[['genotype_bh']] < 0.05, 
    tf_ieqtls_rep[['region_bh']] < 0.05, 
]

# subset the set to what is an eqtl
tf_ieqtls_rep_eqtl <- tf_ieqtls_rep[
  paste(tf_ieqtls_rep[['variant']], tf_ieqtls_rep[['gene']]) %in% paste(eqtl_outputs_all[['snp_id']], eqtl_outputs_all[['feature_id']]), 
]
# filter by what was in LD with a top variant
tf_ieqtls_rep_eqtl <- tf_ieqtls_rep_eqtl[paste(tf_ieqtls_rep_eqtl[['variant']], tf_ieqtls_rep_eqtl[['gene']]) %in% paste(eqtl_top_var_cs_ld[['ld_variant']], eqtl_top_var_cs_ld[['feature']]), ]
# reapply fdr
for (pcolumn in grep('_p$', colnames(tf_ieqtls_rep_eqtl), value = T)) {
  tf_ieqtls_rep_eqtl[[gsub('_p$', '_bh', pcolumn)]] <- p.adjust(tf_ieqtls_rep_eqtl[[pcolumn]], method = 'BH')
  tf_ieqtls_rep_eqtl[[gsub('_p$', '_bf', pcolumn)]] <- p.adjust(tf_ieqtls_rep_eqtl[[pcolumn]], method = 'bonferroni')
}

# get what is significant
tf_ieqtls_rep_sig_eqtl <- tf_ieqtls_rep_eqtl[
  tf_ieqtls_rep_eqtl[['region:genotype_bh']] < 0.05 & 
    tf_ieqtls_rep_eqtl[['anova_bh']] < 0.05 & 
    # tf_ieqtls_eqtl[['region_bh']] < 0.05 &
    # tf_ieqtls_eqtl[['genotype_bh']] < 0.05, 
    tf_ieqtls_rep_eqtl[['region_bh']] < 0.05, 
]

# merge the tf and region qtls
tf_eqtl_rep_region_ieqtls_overlap <- merge(
  tf_ieqtls_rep_sig_eqtl, 
  region_ieqtls_sig, 
  by.x = c('variant', 'gene'), 
  by.y = c('variant', 'gene')
)

# add qtl annotation
tf_eqtl_rep_region_ieqtls_overlap[['is_caqtl']] <- paste(tf_eqtl_rep_region_ieqtls_overlap[['variant']], tf_eqtl_rep_region_ieqtls_overlap[['region.y']]) %in% paste(caqtl_outputs_all[['snp_id']], caqtl_outputs_all[['feature_id']])
tf_eqtl_rep_region_ieqtls_overlap[['is_eqtl']] <- paste(tf_eqtl_rep_region_ieqtls_overlap[['variant']], tf_eqtl_rep_region_ieqtls_overlap[['gene']]) %in% paste(eqtl_outputs_all[['snp_id']], eqtl_outputs_all[['feature_id']])

# renaem columns
colnames(tf_eqtl_rep_region_ieqtls_overlap) <- gsub('^region.x$', 'TF', colnames(tf_eqtl_rep_region_ieqtls_overlap))
colnames(tf_eqtl_rep_region_ieqtls_overlap) <- gsub('^region.y$', 'region', colnames(tf_eqtl_rep_region_ieqtls_overlap))

# add signature of gene
tf_eqtl_rep_region_ieqtls_overlap[['Gene_signature_direction']] <- str_extract(tf_eqtl_rep_region_ieqtls_overlap[['TF']], '\\+\\/\\+|\\-\\/\\-|\\+\\/\\-|\\-\\/\\+')

# remove the TF-i-eGene that was removed from the name (it was added in the second pass)
tf_eqtl_rep_region_ieqtls_overlap[['TF']] <- gsub('\\)_.*', ')', tf_eqtl_rep_region_ieqtls_overlap[['TF']])

# keep only region-gene-tf pairs 
tf_eqtl_rep_region_ieqtls_overlap <- tf_eqtl_rep_region_ieqtls_overlap[
  paste(tf_eqtl_rep_region_ieqtls_overlap[['gene']], tf_eqtl_rep_region_ieqtls_overlap[['region']], tf_eqtl_rep_region_ieqtls_overlap[['TF']]) %in% paste(scenic_output[['Gene']], gsub(':', '-', scenic_output[['Region']]), scenic_output[['Gene_signature_name']]), 
]

# fix directions
tf_eqtl_rep_region_ieqtls_overlap[['region:genotype_beta.x_directed']] <- sign(tf_eqtl_rep_region_ieqtls_overlap[['genotype_beta.x']]) * tf_eqtl_rep_region_ieqtls_overlap[['region:genotype_beta.x']]
tf_eqtl_rep_region_ieqtls_overlap[['region:genotype_beta.y_directed']] <- sign(tf_eqtl_rep_region_ieqtls_overlap[['genotype_beta.y']]) * tf_eqtl_rep_region_ieqtls_overlap[['region:genotype_beta.y']]
# but refix if the direction is opposite
tf_eqtl_rep_region_ieqtls_overlap[tf_eqtl_rep_region_ieqtls_overlap[['Gene_signature_direction']] == '-/+', ][['region:genotype_beta.x_directed']] <- tf_eqtl_rep_region_ieqtls_overlap[tf_eqtl_rep_region_ieqtls_overlap[['Gene_signature_direction']] == '-/+', ][['region:genotype_beta.x_directed']] * -1
tf_eqtl_rep_region_ieqtls_overlap <- tf_eqtl_rep_region_ieqtls_overlap[order(tf_eqtl_rep_region_ieqtls_overlap[['region:genotype_p.x']]), ]
# with most significant region per TF
tf_eqtl_rep_region_ieqtls_overlap_toptf <- tf_eqtl_rep_region_ieqtls_overlap[!duplicated(paste(tf_eqtl_rep_region_ieqtls_overlap[['variant']], tf_eqtl_rep_region_ieqtls_overlap[['TF']])), ]

plot_concondance(tf_eqtl_rep_region_ieqtls_overlap[tf_eqtl_rep_region_ieqtls_overlap[['is_eqtl']] & !(tf_eqtl_rep_region_ieqtls_overlap[['is_caqtl']]), ], d1_effect_column = 'region:genotype_beta.y_directed', d2_effect_column = 'region:genotype_beta.x_directed') + ggtitle('only eQTL i-egene beta')
plot_concondance(tf_eqtl_rep_region_ieqtls_overlap_toptf[tf_eqtl_rep_region_ieqtls_overlap_toptf[['is_eqtl']] & !(tf_eqtl_rep_region_ieqtls_overlap_toptf[['is_caqtl']]), ], d1_effect_column = 'region:genotype_beta.y_directed', d2_effect_column = 'region:genotype_beta.x_directed') + ggtitle('only eQTL i-egene beta')

```

```{r compare_corrected_tf, include=TRUE, fig.height=5, fig.width=5}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# merge significant in either
tf_ieqtls_sig_both <- merge(
  tf_ieqtls_sig, 
  tf_ieqtls_rep_sig, 
  by = c('variant', 'region', 'gene')
)
# add info on the direction of the TF
tf_ieqtls_sig_both[['region_gene_direction']] <- str_extract(tf_ieqtls_sig_both[['region']], '\\+\\/\\+|\\-\\/\\-|\\+\\/\\-|\\-\\/\\+')
# add a signed beta to show how the effect size becomes stronger
tf_ieqtls_sig_both[['region:genotype_beta.x_directed']] <- sign(tf_ieqtls_sig_both[['genotype_beta.x']]) * tf_ieqtls_sig_both[['region:genotype_beta.x']]
tf_ieqtls_sig_both[['region:genotype_beta.y_directed']] <- sign(tf_ieqtls_sig_both[['genotype_beta.y']]) * tf_ieqtls_sig_both[['region:genotype_beta.y']]
# flip the beta again
tf_ieqtls_sig_both[tf_ieqtls_sig_both[['region_gene_direction']] == '-/+'][['region:genotype_beta.x_directed']] <- tf_ieqtls_sig_both[tf_ieqtls_sig_both[['region_gene_direction']] == '-/+'][['region:genotype_beta.x_directed']] * -1
# add z
tf_ieqtls_sig_both[['region:genotype_z.x_directed']] <- tf_ieqtls_sig_both[['region:genotype_beta.x_directed']] / tf_ieqtls_sig_both[['region:genotype_se.x']]
tf_ieqtls_sig_both[['region:genotype_z.y_directed']] <- tf_ieqtls_sig_both[['region:genotype_beta.y_directed']] / tf_ieqtls_sig_both[['region:genotype_se.y']]

# then show them
plot_concondance(tf_ieqtls_sig_both, d1_effect_column = 'region:genotype_beta.x_directed', d2_effect_column = 'region:genotype_beta.y_directed') + 
  xlab('uncorrected TF-i-eQTL beta') +
  ylab('corrected TF-i-eQTL beta') +
  ggtitle('Uncorrected vs corrected TF-i-eQTL beta')

plot_concondance(tf_ieqtls_sig_both[
  tf_ieqtls_sig_both[['anova_bf.x']] < 0.05 &
  tf_ieqtls_sig_both[['anova_bf.y']] < 0.05 &
  tf_ieqtls_sig_both[['region:genotype_bf.x']] < 0.05 &
  tf_ieqtls_sig_both[['region:genotype_bf.y']] < 0.05, 
  
], d1_effect_column = 'region:genotype_beta.x_directed', d2_effect_column = 'region:genotype_beta.y_directed') + 
  xlab('uncorrected TF-i-eQTL beta') +
  ylab('corrected TF-i-eQTL beta') +
  ggtitle('Uncorrected vs corrected TF-i-eQTL beta')

plot_concondance(tf_ieqtls_sig_both[
  tf_ieqtls_sig_both[['anova_bf.x']] < 0.05 &
  tf_ieqtls_sig_both[['anova_bf.y']] < 0.05 &
  tf_ieqtls_sig_both[['region:genotype_bf.x']] < 0.05 &
  tf_ieqtls_sig_both[['region:genotype_bf.y']] < 0.05, 
  
], d1_effect_column = 'region:genotype_z.x_directed', d2_effect_column = 'region:genotype_z.y_directed') + 
  xlab('uncorrected TF-i-eQTL Z-score') +
  ylab('corrected TF-i-eQTL Z-score') +
  ggtitle('Uncorrected vs corrected TF-i-eQTL Z-score')

```

```{r annotate_input, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# add all info to the full results as well
tf_ieqtls_gene_info <- gene_anno[match(tf_ieqtls[['gene']], gene_anno[['gs']]), ]
# make columns gene specific
colnames(tf_ieqtls_gene_info) <- c('gene_chromosome', 'gene_start', 'gene_end', 'gene_strand', 'gs', 'gene_tss', 'gene_tt')
# remove gs column
tf_ieqtls_gene_info[['gs']] <- NULL
# add to the overlap table
tf_ieqtls <- cbind(tf_ieqtls, tf_ieqtls_gene_info)

# get info
tf_ieqtls_variant_info <- variant_anno[match(tf_ieqtls[['variant']], variant_anno[['snp_id']]), c('snp_chromosome', 'snp_position')]
# add to the overlap table
tf_ieqtls <- cbind(tf_ieqtls, tf_ieqtls_variant_info)

# add caQTL annotation
tf_ieqtls[['is_caqtl']] <- paste(tf_ieqtls[['variant']], tf_ieqtls[['region.y']]) %in% paste(caqtl_outputs_all[['snp_id']], caqtl_outputs_all[['feature_id']])

# add qtl info
tf_ieqtls[['is_eqtl']] <- paste(tf_ieqtls[['variant']], tf_ieqtls[['gene']]) %in% paste(eqtl_outputs_all[['snp_id']], eqtl_outputs_all[['feature_id']])

# rename columns of 'region' to be tf
colnames(tf_ieqtls) <- gsub('region', 'tf', colnames(tf_ieqtls))
# and add the second round info
tf_ieqtls[['tf:genotype_p_rep']] <- tf_ieqtls_rep[match(paste(tf_ieqtls[['variant']], tf_ieqtls[['tf']], tf_ieqtls[['gene']]), paste(tf_ieqtls_rep[['variant']], tf_ieqtls_rep[['region']], tf_ieqtls_rep[['gene']])), ][['region:genotype_p']]
tf_ieqtls[['tf:genotype_bh_rep']] <- tf_ieqtls_rep[match(paste(tf_ieqtls[['variant']], tf_ieqtls[['tf']], tf_ieqtls[['gene']]), paste(tf_ieqtls_rep[['variant']], tf_ieqtls_rep[['region']], tf_ieqtls_rep[['gene']])), ][['region:genotype_bh']]
tf_ieqtls[['anova_p_rep']] <- tf_ieqtls_rep[match(paste(tf_ieqtls[['variant']], tf_ieqtls[['tf']], tf_ieqtls[['gene']]), paste(tf_ieqtls_rep[['variant']], tf_ieqtls_rep[['region']], tf_ieqtls_rep[['gene']])), ][['anova_p']]
tf_ieqtls[['anova_bh_rep']] <- tf_ieqtls_rep[match(paste(tf_ieqtls[['variant']], tf_ieqtls[['tf']], tf_ieqtls[['gene']]), paste(tf_ieqtls_rep[['variant']], tf_ieqtls_rep[['region']], tf_ieqtls_rep[['gene']])), ][['anova_bh']]
tf_ieqtls[['tf:genotype_beta_rep']] <- tf_ieqtls_rep[match(paste(tf_ieqtls[['variant']], tf_ieqtls[['tf']], tf_ieqtls[['gene']]), paste(tf_ieqtls_rep[['variant']], tf_ieqtls_rep[['region']], tf_ieqtls_rep[['gene']])), ][['region:genotype_beta']]
# add info on the direction of the TF
tf_ieqtls[['tf_gene_direction']] <- str_extract(tf_ieqtls[['tf']], '\\+\\/\\+|\\-\\/\\-|\\+\\/\\-|\\-\\/\\+')
# and whether it was flipped for the replication
tf_ieqtls[['replication_flip']] <- tf_ieqtls[['tf_gene_direction']] == '-/+'
# filter by significant as well
tf_ieqtls_repsig <- tf_ieqtls[
  !is.na(tf_ieqtls[['anova_bh_rep']]) &
  tf_ieqtls[['anova_bh_rep']] < 0.05 & 
  !is.na(tf_ieqtls[['tf:genotype_bh_rep']]) & 
  tf_ieqtls[['tf:genotype_bh_rep']] < 0.05, 
]

# set location of both tables
tf_ieqtls_annotated_loc <- paste(dirname(tf_ieqtl_loc), 'results_fdr_with_replication.tsv.gz', sep = '/')
tf_ieqtls_annotated_significant_loc <- paste(dirname(tf_ieqtl_loc), 'results_fdr_with_replication_significant.tsv.gz', sep = '/')
# save these
write.table(tf_ieqtls, gzfile(tf_ieqtls_annotated_loc), col.names = T, sep = '\t', quote = F, row.names = F)
mdfiver::create_sha256_for_file(tf_ieqtls_annotated_loc)
write.table(tf_ieqtls_repsig, gzfile(tf_ieqtls_annotated_significant_loc), col.names = T, sep = '\t', quote = F, row.names = F)
mdfiver::create_sha256_for_file(tf_ieqtls_annotated_significant_loc)


```
