---
title: "mo_limix_cre_celltype_replication"
author: "Roy Oelen"
date: "2025-07-21"
output: html_document
---

```{r header, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#!/usr/bin/env Rscript
############################################################################################################################
# Authors: Roy Oelen
# Name: mo_limix_cre_celltype_replication.Rmd
# Function: plot replication of CREs
############################################################################################################################
```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

####################
# libraries        #
####################

library(data.table)
library(ggplot2)
library(cowplot)
library(RColorBrewer)
library(roycols)
library(ggrastr)
library(ggpubr)
library(UpSetR)
library(grid)
library(IRanges)

```

```{r functions, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# Functions        #
####################


#' get a label dict that replaces the posix safe names into printable versions
#' 
#' @returns a label dict that replaces the posix safe names into printable versions
#' label_dict_names <- get_label_dict()
get_label_dict <- function() {
  label_dict <- list()
  label_dict[['CD4_T_cells']] <- 'CD4+ T cells'
  label_dict[['CD8_T_cells']] <- 'CD8+ T cells'
  label_dict[['CD4T']] <- 'CD4+ T'
  label_dict[['CD8T']] <- 'CD8+ T'
  label_dict[['CD4_T']] <- 'CD4+ T'
  label_dict[['CD8_T']] <- 'CD8+ T'
  label_dict[['Dendritic_cells']] <- 'Dendritic cells'
  label_dict[['Endothelial_cells']] <- 'Endothelial cells'
  label_dict[['Fibroblasts']] <- 'Fibroblasts'
  label_dict[['Glia_cells']] <- 'Glia cells'
  label_dict[['Mast_cells']] <- 'MAST cells'
  label_dict[['Mature_absorptive_enterocytes']] <- 'Mature absorptive enterocytes'
  label_dict[['Mature_secretory_enterocytes']] <- 'Mature secretory enterocytes'
  label_dict[['Memory_B']] <- 'Memory B cells'
  label_dict[['Monocytes']] <- 'Monocytes'
  label_dict[['monocyte']] <- 'Monocyte'
  label_dict[['Mono']] <- 'Monocyte'
  label_dict[['Plasma_cells']] <- 'Plasma cells'
  label_dict[['Stem_cells']] <- 'Stem cells'
  label_dict[['Stromal_cells']] <- 'Stromal cells'
  label_dict[['T_others']] <- 'other T cells'
  label_dict[['Transit_amplifying_cells']] <- 'Transit amplifying cells'
  label_dict[['AI']] <- 'Actively Inflamed'
  label_dict[['NI']] <- 'Non-Inflamed'
  return(label_dict)
}


rename_labels <- function(vector_to_rename) {
  # get the labels that are present
  label_renaming <- get_label_dict()
  # now check which labels we are missing
  missing_renames <- setdiff(unique(vector_to_rename), names(label_renaming))
  # add those renames as not being renames
  for (missing_rename in missing_renames) {
    label_renaming[[missing_rename]] <- missing_rename
  }
  # now replace each value with the rename
  renamed_vector <- as.vector(unlist(label_renaming[vector_to_rename]))
  # and return that
  return(renamed_vector)
}


remap_with_label_dict <- function(vector_of_names) {
  # get the label dict
  relabels <- get_label_dict()
  # get the labels available for renaming
  labels_available <- names(relabels)
  # get the ones we cant remap
  unmappable <- setdiff(unique(vector_of_names), labels_available)
  # report on those
  if (length(unmappable) > 0) {
    print(paste('cannot remap the following names, they will be returned unchanged:', paste(unmappable, collapse = ',')))
    # and put those in our remapping list as their originals
    relabels[unmappable] <- unmappable
  }
  # now actually do the remapping
  remapped <- as.vector(unlist(relabels[vector_of_names]))
  return(remapped)
}


get_color_coding_dict <- function() {
	# medhigh
  color_coding_dict <- list()
  color_coding_dict[["B"]] <- "#71BC4B"
  #color_coding_dict[['CD4_T_cells']] <- '#7FC97F'
  color_coding_dict[['CD4_T_cells']] <- '#153057'
  color_coding_dict[['CD4T']] <- '#153057'
	#color_coding_dict[['CD8_T_cells']] <- '#BEAED4'
	color_coding_dict[['CD8_T_cells']] <- '#009DDB'
	color_coding_dict[['CD8T']] <- '#009DDB'
	#color_coding_dict[['Dendritic_cells']] <- '#FDC086'
	color_coding_dict[['Dendritic_cells']] <- '#965EC8'
	color_coding_dict[['DC']] <- '#965EC8'
	color_coding_dict[['Endothelial_cells']] <- '#FFFFB3'
	color_coding_dict[['Fibroblasts']] <- '#386CB0'
	color_coding_dict[['Glia_cells']] <- '#F0027F'
	color_coding_dict[['Mast_cells']] <- '#BF5B17'
	color_coding_dict[['Mature_absorptive_enterocytes']] <- '#A6CEE3'
	color_coding_dict[['Mature_secretory_enterocytes']] <- '#1B9E77'
	color_coding_dict[['Memory_B']] <- '#D95F02'
	color_coding_dict[['Microfold_cell']] <- '#BEAED4'
	#color_coding_dict[['Monocytes']] <- '#7570B3'
	color_coding_dict[['Monocyte']] <- '#EDBA1B'
	color_coding_dict[['Naive_B_cells']] <- '#FDC086'
	color_coding_dict[['NK']] <- '#E64B50'
	#color_coding_dict[['Plasma_cells']] <- '#E7298A'
	color_coding_dict[['Plasma_cells']] <- '#DB8E00'
	color_coding_dict[['Stem_cells']] <- '#66A61E'
	color_coding_dict[['Stromal_cells']] <- '#8DD3C7'
	#color_coding_dict[['T_others']] <- '#A6761D'
	color_coding_dict[['T_others']] <- '#FF63B6'
	color_coding_dict[['Transit_amplifying_cells']] <- '#FF7F00'
	color_coding_dict[['disconcordant']] <- 'gray'
  #color_coding_dict[['CD4+ T cells']] <- '#7FC97F'
  color_coding_dict[['CD4+ T cells']] <- '#153057'
  color_coding_dict[['CD4+ T']] <- '#153057'
	#color_coding_dict[['CD8+ T cells']] <- '#BEAED4'
	color_coding_dict[['CD8+ T cells']] <- '#009DDB'
	color_coding_dict[['CD8+ T']] <- '#009DDB'
	#color_coding_dict[['Dendritic cells']] <- '#FDC086'
	color_coding_dict[['Dendritic cells']] <- '#965EC8'
	color_coding_dict[['Endothelial cells']] <- '#FFFFB3'
	color_coding_dict[['Endothelial\ncells']] <- '#FFFFB3'
	color_coding_dict[['Fibroblasts']] <- '#386CB0'
	color_coding_dict[['Glia cells']] <- '#F0027F'
	color_coding_dict[['MAST cells']] <- '#BF5B17'
	color_coding_dict[['Mature absorptive enterocytes']] <- '#A6CEE3'
	color_coding_dict[['Mature\nabsorptive\nenterocytes']] <- '#A6CEE3'
	color_coding_dict[['Mature secretory enterocytes']] <- '#1B9E77'
	color_coding_dict[['Mature secretory\nenterocytes']] <- '#1B9E77'
	color_coding_dict[['Memory B cells']] <- '#D95F02'
	#color_coding_dict[['Monocytes']] <- '#7570B3'
	color_coding_dict[['Microfold cells']] <- '#BEAED4'
	color_coding_dict[['Monocytes']] <- '#EDBA1B'
	color_coding_dict[['monocyte']] <- '#EDBA1B'
	color_coding_dict[['Monocyte']] <- '#EDBA1B'
	color_coding_dict[['Naive B cells']] <- '#FDC086'
	#color_coding_dict[['Plasma cells']] <- '#E7298A'
	color_coding_dict[['Plasma cells']] <- '#DB8E00'
	color_coding_dict[['Stem cells']] <- '#66A61E'
	color_coding_dict[['Stromal cells']] <- '#8DD3C7'
	#color_coding_dict[['other T cells']] <- '#A6761D'
	color_coding_dict[['other T cells']] <- '#FF63B6'
	color_coding_dict[['Transit amplifying cells']] <- '#FF7F00'
	color_coding_dict[['Transit\namplifying cells']] <- '#FF7F00'
	color_coding_dict[['disconcordant']] <- 'gray'
	# up and down regulation will be added to, we need a whitening percentage
	pct_whitening <- 40
	# then we will check each cell type
	for (cell_type in names(color_coding_dict)) {
	  # the up color is the same as the regular one
	  color_coding_dict[[paste(cell_type, 'up')]] <- color_coding_dict[[cell_type]]
	  # but the down one will have a more faded colour
	  color_coding_dict[[paste(cell_type, 'down')]] <- colorRampPalette(c(color_coding_dict[[cell_type]], "white"))(100)[pct_whitening]
	  # we'll do something similiar when we have multiple conditions
	  color_coding_dict[[paste(cell_type, 'combined')]] <- color_coding_dict[[cell_type]]
	  color_coding_dict[[paste(cell_type, 'UT')]] <- colorRampPalette(c(color_coding_dict[[cell_type]], "white"))(100)[pct_whitening]
	  color_coding_dict[[paste(cell_type, '24hCA')]] <- colorRampPalette(c(color_coding_dict[[cell_type]], "black"))(100)[pct_whitening]
	}
	# general
	color_coding_dict[['AI']] <- 'darkblue'
	color_coding_dict[['NI']] <- 'darkred'
	color_coding_dict[['Actively Inflamed']] <- 'darkblue'
	color_coding_dict[['Non-Inflamed']] <- 'darkred'
	return(color_coding_dict)
}


split_string_with_max_length <- function(string, max_length=15) {
  # split the string on the space first
  words <- strsplit(string, ' ')[[1]]
  # and initial pasted string
  final_string <- ''
  # and the temporary string
  tmp_string <- ''
  # check each word
  for (word in words) {
    # get the lenght of the temporary string
    tmp_len <- nchar(tmp_string)
    # get the length of the word
    word_len <- nchar(word)
    # length of the final string
    final_len <- nchar(final_string)
    # check if adding the next word would make us go over the limit
    if ((tmp_len + word_len) > max_length) {
      if (final_len > 0) {
        # add the temporary word to the final string if it was not empty
        final_string <- paste(final_string, '\n', tmp_string, sep = '')
      }
      else{
        # if there was not final string yet, it will just become that temporary string
        final_string <- tmp_string
      }
      # reset the temporary string
      tmp_string <- word
    }
    else{
      # otherwise add it to the temporary string
      if (tmp_len > 0) {
        tmp_string <- paste(tmp_string, word)
      }
      # or set if the temporary string was empty
      else{
        tmp_string <- word
      }
    }
  }
  # add last word
  if (nchar(paste(final_string, tmp_string)) > max_length) {
    if (nchar(final_string) == 0) {
      final_string <- tmp_string
    }
    else if (nchar(tmp_string > 0)) {
      final_string <- paste(final_string, '\n', tmp_string, sep = '')
    }
    else{
      # nothing the final string is as it is
    }
  }
  else {
    if (nchar(final_string) == 0) {
      final_string <- tmp_string
    }
    else if(nchar(tmp_string) == 0){
      # nothing, the final string is as is
    }
    else{
      final_string <- paste(final_string, ' ', tmp_string, sep = '')
    }
  }
  # add the last word
  return(final_string)
}


split_strings_with_max_length <- function(strings, max_length=15) {
  strings_split <- sapply(strings, FUN = function(x){
    split_string_with_max_length(x, max_length)
  })
  strings_split <- as.vector(strings_split)
  return(strings_split)
}


#' get the eGenes per cell type from QTL output
#' 
#' @param qtl_output_loc base location of the QTL output per cell type
#' @param output_file which output file to read for the results
#' @param gene_column which column to use as the gene identifier
#' @returns a list with the egenes per cell type
#' 
get_egenes_per_celltype_limix <- function(qtl_output_loc, output_file='qtl_results_all.txt.gz', gene_column='feature_id', significance_column='feature_q_value', significance_cutoff=0.05, verbose=T) {
  # get the folders in the directory, which should be the cell types
  cell_types <- list.dirs(qtl_output_loc, full.names = F, recursive = F)
  # we will store the results in a list for now
  egenes_per_celltype <- list()
  # check each cell type
  for (cell_type in cell_types) {
    # paste together the full path
    full_cell_type_path <- paste(qtl_output_loc, '/', cell_type, '/', output_file, sep = '')
    # log if requested
    if (verbose) {
      print(paste('reading', full_cell_type_path))
    }
    # read the file
    cell_type_output <- read.table(full_cell_type_path, sep = '\t', header = T)
    # filter the results on significance
    if (!is.null(significance_column)) {
      # print progress if requested
      if (verbose) {
        print(paste('variant+phenotype before filtering', nrow(cell_type_output)))
      }
      # filter
      cell_type_output <- cell_type_output[
        !is.na(cell_type_output[[significance_column]]) &
          cell_type_output[[significance_column]] < significance_cutoff, 
      ]
      if (verbose) {
        print(paste('variant+phenotype after filtering', nrow(cell_type_output)))
      }
    }
    # get the unique genes in this file
    unique_genes <- unique(cell_type_output[[gene_column]])
    # add to the list
    egenes_per_celltype[[cell_type]] <- unique_genes
  }
  # turn into a dataframe
  return(egenes_per_celltype)
}



#' Plot Sharing of  Genes per Cell Type
#'
#' This function plots the sharing of differentially genes across cell types using an UpSet plot. It allows the use of custom label and color dictionaries.
#'
#' @param genes_per_ct list with the genes for each cell type
#' @param use_label_dict A logical value indicating whether to use a custom label dictionary for renaming cell types. Default is TRUE.
#' @param use_color_dict A logical value indicating whether to use a custom color dictionary for cell types. Default is TRUE.
#' @param n_intersects value describing how many intersections to plot, default is all
#' @return An UpSet plot showing the sharing of DE genes across cell types.
#'
plot_sharing_per_celltype <- function(genes_per_ct, use_label_dict=T, use_color_dict=T, n_intersects=NA){
  # get the total overlap
  total_overlap <- fromList(genes_per_ct)
  # count how many in each overlap
  combination_to_overlap <- list()
  apply(total_overlap, 1, function(x){
    # get which ones have a number
    positions_1 <- x > 0
    # get which these are, and paste together
    cols_1 <- paste(colnames(total_overlap)[positions_1], collapse = ',')
    # add to list if does not exist
    if (cols_1 %in% c(names(combination_to_overlap))) {
      combination_to_overlap[[cols_1]] <<- combination_to_overlap[[cols_1]] + 1
    }
    else{
      combination_to_overlap[[cols_1]] <<- 1
    }
  })
  # make into an ordered df
  combination_numbers <- data.frame('combination' = names(combination_to_overlap), 'nr' = as.vector(unlist(combination_to_overlap)))
  combination_numbers <- combination_numbers[order(combination_numbers[['nr']], combination_numbers[['combination']], decreasing = T), ]
  # get lowest number we have for the sets
  intersect_size_smallest <- 0
  if (is.na(n_intersects)) {
    intersect_size_smallest <- min(combination_numbers[['nr']])
  }
  else {
    intersect_size_smallest <- combination_numbers[n_intersects, 'nr']
  }
  # set queries and colours
  queries <- list()
  sets.bar.color <- 'black'
  if(use_color_dict){
    # create df to store the number of each set, so we know how to order
    nrs_df <- NULL
    # get the cell types we have
    cell_types <- names(genes_per_ct)
    # get colour codes for the cell types
    cell_type_colours <- get_color_coding_dict()
    # also get colours for the cell types we don't have colours for
    cell_type_colours_missing <- get_color_list(setdiff(cell_types, names(cell_type_colours)))
    # and merge them
    cell_type_colours <- c(cell_type_colours, cell_type_colours_missing)
    # add the colors for the cell types
    i <- 1
    for(cell_type in cell_types){
      # check if there is a singleton for this cell type, so this celltype is 1, but the total of the row is also 1
      n_singletons <- nrow(total_overlap[total_overlap[[cell_type]] == 1 & rowSums(total_overlap) == 1, ])
      # if we have singletons, colour it
      if (n_singletons > 0 & n_singletons >= intersect_size_smallest) {
        # add for the singles in the intersection sizes
        ct_list <- list(
          query = intersects,
          params = list(cell_type),
          color = cell_type_colours[[cell_type]],
          active = T)
        queries[[i]] <- ct_list
        i <- i + 1
      }
      # add for the DF to order the set sizes
      numbers_row <- data.frame(ct=c(cell_type), nr=c(length(genes_per_ct[[cell_type]])), stringsAsFactors = F)
      if(is.null(nrs_df)){
        nrs_df <- numbers_row
      }
      else{
        nrs_df <- rbind(nrs_df, numbers_row)
      }
    }
    # get the order of the sets
    ordered_cts <- nrs_df[order(nrs_df$nr, decreasing = T), 'ct']
    # add the colors for the sets
    sets.bar.color <- unlist(cell_type_colours[ordered_cts])
    # make the plot
    upset(total_overlap, order.by = 'freq', nsets = length(genes_per_ct), queries = queries, sets.bar.color=sets.bar.color, nintersects = n_intersects)
  }
  else {
    upset(total_overlap, order.by = 'freq', nsets = length(genes_per_ct), nintersects = n_intersects)
  }
  
  #return(DE_genes_per_ct)
}

#' plot in a barplot the number of DE genes per cell type
#' 
#' @param egene_numbers the table containing the number of eenes per cell type
#' @param celltype_column which column of the supplied table has the celltype name
#' @param number_column which column of the supplied table has the number of DE genes
#' @param pointless draw the ticks on the bottom of the plot?
#' @param legendless draw the legend?
#' @param ylim the range for the y-axis
#' @param paper_style use the paper style with more whitespace
#' @param angle_labels angle the x labels 90 degrees?
#' @param use_distinct_colours use the distinct colour palette instead of ggplot defaults (optional, default T)
#' @param use_sampling randomly sample colours from the distinct colour palette (optional, default F)
#' @param color_indices supply specific indices relating to colours to use from the distinct colour palette. Use 'get_available_colours_grid' to get the colours and their indices (optional, unused by default)
#' @param use_label_dict change names to a more pleasing format
#' @param make_labels_multiline make labels multiline if they are long
#' @param x_order to order the values on the x axis
#' @returns a barplot with the number of eGenes per cell type
#' 
egene_numbers_to_plot <- function(egene_numbers, celltype_column='cell_type', number_column='nr', pointless=F, legendless=F, ylim=NULL, paper_style=T, angle_labels=T, use_distinct_colours=T, use_sampling=F, color_indices=NULL, use_color_dict=F, use_label_dict=T, split_long_labels_to_lines=T, x_order=NULL) {
  # remap names if requested
  if (use_label_dict) {
    egene_numbers[[celltype_column]] <- remap_with_label_dict(egene_numbers[[celltype_column]])
  }
  # make them multiline
  if (split_long_labels_to_lines) {
    egene_numbers[[celltype_column]] <- split_strings_with_max_length(egene_numbers[[celltype_column]])
  }
  # order the x axis if requested
  if (!is.null(x_order)) {
    egene_numbers[[celltype_column]] <- factor(egene_numbers[[celltype_column]], levels = x_order)
  }
  # start plot
  p <- ggplot(mapping = aes(x = egene_numbers[[celltype_column]], y = egene_numbers[[number_column]], fill = egene_numbers[[celltype_column]])) +
    geom_bar(stat='identity') + xlab(celltype_column) + ylab(number_column)
  # options
  if (use_distinct_colours) {
    # get the unique possible assigments
    possible_assignments <- unique(egene_numbers[[celltype_column]])
    # put into a list
    colour_mapping <- roycols::get_color_list(possible_assignments)
    # add to plot
    p <- p + scale_fill_manual(values = colour_mapping)
  }
  if (use_color_dict) {
    # get the color coding dict
    colour_mapping <- get_color_coding_dict()
    # also rename here then
    if (split_long_labels_to_lines) {
      names(colour_mapping) <- split_strings_with_max_length(names(colour_mapping))
    }
    # add to plot
    p <- p + scale_fill_manual(values = colour_mapping)
  }
  if(!is.null(ylim)){
    p <- p + ylim(ylim)
  }
  if(pointless){
    p <- p + theme(axis.text.x=element_blank(), 
                   axis.ticks = element_blank())
  }
  if(legendless){
    p <- p + theme(legend.position = 'none')
  }
  if (paper_style) {
    p <- p + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white"))
  }
  if (angle_labels) {
    p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  }
  return(p)
}


match_qtl_outputs <- function(replicating_qtl_folder, replicating_in_qtl_folder, replicating_name='replicating', replicating_in_name='replicating_in', 
                              replicating_qtl_prepend='qtl_results_all_qval_', replicating_qtl_append='.txt.gz', replicating_qtl_pval_column='p_value', replicating_qtl_feature_column='feature_id', replicating_qtl_variant_column='snp_id', replicating_qtl_fdr_column='feature_q_value', replicating_qtl_beta_column='beta', replicating_qtl_se_column='beta_se', replicating_qtl_aa_column='assessed_allele', replicating_qtl_fdr_cutoff=0.05, 
                              replicating_in_qtl_prepend='qtl_results_all_qval_', replicating_in_qtl_append='.txt.gz', replicating_in_qtl_pval_column='p_value', replicating_in_qtl_feature_column='feature_id', replicating_in_qtl_variant_column='snp_id', replicating_in_qtl_fdr_column='feature_q_value', replicating_in_qtl_beta_column='beta', replicating_in_qtl_se_column='beta_se', replicating_in_qtl_aa_column='assessed_allele', replicating_in_qtl_fdr_cutoff=0.05, nosplit=F) {
  # we'll store both in lists
  replicating_top_qtl <- list()
  replicating_in_qtl_matched <- list()
  # we'll do every chromosome
  chromosomes <- 1:22
  # unless we don't have a split
  if (nosplit) {
    chromosomes <- c('')
  }
  # we'll check each chromosome
  for (chromosome in chromosomes) {
    # progress
    message(paste('doing chromosome', chromosome))
    # paste together the path
    replicating_qtl_chromosome_loc <- paste0(replicating_qtl_folder, '/', replicating_qtl_prepend, chromosome, replicating_qtl_append)
    # read this output
    replicating_qtl_chromosome <- fread(replicating_qtl_chromosome_loc, header = T, sep = '\t')
    # order by significance
    replicating_qtl_chromosome <- replicating_qtl_chromosome[order(replicating_qtl_chromosome[[replicating_qtl_pval_column]]), ]
    # and get just top effects
    replicating_qtl_chromosome_top <- replicating_qtl_chromosome[!duplicated(replicating_qtl_chromosome[[replicating_qtl_feature_column]]), ]
    # add the qtl column
    replicating_qtl_chromosome_top[['qtl']] <- paste0(replicating_qtl_chromosome_top[[replicating_qtl_feature_column]], '_', replicating_qtl_chromosome_top[[replicating_qtl_variant_column]])
    # and significance
    if (isTRUE(replicating_qtl_fdr_cutoff)) {
      # if we have a T value instead of a number, we'll just use that instead of a cutoff value
      replicating_qtl_chromosome_top[['significant']] <- replicating_qtl_chromosome_top[[replicating_qtl_fdr_column]]
    } else {
      replicating_qtl_chromosome_top[['significant']] <- replicating_qtl_chromosome_top[[replicating_qtl_fdr_column]] < replicating_qtl_fdr_cutoff & replicating_qtl_chromosome_top[[replicating_qtl_pval_column]] < 0.05
    }
    # calculate the Z
    replicating_qtl_chromosome_top[['zscore']] <- replicating_qtl_chromosome_top[[replicating_qtl_beta_column]] / replicating_qtl_chromosome_top[[replicating_qtl_se_column]]
    # subset to the column we want
    replicating_qtl_chromosome_top <- replicating_qtl_chromosome_top[, c('qtl', 'zscore', ..replicating_qtl_aa_column, 'significant', ..replicating_qtl_fdr_column, ..replicating_qtl_pval_column, ..replicating_qtl_beta_column, ..replicating_qtl_se_column)]
    # rename the columns to not conflict
    colnames(replicating_qtl_chromosome_top) <-c('qtl', paste(replicating_name, c('zscore', 'assessed_allele', 'significant', 'fdr', 'p', 'beta', 'se'), sep = '_'))
  
    # now paste the onek1k path
    replicating_in_qtl_chromosome_loc <- paste0(replicating_in_qtl_folder, '/', replicating_in_qtl_prepend, chromosome, replicating_in_qtl_append)
    # read this output
    replicating_in_qtl_chromosome <- fread(replicating_in_qtl_chromosome_loc, header = T, sep = '\t')
    # add the qtl column
    replicating_in_qtl_chromosome[['qtl']] <- paste0(replicating_in_qtl_chromosome[[replicating_in_qtl_feature_column]], '_', replicating_in_qtl_chromosome[[replicating_in_qtl_variant_column]])
    # and keep only matching QTLs from our UT output
    replicating_in_qtl_chromosome <- replicating_in_qtl_chromosome[replicating_in_qtl_chromosome[['qtl']] %in% replicating_qtl_chromosome_top[['qtl']], ]
    # and significance
    if (isTRUE(replicating_in_qtl_fdr_cutoff)) {
      # if the value is a straight-up T, then we use it as-is without using a cutoff value
      replicating_in_qtl_chromosome[['significant']] <- replicating_in_qtl_chromosome[[replicating_in_qtl_fdr_column]]
    } else {
      replicating_in_qtl_chromosome[['significant']] <- replicating_in_qtl_chromosome[[replicating_in_qtl_fdr_column]] < replicating_in_qtl_fdr_cutoff & replicating_in_qtl_chromosome[[replicating_in_qtl_pval_column]] < 0.05
    }
    # calculate the Z
    replicating_in_qtl_chromosome[['zscore']] <- replicating_in_qtl_chromosome[[replicating_in_qtl_beta_column]] / replicating_in_qtl_chromosome[[replicating_in_qtl_se_column]]
    # subset to the column we want
    replicating_in_qtl_chromosome <- replicating_in_qtl_chromosome[, c('qtl', 'zscore', ..replicating_in_qtl_aa_column, 'significant', ..replicating_in_qtl_fdr_column, ..replicating_in_qtl_pval_column, ..replicating_in_qtl_beta_column, ..replicating_in_qtl_se_column)]
    # rename the columns to not conflict
    colnames(replicating_in_qtl_chromosome) <- c('qtl', paste(replicating_in_name, c('zscore', 'assessed_allele', 'significant', 'fdr', 'p', 'beta', 'se'), sep = '_'))
  
    # put both in lists
    replicating_top_qtl[[paste0('chr', chromosome)]] <- replicating_qtl_chromosome_top
    replicating_in_qtl_matched[[paste0('chr', chromosome)]] <- replicating_in_qtl_chromosome
  }
  # merge all the lcl chromosomes
  replicating_top_qtl_all <- do.call('rbind', replicating_top_qtl)
  replicating_in_qtl_matched_all <- do.call('rbind', replicating_in_qtl_matched)

  # now merge the two tables
  qtl_both <- merge(x = replicating_top_qtl_all, y = replicating_in_qtl_matched_all, by = 'qtl')
  # get the z score of the replicating dataset
  replicating_z_signed <- qtl_both[[paste(replicating_in_name, 'zscore', sep = '_')]]
  replicating_beta_signed <- qtl_both[[paste(replicating_in_name, 'beta', sep = '_')]]
  # get whether the allele asses was different than in the replicating dataset
  replicating_allele_different <- qtl_both[[paste(replicating_name, 'assesed_allele', sep = '_')]] != qtl_both[[paste(replicating_in_name, 'assesed_allele', sep = '_')]]
  # flip direction of the score where the allele was different
  replicating_z_signed[replicating_allele_different] <- -1 * replicating_z_signed[replicating_allele_different]
  replicating_beta_signed[replicating_allele_different] <- -1 * replicating_beta_signed[replicating_allele_different]
  # and add that information back into the table
  qtl_both[[paste(replicating_in_name, 'zscore_signed', sep = '_')]] <- replicating_z_signed
  qtl_both[[paste(replicating_in_name, 'beta_signed', sep = '_')]] <- replicating_beta_signed

  return(qtl_both)
}


match_qtl_outputs_each <- function(qtl_folder, name='replicating', in_name='replicating_in', 
                              qtl_prepend='qtl_results_all_qval_', qtl_append='.txt.gz', qtl_pval_column='p_value', qtl_feature_column='feature_id', qtl_variant_column='snp_id', qtl_fdr_column='feature_q_value', qtl_beta_column='beta', qtl_se_column='beta_se', qtl_aa_column='assessed_allele', qtl_fdr_cutoff=0.05, nosplit=F, folders_to_use=NULL) {
  # store each combination
  folder_vs_folder_all <- list()
  # list of all of the cell types in the first folder
  folders_all <- list.dirs(qtl_folder, full.names = F, recursive = F)
  # filter if requested
  if (!is.null(folders_to_use)) {
    folders_all <- intersect(folders_all, folders_to_use)
  }
  # check each folder
  for (folder in folders_all) {
    # check against every other cell type
    for (folder2 in folders_all) {
      # print the progress
      message(paste('doing', folder, 'vs', folder2))
      # paste the folders together
      replicating_qtl_folder <- paste(qtl_folder, folder, sep = '/')
      replicating_in_qtl_folder <- paste(qtl_folder, folder2, sep = '/')
      # check overlaps
      folder_vs_folder <- match_qtl_outputs(replicating_qtl_folder, replicating_in_qtl_folder, replicating_name=folder, replicating_in_name=folder2, 
                              replicating_qtl_prepend=qtl_prepend, replicating_qtl_append=qtl_append, replicating_qtl_pval_column=qtl_pval_column, replicating_qtl_feature_column=qtl_feature_column, replicating_qtl_variant_column=qtl_variant_column, replicating_qtl_fdr_column=qtl_fdr_column, replicating_qtl_beta_column=qtl_beta_column, replicating_qtl_se_column=qtl_se_column, replicating_qtl_aa_column=qtl_aa_column, replicating_qtl_fdr_cutoff=qtl_fdr_cutoff, 
                              replicating_in_qtl_prepend=qtl_prepend, replicating_in_qtl_append=qtl_append, replicating_in_qtl_pval_column=qtl_pval_column, replicating_in_qtl_feature_column=qtl_feature_column, replicating_in_qtl_variant_column=qtl_variant_column, replicating_in_qtl_fdr_column=qtl_fdr_column, replicating_in_qtl_beta_column=qtl_beta_column, replicating_in_qtl_se_column=qtl_se_column, replicating_in_qtl_aa_column=qtl_aa_column, replicating_in_qtl_fdr_cutoff=qtl_fdr_cutoff, nosplit=nosplit)
      # add to the list
      folder_vs_folder_all[[paste(folder, folder2, sep = '_vs_')]] <- folder_vs_folder
    }
  }
  return(folder_vs_folder_all)
}


#' Function for Rb analysis
#'
#' @param b1 Beta from first dataset.
#' @param se1 Standard error of beta from first dataset.
#' @param b2 Beta from second dataset.
#' @param se2 Standard error of beta from second dataset.
#' @param theta Variable representing sample overlap between two datasets. Should be set 0 if no sample overlap.
#'
#' @return Data frame with Rb, SE(Rb) and corresponding P-value.
#' @export
#'
#' @note This function is slightly adapted from the script shared by Ting Qi.
#'
#' @examples
calcu_cor_true <- function(b1, se1, b2, se2, theta=1) {
  idx <- which(is.infinite(b1) | is.infinite(b2) | is.infinite(se1) | is.infinite(se2))
  if (length(idx) > 0) {
    b1 <- b1[-idx]
    se1 <- se1[-idx]
    b2 <- b2[-idx]
    se2 <- se2[-idx]
    theta <- theta[-idx]
  }

  var_b1 <- var(b1, na.rm = T) - mean(se1^2, na.rm = T)
  var_b2 <- var(b2, na.rm = T) - mean(se2^2, na.rm = T)
  if (var_b1 < 0) {
    var_b1 <- var(b1, na.rm = T)
  }
  if (var_b2 < 0) {
    var_b2 <- var(b2, na.rm = T)
  }
  cov_b1_b2 <- cov(b1, b2, use = "complete.obs") - mean(theta, na.rm = T) * sqrt(mean(se1^2, na.rm = T) * mean(se2^2, na.rm = T))
  r <- cov_b1_b2 / sqrt(var_b1 * var_b2)

  r_jack <- c()
  n <- length(b1)
  for (k in 1:n) {
    b1_jack <- b1[-k]
    se1_jack <- se1[-k]
    var_b1_jack <- var(b1_jack, na.rm = T) - mean(se1_jack^2, na.rm = T)
    b2_jack <- b2[-k]
    se2_jack <- se2[-k]
    var_b2_jack <- var(b2_jack, na.rm = T) - mean(se2_jack^2, na.rm = T)
    if (var_b1_jack < 0) {
      var_b1_jack <- var(b1_jack, na.rm = T)
    }
    if (var_b2_jack < 0) {
      var_b2_jack <- var(b2_jack, na.rm = T)
    }
    theta_jack <- theta[-k]
    cov_e1_jack_e2_jack <- mean(theta_jack, na.rm = T) * sqrt(mean(se1_jack^2, na.rm = T) * mean(se2_jack^2, na.rm = T))
    cov_b1_b2_jack <- cov(b1_jack, b2_jack, use = "complete.obs") - cov_e1_jack_e2_jack
    r_tmp <- cov_b1_b2_jack / sqrt(var_b1_jack * var_b2_jack)
    r_jack <- c(r_jack, r_tmp)
  }
  r_mean <- mean(r_jack, na.rm = T)
  idx <- which(is.na(r_jack))
  if (length(idx) > 0) {
    se_r <- sqrt((n - 1) / n * sum((r_jack[-idx] - r_mean)^2))
  } else {
    se_r <- sqrt((n - 1) / n * sum((r_jack - r_mean)^2))
  }

  p <- pchisq((r / se_r)**2, df = 1, lower.tail = FALSE)

  res <- cbind(r, se_r, p)
  return(res)
}


get_stats_qtl_matches <- function(table_per_match, name_split='_vs_', 
                                  significance_column_replicating_emperical='fdr', 
                                  significance_column_replicating_nominal='p',
                                  significance_column_replicating_in_emperical='fdr',
                                  significance_column_replicating_in_nominal='p',
                                  significance_cutoff_replicating_emperical=0.05, 
                                  significance_cutoff_replicating_nominal=0.05, 
                                  significance_cutoff_replicating_in_emperical=0.05, 
                                  significance_cutoff_replicating_in_nominal=0.05, 
                                  score_column_replicating='zscore', 
                                  score_column_replicating_in='zscore', 
                                  beta_column_replicating='beta', 
                                  beta_column_replicating_in='beta', 
                                  se_column_replicating='se', 
                                  se_column_replicating_in='se', 
                                  allele_column_replicating='assessed_allele', 
                                  allele_column_replicating_in='assessed_allele', 
                                  cor_method='spearman') {
  # prepare a list of tables of all the comparisons
  stats_per_combination <- list()
  # check each of the tables
  for (combination in names(table_per_match)) {
    print(combination)
    # extract the two names
    replicating_name <- strsplit(combination, name_split)[[1]][1]
    replicating_in_name <- strsplit(combination, name_split)[[1]][2]
    # extract the table
    replication_table <- table_per_match[[combination]]
    # init variables
    replicated_emperical_emperical_in_replicating <- NA
    nominal_to_nominal_zscore_correlation <- NA
    emperical_to_nominal_zscore_correlation <- NA
    emperical_to_emperical_zscore_correlation <- NA
    nominal_to_nominal_concordance <- NA
    emperical_to_nominal_concordance <- NA
    emperical_to_emperical_concordance <- NA
    nominal_to_nominal_rb <- NA
    emperical_to_nominal_rb <- NA
    emperical_to_all_rb <- NA
    emperical_to_emperical_rb <- NA
    # if they are the same, we don't have to do much
    if (replicating_name == replicating_in_name) {
      # we check how many are significant
      n_sig <- NULL
      if (isTRUE(significance_cutoff_replicating_emperical)) {
        n_sig <- nrow(replication_table[
          replication_table[[paste0(replicating_name, '_', significance_column_replicating_emperical, '.x')]] == T, ])
      } else {
        n_sig <- nrow(replication_table[
          replication_table[[paste0(replicating_name, '_', significance_column_replicating_emperical, '.x')]] < significance_cutoff_replicating_emperical, ])
      }
      # and then all of these will be the same
      replicated_emperical_emperical_in_replicating <- n_sig
      replicated_emperical_nominal_in_replicating <- n_sig
      replicated_emperical_tested_in_replicating <- n_sig
      replicated_emperical_nominal_in_replicating <- n_sig
      # these will all be one
      nominal_to_nominal_zscore_correlation <- 1
      emperical_to_nominal_zscore_correlation <- 1
      emperical_to_emperical_zscore_correlation <- 1
      nominal_to_nominal_concordance <- 1
      emperical_to_nominal_concordance <- 1
      emperical_to_emperical_concordance <- 1
      nominal_to_nominal_rb <- 1
      emperical_to_nominal_rb <- 1
      emperical_to_all_rb <- 1
      emperical_to_emperical_rb <- 1
    }
    else {
      # check how many significant in replicating, are present in the other
      replicated_emperical_tested_in_replicating <- NULL
      # using the boolean value in the column if it was a boolean
      if (isTRUE(significance_cutoff_replicating_emperical)) {
        replicated_emperical_tested_in_replicating <- nrow(replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] == T, ])
      } else {
        # otherwise use it as a cutoff
        replicated_emperical_tested_in_replicating <- nrow(replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] < significance_cutoff_replicating_emperical, ])
      }
      
      # subset to emperical only in where we are replicating
      replication_table_emp_to_all <- NULL
      # if the significance cutoff is a T/F we don't use it as a cutoff
      if (isTRUE(significance_cutoff_replicating_emperical)) {
        replication_table_emp_to_all <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] == T, 
        ]
      } else {
        replication_table_emp_to_all <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] < significance_cutoff_replicating_emperical, 
        ]
      }
      # and the beta
      beta_replicating_in <- replication_table_emp_to_all[[paste(replicating_in_name, beta_column_replicating_in, sep = '_')]]
      # check which have the same allelic direction
      alleles_differ_locs <- which(replication_table_emp_to_all[[paste(replicating_name, allele_column_replicating, sep = '_')]] != replication_table_emp_to_all[[paste(replicating_in_name, allele_column_replicating_in, sep = '_')]])
      # and flip direction of betas to reflect this
      beta_replicating_in[alleles_differ_locs] <- -1 * beta_replicating_in[alleles_differ_locs]
      # calculate Rb
     emp_to_all_rb_table <- calcu_cor_true(b1 = replication_table_emp_to_all[[paste(replicating_name, beta_column_replicating, sep = '_')]], se1 = replication_table_emp_to_all[[paste(replicating_name, se_column_replicating, sep = '_')]], b2 = beta_replicating_in, se2 = replication_table_emp_to_all[[paste(replicating_in_name, se_column_replicating_in, sep = '_')]])
      emperical_to_all_rb <- emp_to_all_rb_table[1, 'r']
      
      # subset to nominal in both
      replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_nominal, sep = '_')]] < significance_cutoff_replicating_nominal &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_nominal, sep = '_')]] < significance_cutoff_replicating_in_nominal, 
      ]
      # get the Z scores
      zscore_replicating <- replication_table[[paste(replicating_name, score_column_replicating, sep = '_')]]
      zscore_replicating_in <- replication_table[[paste(replicating_in_name, score_column_replicating_in, sep = '_')]]
      # and the beta
      beta_replicating_in <- replication_table[[paste(replicating_in_name, beta_column_replicating_in, sep = '_')]]
      # check which have the same allelic direction
      alleles_differ_locs <- which(replication_table[[paste(replicating_name, allele_column_replicating, sep = '_')]] != replication_table[[paste(replicating_in_name, allele_column_replicating_in, sep = '_')]])
      # and flip direction of z score and betas to reflect this
      zscore_replicating_in[alleles_differ_locs] <- -1 * zscore_replicating_in[alleles_differ_locs]
      beta_replicating_in[alleles_differ_locs] <- -1 * beta_replicating_in[alleles_differ_locs]
      # get the correlation of the two
      nominal_to_nominal_zscore_correlation <- cor(zscore_replicating, zscore_replicating_in, method = cor_method)
      # and concordance
      nominal_to_nominal_concordance <- sum(sign(zscore_replicating) == sign(zscore_replicating_in)) / length(zscore_replicating)
      # and the rb
      #nominal_to_nominal_rb <- 1 - mean(abs(((zscore_replicating_in - zscore_replicating) / zscore_replicating)))
      nominal_to_nominal_rb_table <- calcu_cor_true(b1 = replication_table[[paste(replicating_name, beta_column_replicating, sep = '_')]], se1 = replication_table[[paste(replicating_name, se_column_replicating, sep = '_')]], b2 = beta_replicating_in, se2 = replication_table[[paste(replicating_in_name, se_column_replicating_in, sep = '_')]])
      nominal_to_nominal_rb <- nominal_to_nominal_rb_table[1, 'r']
      
      # subset the replicating to emperical for replicating
      if (isTRUE(significance_cutoff_replicating_emperical)) {
        # if the cutoff is just a 'T' value, we use that as the filter
        replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] == T &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_nominal, sep = '_')]] < significance_cutoff_replicating_in_nominal, 
        ]
      } else {
        replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] < significance_cutoff_replicating_emperical &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_nominal, sep = '_')]] < significance_cutoff_replicating_in_nominal, 
        ]
      }
      
      # check how many significant in replicating, are nominally significant in the other
      replicated_emperical_nominal_in_replicating <- nrow(replication_table)
      # get the Z scores
      zscore_replicating <- replication_table[[paste(replicating_name, score_column_replicating, sep = '_')]]
      zscore_replicating_in <- replication_table[[paste(replicating_in_name, score_column_replicating_in, sep = '_')]]
      # and the beta
      beta_replicating_in <- replication_table[[paste(replicating_in_name, beta_column_replicating_in, sep = '_')]]
      # check which have the same allelic direction
      alleles_differ_locs <- which(replication_table[[paste(replicating_name, allele_column_replicating, sep = '_')]] != replication_table[[paste(replicating_in_name, allele_column_replicating_in, sep = '_')]])
      # and flip direction of z score to reflect this
      zscore_replicating_in[alleles_differ_locs] <- -1 * zscore_replicating_in[alleles_differ_locs]
      beta_replicating_in[alleles_differ_locs] <- -1 * beta_replicating_in[alleles_differ_locs]
      # get the correlation of the two
      emperical_to_nominal_zscore_correlation <- cor(zscore_replicating, zscore_replicating_in, method = cor_method)
      # and concordance
      emperical_to_nominal_concordance <- sum(sign(zscore_replicating) == sign(zscore_replicating_in)) / length(zscore_replicating)
      # and the rb
      #emperical_to_nominal_rb <- 1 - mean(abs(((zscore_replicating_in - zscore_replicating) / zscore_replicating)))
      emperical_to_nominal_rb_table <- calcu_cor_true(b1 = replication_table[[paste(replicating_name, beta_column_replicating, sep = '_')]], se1 = replication_table[[paste(replicating_name, se_column_replicating, sep = '_')]], b2 = beta_replicating_in, se2 = replication_table[[paste(replicating_in_name, se_column_replicating_in, sep = '_')]])
      emperical_to_nominal_rb <- emperical_to_nominal_rb_table[1, 'r']
      
      # subset the replicating to emperical for both
      if (isTRUE(significance_cutoff_replicating_emperical) & isTRUE(significance_cutoff_replicating_in_emperical)) {
        # subset both just on that T value
        replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] == T &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_emperical, sep = '_')]] == T, 
        ]
      }
      else if(isTRUE(significance_cutoff_replicating_emperical)) {
        # or only one
        replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] == T &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_emperical, sep = '_')]] < significance_cutoff_replicating_in_emperical, 
        ]
      }
      else if(isTRUE(significance_cutoff_replicating_in_emperical)) {
        # or the other
        replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] < significance_cutoff_replicating_emperical &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_emperical, sep = '_')]] == T, 
        ]
      }
      else {
        # or on actual values
        replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] < significance_cutoff_replicating_emperical &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_emperical, sep = '_')]] < significance_cutoff_replicating_in_emperical, 
        ]
      }
      
      # check how many significant in replicating, are also significant in the other
      replicated_emperical_emperical_in_replicating <- nrow(replication_table)
      # get the Z scores
      zscore_replicating <- replication_table[[paste(replicating_name, score_column_replicating, sep = '_')]]
      zscore_replicating_in <- replication_table[[paste(replicating_in_name, score_column_replicating_in, sep = '_')]]
      # and the beta
      beta_replicating_in <- replication_table[[paste(replicating_in_name, beta_column_replicating_in, sep = '_')]]
      # check which have the same allelic direction
      alleles_differ_locs <- which(replication_table[[paste(replicating_name, allele_column_replicating, sep = '_')]] != replication_table[[paste(replicating_in_name, allele_column_replicating_in, sep = '_')]])
      # and flip direction of z score to reflect this
      zscore_replicating_in[alleles_differ_locs] <- -1 * zscore_replicating_in[alleles_differ_locs]
      beta_replicating_in[alleles_differ_locs] <- -1 * beta_replicating_in[alleles_differ_locs]
      # get the correlation of the two
      emperical_to_emperical_zscore_correlation <- cor(zscore_replicating, zscore_replicating_in, method = cor_method)
      # and concordance
      emperical_to_emperical_concordance <- sum(sign(zscore_replicating) == sign(zscore_replicating_in)) / length(zscore_replicating)
      # and the rb
      #emperical_to_emperical_rb <- 1 - mean(abs(((zscore_replicating_in - zscore_replicating) / zscore_replicating)))
      emperical_to_emperical_rb_table <- calcu_cor_true(b1 = replication_table[[paste(replicating_name, beta_column_replicating, sep = '_')]], se1 = replication_table[[paste(replicating_name, se_column_replicating, sep = '_')]], b2 = beta_replicating_in, se2 = replication_table[[paste(replicating_in_name, se_column_replicating_in, sep = '_')]])
       emperical_to_emperical_rb <- emperical_to_emperical_rb_table[1, 'r']
      
    }
    # put it all in a table
      stats_combination <- data.frame(
        'replicating' = c(replicating_name), 
        'replicating_in' = c(replicating_in_name), 
        'n_sig_tested' = c(replicated_emperical_tested_in_replicating), 
        'n_sig_nom' = c(replicated_emperical_nominal_in_replicating), 
        'n_sig_both' = c(replicated_emperical_emperical_in_replicating), 
        'cor_nom_nom' = c(nominal_to_nominal_zscore_correlation), 
        'cor_emp_nom' = c(emperical_to_nominal_zscore_correlation), 
        'cor_emp_emp' = c(emperical_to_emperical_zscore_correlation), 
        'con_nom_nom' = c(nominal_to_nominal_concordance), 
        'con_emp_nom' = c(emperical_to_nominal_concordance), 
        'con_emp_emp' = c(emperical_to_emperical_concordance), 
        'rb_nom_nom' = c(nominal_to_nominal_rb), 
        'rb_emp_nom' = c(emperical_to_nominal_rb), 
        'rb_emp_emp' = c(emperical_to_emperical_rb), 
        'rb_emp_all' = c(emperical_to_all_rb))
      # put in the list
      stats_per_combination[[combination]] <- stats_combination
  }
  # merge all tables
  stats_combination_all <- do.call('rbind', stats_per_combination)
  return(stats_combination_all)
}


plot_replication_stats <- function(replication_stats, replicating_column='replicating', replicating_in_column='replicating_in', matching_value_to_text=list('n_sig_tested' = 'N sig:'), comparing_value_to_text=list('n_sig_both' = 'N sig both:', 'n_sig_tested' = 'N test both:', 'cor_emp_nom' = 'nom cor:'), colour_column='cor_emp_nom', angle_labels=F, use_label_dict=T, legendless=F, paper_style=T, round_decimals=2, low_color='blue', mid_color='white', high_color='red', mid_value=0, category_plot_order=NULL, text_size=6) {
  # round values if required
  if (!is.null(round_decimals)) {
    for (col in colnames(replication_stats)) {
      if (is.numeric(replication_stats[[col]])) {
        replication_stats[[col]] <- round(replication_stats[[col]], digits = round_decimals)
      }
    }
  }
  # check each row of this table
  replication_stats[['display_text']] <- apply(replication_stats, 1, FUN = function(x) {
    # get the replicating cell type
    replicating <- x[[replicating_column]]
    # and what we are replicating in
    replicating_in <- x[[replicating_in_column]]
    # create the text
    final_text <- NULL
    # check if they are the same
    if (replicating == replicating_in) {
      # then we use this list
      list_to_check <- matching_value_to_text
    }
    else {
      # otherwise we use the other list
      list_to_check <- comparing_value_to_text
    }
    # check each column in the matching list
    for (column_to_check in names(list_to_check)) {
      # make the new piece of text by getting the matching text, and the value from the table
      display_text_part <- paste0(list_to_check[[column_to_check]], as.character(x[[column_to_check]]))
      # check if we have any text
      if (is.null(final_text)) {
        final_text <- display_text_part
      }
      else {
        # if we have, paste together
        final_text <- paste(final_text, display_text_part, sep = '\n')
      }
    }
    return(final_text)
  })
  # remap names if requested
  if (use_label_dict) {
    replication_stats[[replicating_column]] <- remap_with_label_dict(replication_stats[[replicating_column]])
    replication_stats[[replicating_in_column]] <- remap_with_label_dict(replication_stats[[replicating_in_column]])
  }
  # order labels if requested
  if (!is.null(category_plot_order)) {
    # double check if we have the labels
    all_labels <- unique(c(replication_stats[[replicating_column]], replication_stats[[replicating_in_column]]))
    # check if there is any difference between what we have and the categories
    labels_missing <- setdiff(all_labels, category_plot_order)
    # and stop it there are
    if (length(labels_missing) > 0) {
      stop(paste('category_plot_order does not contain all values in categories, missing are:', paste(labels_missing, sep = ',')))
    }
    replication_stats[[replicating_column]] <- factor(replication_stats[[replicating_column]], levels = category_plot_order)
    replication_stats[[replicating_in_column]] <- factor(replication_stats[[replicating_in_column]], levels = category_plot_order)
  }
  # now make the plot (use the !! rlang::sym(variable_name) synthax to be able to use a variable for ggplot)
  p <- ggplot(data=replication_stats, aes(x=!! rlang::sym(replicating_column), y=!! rlang::sym(replicating_in_column), fill=!! rlang::sym(colour_column))) + geom_tile() + scale_fill_gradient2(low=low_color, mid = mid_color, high=high_color, midpoint = mid_value) + geom_text(aes(label=display_text), size = text_size)
  # some options
  if(legendless){
    p <- p + theme(legend.position = 'none')
  }
  if (paper_style) {
    p <- p + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white"))
  }
  if (angle_labels) {
    p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  }
  return(p)
}


read_pseudobulk_cre_output_per_celltype <- function(pseudobulk_output_folder, cell_types=NULL, filename_output='qtl_results_all.txt.gz', significance_column='empirical_feature_p_value', significance_cutoff=0.05, add_mtc=T, mtc_column='empirical_feature_p_value', feature_mtc_column='feature_id', mtc_column_to_add='feature_q_value', add_global_nominal_threshold=F, add_local_nominal_threshold=F, global_nominal_threshold_column_to_add='pval_nominal_threshold_global', local_nominal_threshold_column_to_add='pval_nominal_threshold_local', alpha_column='alpha_param', beta_column='beta_param', nominal_p_column='p_value', filter_alpha=T, alpha_min=.2, alpha_max=5, filter_significance=T) {
  # list all the files in the directory
  cell_type_folders <- list.dirs(pseudobulk_output_folder, full.names = F, recursive = F)
  # intersect the cell type folders with the cell types we are interested in
  if (!is.null(cell_types)) {
    cell_type_folders <- intersect(cell_type_folders, cell_types)
  }
  # save the results in a list
  output_per_celltype <- list()
  # now check each cell type
  for (cell_type in cell_type_folders) {
    # paste together the full file path
    cell_type_output_loc <- paste(pseudobulk_output_folder, cell_type, filename_output, sep = '/')
    # check if the file exists
    if (file.exists(cell_type_output_loc)) {
      # read this file
      cell_type_output <- fread(cell_type_output_loc, header = T, sep = '\t')
      # make sure there are no duplicates
      cell_type_output <- unique(cell_type_output)
      # filter on alpha if requested
      if (filter_alpha) {
        cell_type_output <- cell_type_output[!(cell_type_output[[alpha_column]] > alpha_max | cell_type_output[[alpha_column]] < alpha_min), ]
      }
      
      # get the features and the emperical p value
      if (add_mtc) {
        # subset to what we need
        cell_type_output_features <- NULL
        # which is a bit if we care about the nominal threshold
        if (add_global_nominal_threshold) {
          cell_type_output_features <- cell_type_output[, c(..feature_mtc_column, ..mtc_column, ..nominal_p_column, ..alpha_column, ..beta_column), with = F]
        }
        # even less if we don't try to get the nominal threshold as well
        else {
          cell_type_output_features <- cell_type_output[, c(..feature_mtc_column, ..mtc_column), with = F]
        }
        # remove the wherever we dont have our significance
        cell_type_output_features <- cell_type_output_features[!is.na(cell_type_output_features[[significance_column]]) & cell_type_output_features[[significance_column]] >= 0, ]
        # order by significance
        cell_type_output_features <- cell_type_output_features[order(cell_type_output_features[[mtc_column]]), ]
        # keep only the first entry
        cell_type_output_features[!duplicated(cell_type_output_features[[feature_mtc_column]]), ]
        # set the values that are larger than 1, to be 1, problem with precision
        cell_type_output_features[cell_type_output_features[[mtc_column]] > 1, mtc_column] <- 1
        # add multiple testing correction
        cell_type_output_features[['qvalue']] <- qvalue(cell_type_output_features[[mtc_column]])$qvalues
        # now add back to the original table
        cell_type_output[[mtc_column_to_add]] <- cell_type_output_features[match(cell_type_output[[feature_mtc_column]], cell_type_output_features[[feature_mtc_column]]), 'qvalue'][['qvalue']]
        # based on this MTC column, we can now also add a cuttoff
        if (add_local_nominal_threshold) {
          cell_type_output_local_threshold <- calculate_nominal_thresholds(cell_type_output_features, fdr=significance_cutoff, pval_col=nominal_p_column, nominal_threshold_column='nomthres', cutoff_column = 'qvalue', alpha_column = alpha_column, beta_column = beta_column)
          # now add the nominal threshold to the full table
          cell_type_output[[local_nominal_threshold_column_to_add]] <- cell_type_output_local_threshold[match(cell_type_output[[feature_mtc_column]], cell_type_output_local_threshold[[feature_mtc_column]]), 'nomthres'][['nomthres']]
        }
        if(add_global_nominal_threshold) {
          # filter the output to significant MTC hits
          cell_type_output_features_significant <- cell_type_output_features[cell_type_output_features[['qvalue']] < significance_cutoff, ]
          # and get the maximum significant nominal value
          global_p_cutoff <- max(cell_type_output_features_significant[[nominal_p_column]])
          # add that to the table
          cell_type_output[[global_nominal_threshold_column_to_add]] <- global_p_cutoff
        }
      }
      # filter the file if requested
      if (filter_significance) {
        cell_type_output <- cell_type_output[
          cell_type_output[[significance_column]] < significance_cutoff, 
        ]
      }
      # add the cell type
      cell_type_output[['cell_type']] <- cell_type
      # put in the list
      output_per_celltype[[cell_type]] <- cell_type_output
    }
    else {
      warning(paste('folder exists at', cell_type_output_loc, 'but no file is there'))
    }
  }
  return(output_per_celltype)
}


rename_labels <- function(vector_to_rename) {
  # get the labels that are present
  label_renaming <- get_label_dict()
  # now check which labels we are missing
  missing_renames <- setdiff(unique(vector_to_rename), names(label_renaming))
  # add those renames as not being renames
  for (missing_rename in missing_renames) {
    label_renaming[[missing_rename]] <- missing_rename
  }
  # now replace each value with the rename
  renamed_vector <- as.vector(unlist(label_renaming[vector_to_rename]))
  # and return that
  return(renamed_vector)
}


remap_with_label_dict <- function(vector_of_names) {
  # get the label dict
  relabels <- get_label_dict()
  # get the labels available for renaming
  labels_available <- names(relabels)
  # get the ones we cant remap
  unmappable <- setdiff(unique(vector_of_names), labels_available)
  # report on those
  if (length(unmappable) > 0) {
    print(paste('cannot remap the following names, they will be returned unchanged:', paste(unmappable, collapse = ',')))
    # and put those in our remapping list as their originals
    relabels[unmappable] <- unmappable
  }
  # now actually do the remapping
  remapped <- as.vector(unlist(relabels[vector_of_names]))
  return(remapped)
}




#' Plot Sharing of  Genes per Cell Type
#'
#' This function plots the sharing of differentially genes across cell types using an UpSet plot. It allows the use of custom label and color dictionaries.
#'
#' @param genes_per_ct list with the genes for each cell type
#' @param use_label_dict A logical value indicating whether to use a custom label dictionary for renaming cell types. Default is TRUE.
#' @param use_color_dict A logical value indicating whether to use a custom color dictionary for cell types. Default is TRUE.
#' @param n_intersects value describing how many intersections to plot, default is all
#' @param use_this_color_dict list with colours for each category, if not supplied, environment default is used
#' @return An UpSet plot showing the sharing of DE genes across cell types.
#'
plot_sharing_per_celltype <- function(genes_per_ct, use_label_dict=T, use_color_dict=T, n_intersects=NA, use_this_color_dict=NULL){
  # rename labels if requested
  if (use_label_dict) {
    names(genes_per_ct) <- remap_with_label_dict(names(genes_per_ct))
  }
  # get the total overlap
  total_overlap <- fromList(genes_per_ct)
  # count how many in each overlap
  combination_to_overlap <- list()
  apply(total_overlap, 1, function(x){
    # get which ones have a number
    positions_1 <- x > 0
    # get which these are, and paste together
    cols_1 <- paste(colnames(total_overlap)[positions_1], collapse = ',')
    # add to list if does not exist
    if (cols_1 %in% c(names(combination_to_overlap))) {
      combination_to_overlap[[cols_1]] <<- combination_to_overlap[[cols_1]] + 1
    }
    else{
      combination_to_overlap[[cols_1]] <<- 1
    }
  })
  # make into an ordered df
  combination_numbers <- data.frame('combination' = names(combination_to_overlap), 'nr' = as.vector(unlist(combination_to_overlap)))
  combination_numbers <- combination_numbers[order(combination_numbers[['nr']], combination_numbers[['combination']], decreasing = T), ]
  # get lowest number we have for the sets
  intersect_size_smallest <- 0
  if (is.na(n_intersects)) {
    intersect_size_smallest <- min(combination_numbers[['nr']])
  }
  else {
    intersect_size_smallest <- combination_numbers[n_intersects, 'nr']
  }
  # set queries and colours
  queries <- list()
  sets.bar.color <- 'black'
  if(use_color_dict){
    # create df to store the number of each set, so we know how to order
    nrs_df <- NULL
    # get the cell types we have
    cell_types <- names(genes_per_ct)
    # get colour codes for the cell types
    cell_type_colours <- NULL
    # use the supplied colour coding dict
    if (!is.null(use_this_color_dict)) {
      cell_type_colours <- use_this_color_dict
    }
    # otherwise the default one
    else {
      cell_type_colours <- get_color_coding_dict()
    }
    
    # also get colours for the cell types we don't have colours for
    cell_type_colours_missing <- roycols::get_color_list(setdiff(cell_types, names(cell_type_colours)))
    # and merge them
    cell_type_colours <- c(cell_type_colours, cell_type_colours_missing)
    # add the colors for the cell types
    i <- 1
    for(cell_type in cell_types){
      # check if there is a singleton for this cell type, so this celltype is 1, but the total of the row is also 1
      n_singletons <- nrow(total_overlap[total_overlap[[cell_type]] == 1 & rowSums(total_overlap) == 1, ])
      # if we have singletons, colour it
      if (n_singletons > 0 & n_singletons >= intersect_size_smallest) {
        # add for the singles in the intersection sizes
        ct_list <- list(
          query = intersects,
          params = list(cell_type),
          color = cell_type_colours[[cell_type]],
          active = T)
        queries[[i]] <- ct_list
        i <- i + 1
      }
      # add for the DF to order the set sizes
      numbers_row <- data.frame(ct=c(cell_type), nr=c(length(genes_per_ct[[cell_type]])), stringsAsFactors = F)
      if(is.null(nrs_df)){
        nrs_df <- numbers_row
      }
      else{
        nrs_df <- rbind(nrs_df, numbers_row)
      }
    }
    # get the order of the sets
    ordered_cts <- nrs_df[order(nrs_df$nr, decreasing = T), 'ct']
    # add the colors for the sets
    sets.bar.color <- unlist(cell_type_colours[ordered_cts])
    # make the plot
    upset(total_overlap, order.by = 'freq', nsets = length(genes_per_ct), queries = queries, sets.bar.color=sets.bar.color, nintersects = n_intersects)
  }
  else {
    upset(total_overlap, order.by = 'freq', nsets = length(genes_per_ct), nintersects = n_intersects)
  }
  
  #return(DE_genes_per_ct)
}


get_closest_flanks <- function(position_table, left_flank_column1, right_flank_column1, left_flank_column2, right_flank_column2) {
  # get the distance between left flanks
  dist_left_flank1_to_left_flank2 <- position_table[[left_flank_column1]] - position_table[[left_flank_column2]]
  # distance between the right flanks
  dist_right_flank1_to_right_flank2 <- position_table[[right_flank_column1]] - position_table[[right_flank_column2]]
  # distance between left flank 1 and right flank 2
  dist_left_flank1_to_right_flank2 <- position_table[[left_flank_column1]] - position_table[[right_flank_column2]]
  # distance between right flank 1 and left flank 2
  dist_right_flank1_to_left_flank2 <- position_table[[right_flank_column1]] - position_table[[left_flank_column2]]
  # put in a table for convenience sake
  distances_tbl <- data.table(
    'lf1_to_lf2' = dist_left_flank1_to_left_flank2, 
    'rf1_to_rf2' = dist_right_flank1_to_right_flank2, 
    'lf1_to_rf2' = dist_left_flank1_to_right_flank2, 
    'rf1_to_lf2' = dist_right_flank1_to_left_flank2
  )
  # add the minimum absolute distance
  distances_tbl[['min_dist']] <- apply(distances_tbl, 1, function(x) {
    return(min(abs(x)))
  })
  # but set this to zero if any of the flanks end in the bodies
  #              -----
  #                 ++++
  distances_tbl[(distances_tbl[['lf1_to_lf2']] < 0 & distances_tbl[['lf1_to_rf2']] > 0) |
                  #                   ----
                #                 ++++
                (distances_tbl[['rf1_to_lf2']] > 0 & distances_tbl[['lf1_to_rf2']] < 0) |
                  #                   ----
                #                 +++++++++
                (distances_tbl[['lf1_to_lf2']] > 0 & distances_tbl[['rf1_to_rf2']] < 0) |
                  #                 ---------
                #                   ++++
                (distances_tbl[['lf1_to_lf2']] < 0 & distances_tbl[['rf1_to_rf2']] > 0)
                , 'min_dist'] <- 0
  return(distances_tbl)
}


get_group_proportions <- function(named_list_of_dfs, column_to_get_proportions_from='screen', specific_trait_expression=NULL, specific_trait_name=NULL) {
  # we'll save per df
  results_per_group <- list()
  # we'll check each df
  for (group_name in names(named_list_of_dfs)) {
    # we'll need the numbers for the traits
    group_totals <- NULL
    # check a specific trait if requested
    if (!is.null(specific_trait_name) & !is.null(specific_trait_expression)) {
      # get true/false vector for that expression
      is_of_trait <- grepl(specific_trait_expression, named_list_of_dfs[[group_name]][[column_to_get_proportions_from]])
      # turn into a string
      is_trait_string <- ifelse (is_of_trait, paste('is', specific_trait_name), paste('is not', specific_trait_name))
      # make factor
      is_trait_factor <- factor(is_trait_string, levels = c(paste('is', specific_trait_name), paste('is not', specific_trait_name)))
      # get the totals from that
      group_totals <- data.frame(table(is_trait_string))
    }
    else {
      # otherwise get the totals of each group
      group_totals <- data.frame(table(named_list_of_dfs[[group_name]][[column_to_get_proportions_from]]))
    }
    # rename the columns
    colnames(group_totals) <- c('category', 'n')
    # add the fraction now as well
    group_totals[['frac']] <- group_totals[['n']] / sum(group_totals[['n']])
    # finally add the group as well
    group_totals[['group']] <- group_name
    # place in the list
    results_per_group[[group_name]] <- group_totals
  }
  # merge all the tables
  results_all <- do.call('rbind', results_per_group)
  # make sure the 'nots' are always last
  categories <- as.character(unique(results_all[['category']]))
  # get the ones that have 'not' in their name
  categories_not <- categories[grep('^is not ', categories)]
  # and the ones that are not not 'not'
  categories_other <- setdiff(categories, categories_not)
  # and make that the order
  results_all[['category']] <- factor(results_all[['category']], levels=(c(categories_not, categories_other)))
  results_all <- results_all[order(results_all[['category']]), ]
  return(results_all)
}



```

```{r path_setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

####################
# Main Code        #
####################

# location of eQTL
cre_output_combined_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/'

```

```{r cre_replication, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in caQTLs across cell types
cre_celltype_replication <- match_qtl_outputs_each(
  cre_output_combined_loc, 
  cre_output_combined_loc, 
  # qtl_prepend='qtl_results_all_frac01', qtl_append='.txt.gz', 
  qtl_prepend='qtl_results_annotated_all', qtl_append='.txt', 
  nosplit=T, 
  folders_to_use = c('B', 'CD4T', 'CD8T', 'DC', 'monocyte', 'NK'), 
  qtl_fdr_column = 'global_significance', 
  qtl_fdr_cutoff = T
)

```

```{r cre_replication_stats, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in caQTLs across cell types
cre_celltype_stats <- get_stats_qtl_matches(cre_celltype_replication, significance_cutoff_replicating_emperical = T, significance_cutoff_replicating_in_emperical = T)

```

```{r cre_replication_plot, include=TRUE, fig.width=12, fig.height=12}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in caQTLs across cell types
cre_celltype_stat_p <- plot_replication_stats(cre_celltype_stats, mid_value = 0.5, comparing_value_to_text=list('n_sig_both' = 'N sig both: ', 'n_sig_tested' = 'N test both: ', 'rb_emp_nom' = 'nom rep rb: '), colour_column = 'rb_emp_nom', category_plot_order = c('B', 'CD4+ T', 'CD8+ T', 'NK', 'DC', 'Monocyte'), text_size = 4) +
  xlab('Cell type replicating') +
  ylab('Cell type replicating in') +
  ggtitle('Replication of CRE-targetted genes across cell types') +
  labs(fill="Rb") +
  theme(
    # X label font size
    axis.title.x = element_text(size = 20), 
    # Y label font size
    axis.title.y = element_text(size = 20), 
    # X tick font size
    axis.text.x = element_text(size = 16), 
    # Y tick font size
    axis.text.y = element_text(size = 16), 
    # title size
    title = element_text(size = 24)
  )

# save the figure
ggsave('~/plots/mo_sccre_celltype_replication.pdf', plot = cre_celltype_stat_p, width = 12, height = 12)

# display the figure
cre_celltype_stat_p

```

```{r cre_replication_plot, include=TRUE, fig.width=12, fig.height=12}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in caQTLs across cell types
cre_celltype_stat_p <- plot_replication_stats(cre_celltype_stats, mid_value = 0.5, comparing_value_to_text=list('n_sig_both' = 'N sig both: ', 'n_sig_tested' = 'N test both: ', 'rb_emp_all' = 'rb: '), colour_column = 'rb_emp_all', category_plot_order = c('B', 'CD4+ T', 'CD8+ T', 'NK', 'DC', 'Monocyte'), text_size = 4) +
  xlab('Cell type replicating') +
  ylab('Cell type replicating in') +
  ggtitle('Replication of CRE-targetted genes across cell types') +
  labs(fill="Rb") +
  theme(
    # X label font size
    axis.title.x = element_text(size = 20), 
    # Y label font size
    axis.title.y = element_text(size = 20), 
    # X tick font size
    axis.text.x = element_text(size = 16), 
    # Y tick font size
    axis.text.y = element_text(size = 16), 
    # title size
    title = element_text(size = 24)
  )

# save the figure
ggsave('~/plots/mo_sccre_celltype_replication.pdf', plot = cre_celltype_stat_p, width = 12, height = 12)

# display the figure
cre_celltype_stat_p

```

```{r cre_replication_plot_con, include=TRUE, fig.width=12, fig.height=12}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in caQTLs across cell types
cre_celltype_stat_p_cor <- plot_replication_stats(cre_celltype_stats, mid_value = 0.5, comparing_value_to_text=list('n_sig_both' = 'N sig both: ', 'n_sig_tested' = 'N test both: ', 'cor_emp_nom' = 'nom rep cor: '), colour_column = 'cor_emp_nom', category_plot_order = c('B', 'CD4+ T', 'CD8+ T', 'NK', 'DC', 'Monocyte'), text_size = 4) +
  xlab('Cell type replicating') +
  ylab('Cell type replicating in') +
  ggtitle('Replication of CREs across cell types') +
  labs(fill="Rho") +
  theme(
    # X label font size
    axis.title.x = element_text(size = 20), 
    # Y label font size
    axis.title.y = element_text(size = 20), 
    # X tick font size
    axis.text.x = element_text(size = 16), 
    # Y tick font size
    axis.text.y = element_text(size = 16), 
    # title size
    title = element_text(size = 24)
  )

# save the figure
ggsave('~/plots/mo_sccre_celltype_replication_cor.pdf', plot = cre_celltype_stat_p_cor, width = 12, height = 12)

# display the figure
cre_celltype_stat_p_cor

```

```{r cre_replication_plot_con, include=TRUE, fig.width=12, fig.height=12}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in caQTLs across cell types
cre_celltype_stat_p_con <- plot_replication_stats(cre_celltype_stats, mid_value = 0.5, comparing_value_to_text=list('n_sig_both' = 'N sig both: ', 'n_sig_tested' = 'N test both: ', 'con_emp_nom' = 'nom rep con: '), colour_column = 'con_emp_nom', category_plot_order = c('B', 'CD4+ T', 'CD8+ T', 'NK', 'DC', 'Monocyte'), text_size = 4) +
  xlab('Cell type replicating') +
  ylab('Cell type replicating in') +
  ggtitle('Replication of CREs across cell types') +
  labs(fill="concordance") +
  theme(
    # X label font size
    axis.title.x = element_text(size = 20), 
    # Y label font size
    axis.title.y = element_text(size = 20), 
    # X tick font size
    axis.text.x = element_text(size = 16), 
    # Y tick font size
    axis.text.y = element_text(size = 16), 
    # title size
    title = element_text(size = 24)
  )

# save the figure
ggsave('~/plots/mo_sccre_celltype_replication_con.pdf', plot = cre_celltype_stat_p_con, width = 12, height = 12)

# display the figure
cre_celltype_stat_p_con

```

```{r cre_replication_plot_con, include=TRUE, fig.width=12, fig.height=12}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in caQTLs across cell types
cre_celltype_stat_p_cor <- plot_replication_stats(cre_celltype_stats, mid_value = 0.5, comparing_value_to_text=list('n_sig_both' = 'N sig both: ', 'n_sig_tested' = 'N test both: ', 'cor_emp_nom' = 'nom rep cor: '), colour_column = 'cor_emp_nom', category_plot_order = c('B', 'CD4+ T', 'CD8+ T', 'NK', 'DC', 'Monocyte'), text_size = 4) +
  xlab('Cell type replicating') +
  ylab('Cell type replicating in') +
  ggtitle('Replication of CREs across cell types') +
  labs(fill="Rho") +
  theme(
    # X label font size
    axis.title.x = element_text(size = 20), 
    # Y label font size
    axis.title.y = element_text(size = 20), 
    # X tick font size
    axis.text.x = element_text(size = 16), 
    # Y tick font size
    axis.text.y = element_text(size = 16), 
    # title size
    title = element_text(size = 24)
  )

# save the figure
ggsave('~/plots/mo_sccre_celltype_replication_cor.pdf', plot = cre_celltype_stat_p_cor, width = 12, height = 12)

# display the figure
cre_celltype_stat_p_cor

```

```{r tables_hybrid, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# read the cpeaks annotation
cpeaks_anno_loc <- '/groups/umcg-franke-scrna/tmp04/external_datasets/cPeaks/cPeaks_wscreenv4.tsv.gz'
cpeaks_anno <- fread(cpeaks_anno_loc, header = T, sep = '\t')
# add the Signac style name
cpeaks_anno[['signac_hg38']] <- paste(cpeaks_anno[['chr_hg38']], cpeaks_anno[['start_hg38']], cpeaks_anno[['end_hg38']], sep = '-')
# as well as the SCENIC+ style name
cpeaks_anno[['scenic_hg38']] <- paste0(cpeaks_anno[['chr_hg38']], ':', cpeaks_anno[['start_hg38']], '-', cpeaks_anno[['end_hg38']])
# location of the hybrid method
hybrid_output_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/'
# read hybrid method
# hybrid_output_list <- read_pseudobulk_cre_output_per_celltype(hybrid_output_loc, add_mtc = F, filter_alpha = F, add_global_nominal_threshold = F, add_local_nominal_threshold = F, filename_output = 'qtl_results_all_frac01.txt.gz', alpha_min = .2, alpha_max = 5, cell_types = c('B', 'CD4T', 'CD8T', 'DC', 'monocyte', 'NK'))
hybrid_output_list <- read_pseudobulk_cre_output_per_celltype(hybrid_output_loc, add_mtc = F, filter_alpha = F, add_global_nominal_threshold = F, add_local_nominal_threshold = F, filename_output = 'qtl_results_annotated_all.txt', alpha_min = .2, alpha_max = 5, cell_types = c('B', 'CD4T', 'CD8T', 'DC', 'monocyte', 'NK'))
# merge them
hybrid_output <- do.call('rbind', hybrid_output_list)
# add z score
hybrid_output[['zscore']] <- hybrid_output[['beta']] / hybrid_output[['beta_se']]
# add a correlation based on the Z score, taking sample size and removing 2 + 10 PCs to get the degrees of freedom
hybrid_output[['r']] <- hybrid_output[['zscore']] / sqrt(hybrid_output[['zscore']]^2 + (hybrid_output[['n_samples']][1] - 12))
# add a p based z
hybrid_output[['z_from_p']] <- qnorm(hybrid_output[['p_value']] / 2) * -1 * sign(hybrid_output[['beta']])
# and add the distances
hybrid_output <- cbind(hybrid_output, cpeaks_anno[match(hybrid_output[['snp_id']], cpeaks_anno[['signac_hg38']]), c('chr_hg38', 'start_hg38', 'end_hg38')])
hybrid_distances <- get_closest_flanks(hybrid_output, 'start_hg38', 'end_hg38', 'feature_start', 'feature_end')
hybrid_output[['distance']] <- hybrid_distances[['min_dist']]
hybrid_output[['category']] <- 'hybrid'
hybrid_output[['screen']] <- cpeaks_anno[match(hybrid_output[['snp_id']], cpeaks_anno[['signac_hg38']]), ][['screen_all']]


```

```{r lists_hybrid, include=TRUE, fig.with=10, fig.height=6}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# make a list with each QTL
cres_to_genes_per_celltype <- list()
cres_per_celltype <- list()
genes_per_celltype <- list()
# check each table
for (ct in unique(hybrid_output[['cell_type']])) {
  # extract that set
  cres_celltype <- hybrid_output[hybrid_output[['cell_type']] == ct, ]
  # subset to what is significant
  cres_celltype_sig <- cres_celltype[
    # cres_celltype[['feature_q_value']] < 0.05 &
    # cres_celltype[['p_value']] <= cres_celltype[['pval_nominal_threshold_global']] & 
    cres_celltype[['global_significance']] == T &
    cres_celltype[['distance']] > 0, 
  ]
  # get the qtls from that
  cres_to_genes_per_celltype[[ct]] <- paste(cres_celltype_sig[['snp_id']], cres_celltype_sig[['feature_id']])
  cres_per_celltype[[ct]] <- cres_celltype_sig[['snp_id']]
  genes_per_celltype[[ct]] <-cres_celltype_sig[['feature_id']]
}
# plot the overlap
plot_sharing_per_celltype(cres_to_genes_per_celltype)
grid.text("Overlap of CRE-gene pairs across cell types", x = 0.65, y = 0.95, gp = gpar(fontsize = 20))
plot_sharing_per_celltype(cres_per_celltype)
grid.text("Overlap of CREs across cell types", x = 0.65, y = 0.95, gp = gpar(fontsize = 20))
plot_sharing_per_celltype(genes_per_celltype)
grid.text("Overlap of CRE-targetted genes across cell types", x = 0.65, y = 0.95, gp = gpar(fontsize = 20))

```

```{r distances_celltypes, include=TRUE, fig.with=6, fig.height=6}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# make plot of distances, excluding overlapping region and gene combinations
p_region_direction_distances <- ggplot(
  data = hybrid_output[hybrid_output[['distance']] > 0, ], 
  mapping = aes(
    x = distance, 
    fill = cell_type
  )
) + 
  labs(fill="Cell type") +
  geom_density(alpha = 0.5) +
  xlab('Distance between region and gene') + 
  ylab('Density') + 
  ggtitle('Distance between region and gene\nacross cell types') + 
  scale_fill_manual(values = get_color_coding_dict()) + 
  theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white"))

# show the plot
p_region_direction_distances

```
```{r screen_annotations, include=TRUE, fig.with=10, fig.height=10}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# split the output back into the list
for (cell_type in unique(hybrid_output[['cell_type']])) {
  # and put that in the list
  hybrid_output_list[[cell_type]] <- hybrid_output[!is.na(hybrid_output[['cell_type']]) & hybrid_output[['cell_type']] == cell_type, ]
}

# the the relative proportions
fracs_screen_is_ca <- get_group_proportions(hybrid_output_list, specific_trait_expression = 'CA', specific_trait_name = 'CA')
fracs_screen_is_tf <- get_group_proportions(hybrid_output_list, specific_trait_expression = 'TF', specific_trait_name = 'TF')
fracs_screen_is_ctcf <- get_group_proportions(hybrid_output_list, specific_trait_expression = 'CTCF', specific_trait_name = 'CTCF')
fracs_screen_is_pls <- get_group_proportions(hybrid_output_list, specific_trait_expression = 'PLS', specific_trait_name = 'PLS')
fracs_screen_is_els <- get_group_proportions(hybrid_output_list, specific_trait_expression = 'ELS', specific_trait_name = 'ELS')
fracs_screen_is_pels <- get_group_proportions(hybrid_output_list, specific_trait_expression = 'pELS', specific_trait_name = 'pELS')
fracs_screen_is_dels <- get_group_proportions(hybrid_output_list, specific_trait_expression = 'dELS', specific_trait_name = 'dELS')

# and plot them
p_screen_fractions_ca <- ggplot(data = fracs_screen_is_ca, mapping = aes(x = group, y = frac, fill = category)) + 
  geom_bar(stat = 'identity', position = 'stack') +
  xlab('Cell type') +
  ylab('fraction of CA screen regions') +
  ggtitle('CA screen regions') +
  theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) +
  scale_fill_manual(values = roycols::get_color_list(c('is CA', 'is not CA')))
p_screen_fractions_tf <- ggplot(data = fracs_screen_is_tf, mapping = aes(x = group, y = frac, fill = category)) + 
  geom_bar(stat = 'identity', position = 'stack') +
  xlab('Cell type') +
  ylab('fraction of TF screen regions') +
  ggtitle('TF screen regions') +
  theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) +
  scale_fill_manual(values = roycols::get_color_list(c('is TF', 'is not TF')))
p_screen_fractions_ctcf <- ggplot(data = fracs_screen_is_ctcf, mapping = aes(x = group, y = frac, fill = category)) + 
  geom_bar(stat = 'identity', position = 'stack') +
  xlab('Cell type') +
  ylab('fraction of CTCF screen regions') +
  ggtitle('CTCF screen regions') +
  theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) +
  scale_fill_manual(values = roycols::get_color_list(c('is CTCF', 'is not CTCF')))
p_screen_fractions_ctcf <- ggplot(data = fracs_screen_is_ctcf, mapping = aes(x = group, y = frac, fill = category)) + 
  geom_bar(stat = 'identity', position = 'stack') +
  xlab('Cell type') +
  ylab('fraction of CTCF screen regions') +
  ggtitle('CTCF screen regions') +
  theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) +
  scale_fill_manual(values = roycols::get_color_list(c('is CTCF', 'is not CTCF')))
p_screen_fractions_pls <- ggplot(data = fracs_screen_is_pls, mapping = aes(x = group, y = frac, fill = category)) + 
  geom_bar(stat = 'identity', position = 'stack') +
  xlab('Cell type') +
  ylab('fraction of PLS screen regions') +
  ggtitle('PLS screen regions') +
  theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) +
  scale_fill_manual(values = roycols::get_color_list(c('is PLS', 'is not PLS')))
p_screen_fractions_els <- ggplot(data = fracs_screen_is_els, mapping = aes(x = group, y = frac, fill = category)) + 
  geom_bar(stat = 'identity', position = 'stack') +
  xlab('Cell type') +
  ylab('fraction of ELS screen regions') +
  ggtitle('ELS screen regions') +
  theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) +
  scale_fill_manual(values = roycols::get_color_list(c('is ELS', 'is not ELS')))
p_screen_fractions_pels <- ggplot(data = fracs_screen_is_pels, mapping = aes(x = group, y = frac, fill = category)) + 
  geom_bar(stat = 'identity', position = 'stack') +
  xlab('Cell type') +
  ylab('fraction of pELS screen regions') +
  ggtitle('pELS screen regions') +
  theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) +
  scale_fill_manual(values = roycols::get_color_list(c('is pELS', 'is not pELS')))
p_screen_fractions_dels <- ggplot(data = fracs_screen_is_dels, mapping = aes(x = group, y = frac, fill = category)) + 
  geom_bar(stat = 'identity', position = 'stack') +
  xlab('Cell type') +
  ylab('fraction of dELS screen regions') +
  ggtitle('dELS screen regions') +
  theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) +
  scale_fill_manual(values = roycols::get_color_list(c('is dELS', 'is not dELS')))

# show in one plot
plot_grid(
  p_screen_fractions_ca, 
  p_screen_fractions_tf, 
  p_screen_fractions_ctcf, 
  p_screen_fractions_pls, 
  p_screen_fractions_els, 
  p_screen_fractions_pels, 
  p_screen_fractions_dels, 
  nrow = 3, 
  ncol = 3
)

```

```{r subsampling_replication, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# do a replication of the subsamplings of CD8T
subsampling_replication_cd8t <- list()
# full vs everything
subsampling_replication_cd8t[['full_vs_full']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='full', replicating_in_name='full'
)
subsampling_replication_cd8t[['full_vs_sampling1']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='full', replicating_in_name='sampling1'
)
subsampling_replication_cd8t[['full_vs_sampling2']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='full', replicating_in_name='sampling2'
)
subsampling_replication_cd8t[['full_vs_sampling3']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='full', replicating_in_name='sampling3'
)
subsampling_replication_cd8t[['full_vs_sampling4']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='full', replicating_in_name='sampling4'
)
# sampling1 vs everything
subsampling_replication_cd8t[['sampling1_vs_full']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling1', replicating_in_name='full'
)
subsampling_replication_cd8t[['sampling1_vs_sampling1']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling1', replicating_in_name='sampling1'
)
subsampling_replication_cd8t[['sampling1_vs_sampling2']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling1', replicating_in_name='sampling2'
)
subsampling_replication_cd8t[['sampling1_vs_sampling3']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling1', replicating_in_name='sampling3'
)
subsampling_replication_cd8t[['sampling1_vs_sampling4']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling1', replicating_in_name='sampling4'
)
# sampling2 vs everything
subsampling_replication_cd8t[['sampling2_vs_full']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling2', replicating_in_name='full'
)
subsampling_replication_cd8t[['sampling2_vs_sampling1']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling2', replicating_in_name='sampling1'
)
subsampling_replication_cd8t[['sampling2_vs_sampling2']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling2', replicating_in_name='sampling2'
)
subsampling_replication_cd8t[['sampling2_vs_sampling3']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling2', replicating_in_name='sampling3'
)
subsampling_replication_cd8t[['sampling2_vs_sampling4']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling2', replicating_in_name='sampling4'
)
# sampling 3 vs everything
subsampling_replication_cd8t[['sampling3_vs_full']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling3', replicating_in_name='full'
)
subsampling_replication_cd8t[['sampling3_vs_sampling1']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling3', replicating_in_name='sampling1'
)
subsampling_replication_cd8t[['sampling3_vs_sampling2']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling3', replicating_in_name='sampling2'
)
subsampling_replication_cd8t[['sampling3_vs_sampling3']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling3', replicating_in_name='sampling3'
)
subsampling_replication_cd8t[['sampling3_vs_sampling4']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling3', replicating_in_name='sampling4'
)
# sampling 4 vs everything
subsampling_replication_cd8t[['sampling4_vs_full']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling4', replicating_in_name='full'
)
subsampling_replication_cd8t[['sampling4_vs_sampling1']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling4', replicating_in_name='sampling1'
)
subsampling_replication_cd8t[['sampling4_vs_sampling2']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling4', replicating_in_name='sampling2'
)
subsampling_replication_cd8t[['sampling4_vs_sampling3']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling4', replicating_in_name='sampling3'
)
subsampling_replication_cd8t[['sampling4_vs_sampling4']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all', 
  replicating_in_qtl_prepend ='qtl_results_all', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling4', replicating_in_name='sampling4'
)

```

```{r sampling_replication_stats, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in CREs across samplings
subsampling_replication_stats <- get_stats_qtl_matches(subsampling_replication_cd8t, 
                                  significance_column_replicating_emperical='fdr', 
                                  significance_column_replicating_nominal='p',
                                  significance_column_replicating_in_emperical='fdr',
                                  significance_column_replicating_in_nominal='p',
                                  significance_cutoff_replicating_emperical=0.05, 
                                  significance_cutoff_replicating_nominal=0.05, 
                                  significance_cutoff_replicating_in_emperical=0.05, 
                                  significance_cutoff_replicating_in_nominal=0.05, 
                                  score_column_replicating='zscore', 
                                  score_column_replicating_in='zscore', 
                                  beta_column_replicating='beta', 
                                  beta_column_replicating_in='beta', 
                                  se_column_replicating='se', 
                                  se_column_replicating_in='se', 
                                  allele_column_replicating='assessed_allele', 
                                  allele_column_replicating_in='assessed_allele', 
                                  cor_method='spearman')

```

```{r sampling_replication_plot, include=TRUE, fig.width=12, fig.height=12}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in caQTLs across cell types
subsampling_stat_p <- plot_replication_stats(subsampling_replication_stats, mid_value = 0.5, comparing_value_to_text=list('n_sig_both' = 'N sig both: ', 'n_sig_tested' = 'N test both: ', 'rb_emp_nom' = 'nom rep rb: '), colour_column = 'rb_emp_nom', category_plot_order = c('full', 'sampling1', 'sampling2', 'sampling3', 'sampling4'), text_size = 4) +
  xlab('Set replicating') +
  ylab('Set replicating in') +
  ggtitle('Replication of CD8+ T\nCREs across samplings') +
  labs(fill="Rb") +
  theme(
    # X label font size
    axis.title.x = element_text(size = 20), 
    # Y label font size
    axis.title.y = element_text(size = 20), 
    # X tick font size
    axis.text.x = element_text(size = 16), 
    # Y tick font size
    axis.text.y = element_text(size = 16), 
    # title size
    title = element_text(size = 24)
  )

# save the figure
ggsave('~/plots/mo_sccre_sampling_replication.pdf', plot = subsampling_stat_p, width = 12, height = 12)

# display the figure
subsampling_stat_p

```

```{r subsampling_replication_filtered, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# do a replication of the subsamplings of CD8T
subsampling_replication_cd8t_filtered <- list()
# full vs everything
subsampling_replication_cd8t_filtered[['full_vs_full']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='full', replicating_in_name='full'
)
subsampling_replication_cd8t_filtered[['full_vs_sampling1']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='full', replicating_in_name='sampling1'
)
subsampling_replication_cd8t_filtered[['full_vs_sampling2']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='full', replicating_in_name='sampling2'
)
subsampling_replication_cd8t_filtered[['full_vs_sampling3']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='full', replicating_in_name='sampling3'
)
subsampling_replication_cd8t_filtered[['full_vs_sampling4']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='full', replicating_in_name='sampling4'
)
# sampling1 vs everything
subsampling_replication_cd8t_filtered[['sampling1_vs_full']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling1', replicating_in_name='full'
)
subsampling_replication_cd8t_filtered[['sampling1_vs_sampling1']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling1', replicating_in_name='sampling1'
)
subsampling_replication_cd8t_filtered[['sampling1_vs_sampling2']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling1', replicating_in_name='sampling2'
)
subsampling_replication_cd8t_filtered[['sampling1_vs_sampling3']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling1', replicating_in_name='sampling3'
)
subsampling_replication_cd8t_filtered[['sampling1_vs_sampling4']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling1', replicating_in_name='sampling4'
)
# sampling2 vs everything
subsampling_replication_cd8t_filtered[['sampling2_vs_full']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling2', replicating_in_name='full'
)
subsampling_replication_cd8t_filtered[['sampling2_vs_sampling1']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling2', replicating_in_name='sampling1'
)
subsampling_replication_cd8t_filtered[['sampling2_vs_sampling2']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling2', replicating_in_name='sampling2'
)
subsampling_replication_cd8t_filtered[['sampling2_vs_sampling3']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling2', replicating_in_name='sampling3'
)
subsampling_replication_cd8t_filtered[['sampling2_vs_sampling4']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling2', replicating_in_name='sampling4'
)
# sampling 3 vs everything
subsampling_replication_cd8t_filtered[['sampling3_vs_full']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling3', replicating_in_name='full'
)
subsampling_replication_cd8t_filtered[['sampling3_vs_sampling1']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling3', replicating_in_name='sampling1'
)
subsampling_replication_cd8t_filtered[['sampling3_vs_sampling2']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling3', replicating_in_name='sampling2'
)
subsampling_replication_cd8t_filtered[['sampling3_vs_sampling3']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling3', replicating_in_name='sampling3'
)
subsampling_replication_cd8t_filtered[['sampling3_vs_sampling4']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling3', replicating_in_name='sampling4'
)
# sampling 4 vs everything
subsampling_replication_cd8t_filtered[['sampling4_vs_full']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/',
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling4', replicating_in_name='full'
)
subsampling_replication_cd8t_filtered[['sampling4_vs_sampling1']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling4', replicating_in_name='sampling1'
)
subsampling_replication_cd8t_filtered[['sampling4_vs_sampling2']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling4', replicating_in_name='sampling2'
)
subsampling_replication_cd8t_filtered[['sampling4_vs_sampling3']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling3/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling4', replicating_in_name='sampling3'
)
subsampling_replication_cd8t_filtered[['sampling4_vs_sampling4']] <- match_qtl_outputs(
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling4/L1/CD8T/', 
  replicating_qtl_prepend='qtl_results_all_frac01', 
  replicating_in_qtl_prepend ='qtl_results_all_frac01', 
  replicating_qtl_append='.txt.gz', 
  replicating_in_qtl_append='.txt.gz', 
  nosplit=T, 
  replicating_name='sampling4', replicating_in_name='sampling4'
)

```

```{r sampling_replication_stats, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in CREs across samplings
subsampling_replication_stats_filtered <- get_stats_qtl_matches(subsampling_replication_cd8t_filtered, 
                                  significance_column_replicating_emperical='fdr', 
                                  significance_column_replicating_nominal='p',
                                  significance_column_replicating_in_emperical='fdr',
                                  significance_column_replicating_in_nominal='p',
                                  significance_cutoff_replicating_emperical=0.05, 
                                  significance_cutoff_replicating_nominal=0.05, 
                                  significance_cutoff_replicating_in_emperical=0.05, 
                                  significance_cutoff_replicating_in_nominal=0.05, 
                                  score_column_replicating='zscore', 
                                  score_column_replicating_in='zscore', 
                                  beta_column_replicating='beta', 
                                  beta_column_replicating_in='beta', 
                                  se_column_replicating='se', 
                                  se_column_replicating_in='se', 
                                  allele_column_replicating='assessed_allele', 
                                  allele_column_replicating_in='assessed_allele', 
                                  cor_method='spearman')

```

```{r sampling_replication_plot, include=TRUE, fig.width=12, fig.height=12}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in caQTLs across cell types
subsampling_stat_p_filtered <- plot_replication_stats(subsampling_replication_stats_filtered, mid_value = 0.5, comparing_value_to_text=list('n_sig_both' = 'N sig both: ', 'n_sig_tested' = 'N test both: ', 'rb_emp_nom' = 'nom rep rb: '), colour_column = 'rb_emp_nom', category_plot_order = c('full', 'sampling1', 'sampling2', 'sampling3', 'sampling4'), text_size = 4) +
  xlab('Set replicating') +
  ylab('Set replicating in') +
  ggtitle('Replication of CD8+ T\nCREs across samplings (% expressed >= 10)') +
  labs(fill="Rb") +
  theme(
    # X label font size
    axis.title.x = element_text(size = 20), 
    # Y label font size
    axis.title.y = element_text(size = 20), 
    # X tick font size
    axis.text.x = element_text(size = 16), 
    # Y tick font size
    axis.text.y = element_text(size = 16), 
    # title size
    title = element_text(size = 24)
  )

# save the figure
ggsave('~/plots/mo_sccre_sampling_replication_filtered.pdf', plot = subsampling_stat_p_filtered, width = 12, height = 12)

# display the figure
subsampling_stat_p_filtered

```

```{r sampling_overlap_plot, include=TRUE, fig.width=8, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

plot_sharing_per_celltype(
  list(
    'full' = unique(subsampling_replication_cd8t[['full_vs_full']][subsampling_replication_cd8t[['full_vs_full']][['full_significant.x']] == T, ][['qtl']]), 
    'sampling1' = unique(subsampling_replication_cd8t[['sampling1_vs_sampling1']][subsampling_replication_cd8t[['sampling1_vs_sampling1']][['sampling1_significant.x']] == T, ][['qtl']]), 
    'sampling2' = unique(subsampling_replication_cd8t[['sampling2_vs_sampling2']][subsampling_replication_cd8t[['sampling2_vs_sampling2']][['sampling2_significant.x']] == T, ][['qtl']])
  )
)
grid.text('CRE-gene pair overlaps in\nCD8+ T samplings', x = 0.8, y = 0.85, gp = gpar(fontsize = 16))

```

```{r sampling_overlap_plot_string, include=TRUE, fig.width=8, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

plot_sharing_per_celltype(
  list(
    'full' = unique(subsampling_replication_cd8t[['full_vs_full']][subsampling_replication_cd8t[['full_vs_full']][['full_fdr.x']] < 0.01, ][['qtl']]), 
    'sampling1' = unique(subsampling_replication_cd8t[['sampling1_vs_sampling1']][subsampling_replication_cd8t[['sampling1_vs_sampling1']][['sampling1_fdr.x']] < 0.01, ][['qtl']]), 
    'sampling2' = unique(subsampling_replication_cd8t[['sampling2_vs_sampling2']][subsampling_replication_cd8t[['sampling2_vs_sampling2']][['sampling2_fdr.x']] < 0.01, ][['qtl']])
  )
)
grid.text('CRE-gene pair overlaps in\nCD8+ T samplings (fdr < 0.01)', x = 0.8, y = 0.85, gp = gpar(fontsize = 16))

```

```{r sampling_overlap_plot_scatter, include=TRUE, fig.width=8, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

p_scatter_sampling <- ggplot(data = subsampling_replication_cd8t[['sampling1_vs_sampling2']], mapping = aes(x = sampling1_beta, y = sampling2_beta)) +
  geom_point() + 
  xlab('beta in sampling 1') +
  ylab('beta in sampling 2') +
  ggtitle('Betas in sampling 1 vs 2\nin CD8+ T cells') +
  theme(
    # X label font size
    axis.title.x = element_text(size = 20), 
    # Y label font size
    axis.title.y = element_text(size = 20), 
    # X tick font size
    axis.text.x = element_text(size = 16), 
    # Y tick font size
    axis.text.y = element_text(size = 16), 
    # title size
    title = element_text(size = 24)
  ) + 
    theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) +
  xlim(min(c(subsampling_replication_cd8t[['sampling1_vs_sampling2']][['sampling1_beta']], subsampling_replication_cd8t[['sampling1_vs_sampling2']][['sampling2_beta']])), max(c(subsampling_replication_cd8t[['sampling1_vs_sampling2']][['sampling1_beta']], subsampling_replication_cd8t[['sampling1_vs_sampling2']][['sampling2_beta']]))) +
  ylim(min(c(subsampling_replication_cd8t[['sampling1_vs_sampling2']][['sampling1_beta']], subsampling_replication_cd8t[['sampling1_vs_sampling2']][['sampling2_beta']])), max(c(subsampling_replication_cd8t[['sampling1_vs_sampling2']][['sampling1_beta']], subsampling_replication_cd8t[['sampling1_vs_sampling2']][['sampling2_beta']])))

# show plot
p_scatter_sampling

```

```{r sampling_overlap_plot_scatter, include=TRUE, fig.width=8, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# grab the full vs full
subsampling_replication_cd8t_full <- subsampling_replication_cd8t[['full_vs_full']]
# add the pct and avg
subsampling_replication_cd8t_full <- cbind(subsampling_replication_cd8t_full, cd8t_openness[match(gsub('^\\S+_', '', subsampling_replication_cd8t_full[['qtl']]), cd8t_openness[['name']]), c('avg', 'pct_exp')])
# and the pct for exp
subsampling_replication_cd8t_full[['pct_gene']] <- cd8t_nonzero[match(gsub('_\\S+$', '', subsampling_replication_cd8t_full[['qtl']]), cd8t_nonzero[['feature']]), ][['pct_exp']]

# do the same for the sampling1 and sampling2
subsampling_replication_cd8t_sample1 <- subsampling_replication_cd8t[['sampling1_vs_sampling1']]
subsampling_replication_cd8t_sample1 <- cbind(subsampling_replication_cd8t_sample1, cd8t_openness[match(gsub('^\\S+_', '', subsampling_replication_cd8t_sample1[['qtl']]), cd8t_openness[['name']]), c('avg', 'pct_exp')])
subsampling_replication_cd8t_sample1[['pct_gene']] <- subsampling_replication_cd8t_sample1[match(gsub('_\\S+$', '', subsampling_replication_cd8t_sample1[['qtl']]), cd8t_nonzero[['feature']]), ][['pct_exp']]
subsampling_replication_cd8t_sample2 <- subsampling_replication_cd8t[['sampling2_vs_sampling2']]
subsampling_replication_cd8t_sample2 <- cbind(subsampling_replication_cd8t_sample2, cd8t_openness[match(gsub('^\\S+_', '', subsampling_replication_cd8t_sample2[['qtl']]), cd8t_openness[['name']]), c('avg', 'pct_exp')])
subsampling_replication_cd8t_sample2[['pct_gene']] <- subsampling_replication_cd8t_sample2[match(gsub('_\\S+$', '', subsampling_replication_cd8t_sample2[['qtl']]), cd8t_nonzero[['feature']]), ][['pct_exp']]

# share based on pct exp
plot_sharing_per_celltype(
  list(
    'full' = unique(subsampling_replication_cd8t_full[
        subsampling_replication_cd8t_full$full_significant.x == T & 
        subsampling_replication_cd8t_full$pct_exp >= 0.001 & 
        subsampling_replication_cd8t_full$pct_gene >= 0.1, ][['qtl']]), 
    'sampling1' = unique(subsampling_replication_cd8t_sample1[
        subsampling_replication_cd8t_sample1$sampling1_significant.x == T & 
        subsampling_replication_cd8t_sample1$pct_exp >= 0.001 &  
        subsampling_replication_cd8t_sample1$pct_gene >= 0.1, ][['qtl']]), 
    'sampling2' = unique(subsampling_replication_cd8t_sample2[
        subsampling_replication_cd8t_sample2$sampling2_significant.x == T & 
        subsampling_replication_cd8t_sample2$pct_exp >= 0.001 &  
        subsampling_replication_cd8t_sample2$pct_gene >= 0.1, ][['qtl']])
  )
)
grid.text('CRE-gene pair overlaps in\nCD8+ T samplings (pct acc >= 0.1 & pct exp >= 10)', x = 0.8, y = 0.85, gp = gpar(fontsize = 16))


```

```{r sampling_testsets, include=TRUE, fig.width=8, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# full analysis
full_cd8t_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input/L1/CD8T/qtl_results_all.txt.gz'
full_cd8t <- fread(full_cd8t_loc, header = T, sep = '\t')
# sampling1
sampling1_cd8t_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling1/L1/CD8T/qtl_results_all.txt.gz'
sampling1_cd8t <- fread(sampling1_cd8t_loc, header = T, sep = '\t')
# sampling2
sampling2_cd8t_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/cre_detection/limix_sc/input_sampled/sampling2/L1/CD8T/qtl_results_all.txt.gz'
sampling2_cd8t <- fread(sampling2_cd8t_loc, header = T, sep = '\t')


# check overlaps
plot_sharing_per_celltype(
  list(
    'full' = unique(full_cd8t[['feature_id']]), 
    'sampling1' = unique(sampling1_cd8t[['feature_id']]), 
    'sampling2' = unique(sampling2_cd8t[['feature_id']])
  )
)
grid.text('Tested gene overlaps in\nCD8+ T samplings', x = 0.8, y = 0.85, gp = gpar(fontsize = 16))
plot_sharing_per_celltype(
  list(
    'full' = unique(full_cd8t[['snp_id']]), 
    'sampling1' = unique(sampling1_cd8t[['snp_id']]), 
    'sampling2' = unique(sampling2_cd8t[['snp_id']])
  )
)
grid.text('Tested region overlaps in\nCD8+ T samplings', x = 0.8, y = 0.85, gp = gpar(fontsize = 16))
plot_sharing_per_celltype(
  list(
    'full' = unique(paste(full_cd8t[['snp_id']], full_cd8t[['feature_id']])), 
    'sampling1' = unique(paste(sampling1_cd8t[['snp_id']], sampling1_cd8t[['feature_id']])), 
    'sampling2' = unique(paste(sampling2_cd8t[['snp_id']], sampling2_cd8t[['feature_id']]))
  )
)
grid.text('Tested region-gene overlaps in\nCD8+ T samplings', x = 0.8, y = 0.85, gp = gpar(fontsize = 16))


```

```{r sampling_overlap_plot_scatter, include=TRUE, fig.width=8, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# get what is only significant in sampling1
sampling1_only_cd8t_genes <- setdiff(
  unique(sampling1_cd8t[sampling1_cd8t[['feature_q_value']] < 0.05, ][['feature_id']]), 
  unique(full_cd8t[full_cd8t[['feature_q_value']] < 0.05, ][['feature_id']])
)
# and what we are sharing
sampling1_and_full_cd8t_genes <- intersect(
  unique(sampling1_cd8t[sampling1_cd8t[['feature_q_value']] < 0.05, ][['feature_id']]), 
  unique(full_cd8t[full_cd8t[['feature_q_value']] < 0.05, ][['feature_id']])
)
# make into one dataframe
shared_vs_sampling1_exp <- data.frame(
  'exp' = c(cd8t_nonzero[match(sampling1_only_cd8t_genes, cd8t_nonzero[['feature']]), ][['pct_exp']], cd8t_nonzero[match(sampling1_and_full_cd8t_genes, cd8t_nonzero[['feature']]), ][['pct_exp']]), 
  'group' = c(rep('sampling1', length(sampling1_only_cd8t_genes)), rep('both', length(sampling1_and_full_cd8t_genes)))
)
# and plot the density
ggplot(data = shared_vs_sampling1_exp, mapping = aes(x = log10(exp), fill = group)) +
  geom_density(alpha=0.5) + 
  xlab('log10 of fraction of expression') +
  ylab('density') +
  ggtitle('log10 of fraction of expression\nin CD8+ T cells for only sampling1 vs overlapping') + 
    theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white"))

```
