---
title: "mo_caqtl_lcl_replication"
author: "Roy Oelen"
date: "2025-04-28"
output: html_document
---

```{r header, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#!/usr/bin/env Rscript
############################################################################################################################
# Authors: Roy Oelen
# Name: mo_caqtl_lcl_replication.Rmd
# Function: plot the replication of the caQTLs with the LCL dataset
############################################################################################################################
```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

####################
# libraries        #
####################

library(data.table)
library(ggplot2)
library(cowplot)
library(RColorBrewer)
library(roycols)
library(ggrastr)
library(ggpubr)
library(UpSetR)
library(grid)
library(IRanges)
library(qvalue)
library(cauchyR)

```

```{r functions, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# Functions        #
####################


#' get a label dict that replaces the posix safe names into printable versions
#' 
#' @returns a label dict that replaces the posix safe names into printable versions
#' label_dict_names <- get_label_dict()
get_label_dict <- function() {
  label_dict <- list()
  label_dict[['CD4_T_cells']] <- 'CD4+ T cells'
  label_dict[['CD8_T_cells']] <- 'CD8+ T cells'
  label_dict[['CD4T']] <- 'CD4+ T'
  label_dict[['CD8T']] <- 'CD8+ T'
  label_dict[['CD4_T']] <- 'CD4+ T'
  label_dict[['CD8_T']] <- 'CD8+ T'
  label_dict[['lcl']] <- 'LCL B'
  label_dict[['Dendritic_cells']] <- 'Dendritic cells'
  label_dict[['Endothelial_cells']] <- 'Endothelial cells'
  label_dict[['Fibroblasts']] <- 'Fibroblasts'
  label_dict[['Glia_cells']] <- 'Glia cells'
  label_dict[['Mast_cells']] <- 'MAST cells'
  label_dict[['Mature_absorptive_enterocytes']] <- 'Mature absorptive enterocytes'
  label_dict[['Mature_secretory_enterocytes']] <- 'Mature secretory enterocytes'
  label_dict[['Memory_B']] <- 'Memory B cells'
  label_dict[['Monocytes']] <- 'Monocytes'
  label_dict[['monocyte']] <- 'Monocyte'
  label_dict[['Mono']] <- 'Monocyte'
  label_dict[['Plasma_cells']] <- 'Plasma cells'
  label_dict[['Stem_cells']] <- 'Stem cells'
  label_dict[['Stromal_cells']] <- 'Stromal cells'
  label_dict[['T_others']] <- 'other T cells'
  label_dict[['Transit_amplifying_cells']] <- 'Transit amplifying cells'
  label_dict[['AI']] <- 'Actively Inflamed'
  label_dict[['NI']] <- 'Non-Inflamed'
  return(label_dict)
}


rename_labels <- function(vector_to_rename) {
  # get the labels that are present
  label_renaming <- get_label_dict()
  # now check which labels we are missing
  missing_renames <- setdiff(unique(vector_to_rename), names(label_renaming))
  # add those renames as not being renames
  for (missing_rename in missing_renames) {
    label_renaming[[missing_rename]] <- missing_rename
  }
  # now replace each value with the rename
  renamed_vector <- as.vector(unlist(label_renaming[vector_to_rename]))
  # and return that
  return(renamed_vector)
}


remap_with_label_dict <- function(vector_of_names) {
  # get the label dict
  relabels <- get_label_dict()
  # get the labels available for renaming
  labels_available <- names(relabels)
  # get the ones we cant remap
  unmappable <- setdiff(unique(vector_of_names), labels_available)
  # report on those
  if (length(unmappable) > 0) {
    print(paste('cannot remap the following names, they will be returned unchanged:', paste(unmappable, collapse = ',')))
    # and put those in our remapping list as their originals
    relabels[unmappable] <- unmappable
  }
  # now actually do the remapping
  remapped <- as.vector(unlist(relabels[vector_of_names]))
  return(remapped)
}


get_color_coding_dict <- function() {
	# medhigh
  color_coding_dict <- list()
  color_coding_dict[["B"]] <- "#71BC4B"
  #color_coding_dict[['CD4_T_cells']] <- '#7FC97F'
  color_coding_dict[['CD4_T_cells']] <- '#153057'
  color_coding_dict[['CD4T']] <- '#153057'
	#color_coding_dict[['CD8_T_cells']] <- '#BEAED4'
	color_coding_dict[['CD8_T_cells']] <- '#009DDB'
	color_coding_dict[['CD8T']] <- '#009DDB'
	#color_coding_dict[['Dendritic_cells']] <- '#FDC086'
	color_coding_dict[['Dendritic_cells']] <- '#965EC8'
	color_coding_dict[['DC']] <- '#965EC8'
	color_coding_dict[['Endothelial_cells']] <- '#FFFFB3'
	color_coding_dict[['Fibroblasts']] <- '#386CB0'
	color_coding_dict[['Glia_cells']] <- '#F0027F'
	color_coding_dict[['Mast_cells']] <- '#BF5B17'
	color_coding_dict[['Mature_absorptive_enterocytes']] <- '#A6CEE3'
	color_coding_dict[['Mature_secretory_enterocytes']] <- '#1B9E77'
	color_coding_dict[['Memory_B']] <- '#D95F02'
	color_coding_dict[['Microfold_cell']] <- '#BEAED4'
	#color_coding_dict[['Monocytes']] <- '#7570B3'
	color_coding_dict[['Monocyte']] <- '#EDBA1B'
	color_coding_dict[['Naive_B_cells']] <- '#FDC086'
	color_coding_dict[['NK']] <- '#E64B50'
	#color_coding_dict[['Plasma_cells']] <- '#E7298A'
	color_coding_dict[['Plasma_cells']] <- '#DB8E00'
	color_coding_dict[['Stem_cells']] <- '#66A61E'
	color_coding_dict[['Stromal_cells']] <- '#8DD3C7'
	#color_coding_dict[['T_others']] <- '#A6761D'
	color_coding_dict[['T_others']] <- '#FF63B6'
	color_coding_dict[['Transit_amplifying_cells']] <- '#FF7F00'
	color_coding_dict[['disconcordant']] <- 'gray'
  #color_coding_dict[['CD4+ T cells']] <- '#7FC97F'
  color_coding_dict[['CD4+ T cells']] <- '#153057'
  color_coding_dict[['CD4+ T']] <- '#153057'
	#color_coding_dict[['CD8+ T cells']] <- '#BEAED4'
	color_coding_dict[['CD8+ T cells']] <- '#009DDB'
	color_coding_dict[['CD8+ T']] <- '#009DDB'
	#color_coding_dict[['Dendritic cells']] <- '#FDC086'
	color_coding_dict[['Dendritic cells']] <- '#965EC8'
	color_coding_dict[['Endothelial cells']] <- '#FFFFB3'
	color_coding_dict[['Endothelial\ncells']] <- '#FFFFB3'
	color_coding_dict[['Fibroblasts']] <- '#386CB0'
	color_coding_dict[['Glia cells']] <- '#F0027F'
	color_coding_dict[['MAST cells']] <- '#BF5B17'
	color_coding_dict[['Mature absorptive enterocytes']] <- '#A6CEE3'
	color_coding_dict[['Mature\nabsorptive\nenterocytes']] <- '#A6CEE3'
	color_coding_dict[['Mature secretory enterocytes']] <- '#1B9E77'
	color_coding_dict[['Mature secretory\nenterocytes']] <- '#1B9E77'
	color_coding_dict[['Memory B cells']] <- '#D95F02'
	#color_coding_dict[['Monocytes']] <- '#7570B3'
	color_coding_dict[['Microfold cells']] <- '#BEAED4'
	color_coding_dict[['Monocytes']] <- '#EDBA1B'
	color_coding_dict[['Naive B cells']] <- '#FDC086'
	#color_coding_dict[['Plasma cells']] <- '#E7298A'
	color_coding_dict[['Plasma cells']] <- '#DB8E00'
	color_coding_dict[['Stem cells']] <- '#66A61E'
	color_coding_dict[['Stromal cells']] <- '#8DD3C7'
	#color_coding_dict[['other T cells']] <- '#A6761D'
	color_coding_dict[['other T cells']] <- '#FF63B6'
	color_coding_dict[['Transit amplifying cells']] <- '#FF7F00'
	color_coding_dict[['Transit\namplifying cells']] <- '#FF7F00'
	color_coding_dict[['disconcordant']] <- 'gray'
	# up and down regulation will be added to, we need a whitening percentage
	pct_whitening <- 40
	# then we will check each cell type
	for (cell_type in names(color_coding_dict)) {
	  # the up color is the same as the regular one
	  color_coding_dict[[paste(cell_type, 'up')]] <- color_coding_dict[[cell_type]]
	  # but the down one will have a more faded colour
	  color_coding_dict[[paste(cell_type, 'down')]] <- colorRampPalette(c(color_coding_dict[[cell_type]], "white"))(100)[pct_whitening]
	  # we'll do something similiar when we have multiple conditions
	  color_coding_dict[[paste(cell_type, 'combined')]] <- color_coding_dict[[cell_type]]
	  color_coding_dict[[paste(cell_type, 'UT')]] <- colorRampPalette(c(color_coding_dict[[cell_type]], "white"))(100)[pct_whitening]
	  color_coding_dict[[paste(cell_type, '24hCA')]] <- colorRampPalette(c(color_coding_dict[[cell_type]], "black"))(100)[pct_whitening]
	}
	# general
	color_coding_dict[['AI']] <- 'darkblue'
	color_coding_dict[['NI']] <- 'darkred'
	color_coding_dict[['Actively Inflamed']] <- 'darkblue'
	color_coding_dict[['Non-Inflamed']] <- 'darkred'
	return(color_coding_dict)
}


split_string_with_max_length <- function(string, max_length=15) {
  # split the string on the space first
  words <- strsplit(string, ' ')[[1]]
  # and initial pasted string
  final_string <- ''
  # and the temporary string
  tmp_string <- ''
  # check each word
  for (word in words) {
    # get the lenght of the temporary string
    tmp_len <- nchar(tmp_string)
    # get the length of the word
    word_len <- nchar(word)
    # length of the final string
    final_len <- nchar(final_string)
    # check if adding the next word would make us go over the limit
    if ((tmp_len + word_len) > max_length) {
      if (final_len > 0) {
        # add the temporary word to the final string if it was not empty
        final_string <- paste(final_string, '\n', tmp_string, sep = '')
      }
      else{
        # if there was not final string yet, it will just become that temporary string
        final_string <- tmp_string
      }
      # reset the temporary string
      tmp_string <- word
    }
    else{
      # otherwise add it to the temporary string
      if (tmp_len > 0) {
        tmp_string <- paste(tmp_string, word)
      }
      # or set if the temporary string was empty
      else{
        tmp_string <- word
      }
    }
  }
  # add last word
  if (nchar(paste(final_string, tmp_string)) > max_length) {
    if (nchar(final_string) == 0) {
      final_string <- tmp_string
    }
    else if (nchar(tmp_string > 0)) {
      final_string <- paste(final_string, '\n', tmp_string, sep = '')
    }
    else{
      # nothing the final string is as it is
    }
  }
  else {
    if (nchar(final_string) == 0) {
      final_string <- tmp_string
    }
    else if(nchar(tmp_string) == 0){
      # nothing, the final string is as is
    }
    else{
      final_string <- paste(final_string, ' ', tmp_string, sep = '')
    }
  }
  # add the last word
  return(final_string)
}


split_strings_with_max_length <- function(strings, max_length=15) {
  strings_split <- sapply(strings, FUN = function(x){
    split_string_with_max_length(x, max_length)
  })
  strings_split <- as.vector(strings_split)
  return(strings_split)
}


#' get the eGenes per cell type from QTL output
#' 
#' @param qtl_output_loc base location of the QTL output per cell type
#' @param output_file which output file to read for the results
#' @param gene_column which column to use as the gene identifier
#' @returns a list with the egenes per cell type
#' 
get_egenes_per_celltype_limix <- function(qtl_output_loc, output_file='qtl_results_all.txt.gz', gene_column='feature_id', significance_column='feature_q_value', significance_cutoff=0.05, verbose=T) {
  # get the folders in the directory, which should be the cell types
  cell_types <- list.dirs(qtl_output_loc, full.names = F, recursive = F)
  # we will store the results in a list for now
  egenes_per_celltype <- list()
  # check each cell type
  for (cell_type in cell_types) {
    # paste together the full path
    full_cell_type_path <- paste(qtl_output_loc, '/', cell_type, '/', output_file, sep = '')
    # log if requested
    if (verbose) {
      print(paste('reading', full_cell_type_path))
    }
    # read the file
    cell_type_output <- read.table(full_cell_type_path, sep = '\t', header = T)
    # filter the results on significance
    if (!is.null(significance_column)) {
      # print progress if requested
      if (verbose) {
        print(paste('variant+phenotype before filtering', nrow(cell_type_output)))
      }
      # filter
      cell_type_output <- cell_type_output[
        !is.na(cell_type_output[[significance_column]]) &
          cell_type_output[[significance_column]] < significance_cutoff, 
      ]
      if (verbose) {
        print(paste('variant+phenotype after filtering', nrow(cell_type_output)))
      }
    }
    # get the unique genes in this file
    unique_genes <- unique(cell_type_output[[gene_column]])
    # add to the list
    egenes_per_celltype[[cell_type]] <- unique_genes
  }
  # turn into a dataframe
  return(egenes_per_celltype)
}



#' Plot Sharing of  Genes per Cell Type
#'
#' This function plots the sharing of differentially genes across cell types using an UpSet plot. It allows the use of custom label and color dictionaries.
#'
#' @param genes_per_ct list with the genes for each cell type
#' @param use_label_dict A logical value indicating whether to use a custom label dictionary for renaming cell types. Default is TRUE.
#' @param use_color_dict A logical value indicating whether to use a custom color dictionary for cell types. Default is TRUE.
#' @param n_intersects value describing how many intersections to plot, default is all
#' @return An UpSet plot showing the sharing of DE genes across cell types.
#'
plot_sharing_per_celltype <- function(genes_per_ct, use_label_dict=T, use_color_dict=T, n_intersects=NA){
  # get the total overlap
  total_overlap <- fromList(genes_per_ct)
  # count how many in each overlap
  combination_to_overlap <- list()
  apply(total_overlap, 1, function(x){
    # get which ones have a number
    positions_1 <- x > 0
    # get which these are, and paste together
    cols_1 <- paste(colnames(total_overlap)[positions_1], collapse = ',')
    # add to list if does not exist
    if (cols_1 %in% c(names(combination_to_overlap))) {
      combination_to_overlap[[cols_1]] <<- combination_to_overlap[[cols_1]] + 1
    }
    else{
      combination_to_overlap[[cols_1]] <<- 1
    }
  })
  # make into an ordered df
  combination_numbers <- data.frame('combination' = names(combination_to_overlap), 'nr' = as.vector(unlist(combination_to_overlap)))
  combination_numbers <- combination_numbers[order(combination_numbers[['nr']], combination_numbers[['combination']], decreasing = T), ]
  # get lowest number we have for the sets
  intersect_size_smallest <- 0
  if (is.na(n_intersects)) {
    intersect_size_smallest <- min(combination_numbers[['nr']])
  }
  else {
    intersect_size_smallest <- combination_numbers[n_intersects, 'nr']
  }
  # set queries and colours
  queries <- list()
  sets.bar.color <- 'black'
  if(use_color_dict){
    # create df to store the number of each set, so we know how to order
    nrs_df <- NULL
    # get the cell types we have
    cell_types <- names(genes_per_ct)
    # get colour codes for the cell types
    cell_type_colours <- get_color_coding_dict()
    # also get colours for the cell types we don't have colours for
    cell_type_colours_missing <- get_color_list(setdiff(cell_types, names(cell_type_colours)))
    # and merge them
    cell_type_colours <- c(cell_type_colours, cell_type_colours_missing)
    # add the colors for the cell types
    i <- 1
    for(cell_type in cell_types){
      # check if there is a singleton for this cell type, so this celltype is 1, but the total of the row is also 1
      n_singletons <- nrow(total_overlap[total_overlap[[cell_type]] == 1 & rowSums(total_overlap) == 1, ])
      # if we have singletons, colour it
      if (n_singletons > 0 & n_singletons >= intersect_size_smallest) {
        # add for the singles in the intersection sizes
        ct_list <- list(
          query = intersects,
          params = list(cell_type),
          color = cell_type_colours[[cell_type]],
          active = T)
        queries[[i]] <- ct_list
        i <- i + 1
      }
      # add for the DF to order the set sizes
      numbers_row <- data.frame(ct=c(cell_type), nr=c(length(genes_per_ct[[cell_type]])), stringsAsFactors = F)
      if(is.null(nrs_df)){
        nrs_df <- numbers_row
      }
      else{
        nrs_df <- rbind(nrs_df, numbers_row)
      }
    }
    # get the order of the sets
    ordered_cts <- nrs_df[order(nrs_df$nr, decreasing = T), 'ct']
    # add the colors for the sets
    sets.bar.color <- unlist(cell_type_colours[ordered_cts])
    # make the plot
    upset(total_overlap, order.by = 'freq', nsets = length(genes_per_ct), queries = queries, sets.bar.color=sets.bar.color, nintersects = n_intersects)
  }
  else {
    upset(total_overlap, order.by = 'freq', nsets = length(genes_per_ct), nintersects = n_intersects)
  }
  
  #return(DE_genes_per_ct)
}

#' plot in a barplot the number of DE genes per cell type
#' 
#' @param egene_numbers the table containing the number of eenes per cell type
#' @param celltype_column which column of the supplied table has the celltype name
#' @param number_column which column of the supplied table has the number of DE genes
#' @param pointless draw the ticks on the bottom of the plot?
#' @param legendless draw the legend?
#' @param ylim the range for the y-axis
#' @param paper_style use the paper style with more whitespace
#' @param angle_labels angle the x labels 90 degrees?
#' @param use_distinct_colours use the distinct colour palette instead of ggplot defaults (optional, default T)
#' @param use_sampling randomly sample colours from the distinct colour palette (optional, default F)
#' @param color_indices supply specific indices relating to colours to use from the distinct colour palette. Use 'get_available_colours_grid' to get the colours and their indices (optional, unused by default)
#' @param use_label_dict change names to a more pleasing format
#' @param make_labels_multiline make labels multiline if they are long
#' @param x_order to order the values on the x axis
#' @returns a barplot with the number of eGenes per cell type
#' 
egene_numbers_to_plot <- function(egene_numbers, celltype_column='cell_type', number_column='nr', pointless=F, legendless=F, ylim=NULL, paper_style=T, angle_labels=T, use_distinct_colours=T, use_sampling=F, color_indices=NULL, use_color_dict=F, use_label_dict=T, split_long_labels_to_lines=T, x_order=NULL) {
  # remap names if requested
  if (use_label_dict) {
    egene_numbers[[celltype_column]] <- remap_with_label_dict(egene_numbers[[celltype_column]])
  }
  # make them multiline
  if (split_long_labels_to_lines) {
    egene_numbers[[celltype_column]] <- split_strings_with_max_length(egene_numbers[[celltype_column]])
  }
  # order the x axis if requested
  if (!is.null(x_order)) {
    egene_numbers[[celltype_column]] <- factor(egene_numbers[[celltype_column]], levels = x_order)
  }
  # start plot
  p <- ggplot(mapping = aes(x = egene_numbers[[celltype_column]], y = egene_numbers[[number_column]], fill = egene_numbers[[celltype_column]])) +
    geom_bar(stat='identity') + xlab(celltype_column) + ylab(number_column)
  # options
  if (use_distinct_colours) {
    # get the unique possible assigments
    possible_assignments <- unique(egene_numbers[[celltype_column]])
    # put into a list
    colour_mapping <- roycols::get_color_list(possible_assignments)
    # add to plot
    p <- p + scale_fill_manual(values = colour_mapping)
  }
  if (use_color_dict) {
    # get the color coding dict
    colour_mapping <- get_color_coding_dict()
    # also rename here then
    if (split_long_labels_to_lines) {
      names(colour_mapping) <- split_strings_with_max_length(names(colour_mapping))
    }
    # add to plot
    p <- p + scale_fill_manual(values = colour_mapping)
  }
  if(!is.null(ylim)){
    p <- p + ylim(ylim)
  }
  if(pointless){
    p <- p + theme(axis.text.x=element_blank(), 
                   axis.ticks = element_blank())
  }
  if(legendless){
    p <- p + theme(legend.position = 'none')
  }
  if (paper_style) {
    p <- p + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white"))
  }
  if (angle_labels) {
    p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  }
  return(p)
}


#' Function for Rb analysis
#'
#' @param b1 Beta from first dataset.
#' @param se1 Standard error of beta from first dataset.
#' @param b2 Beta from second dataset.
#' @param se2 Standard error of beta from second dataset.
#' @param theta Variable representing sample overlap between two datasets. Should be set 0 if no sample overlap.
#'
#' @return Data frame with Rb, SE(Rb) and corresponding P-value.
#' @export
#'
#' @note This function is slightly adapted from the script shared by Ting Qi.
#'
#' @examples
calcu_cor_true <- function(b1, se1, b2, se2, theta=1) {
  idx <- which(is.infinite(b1) | is.infinite(b2) | is.infinite(se1) | is.infinite(se2))
  if (length(idx) > 0) {
    b1 <- b1[-idx]
    se1 <- se1[-idx]
    b2 <- b2[-idx]
    se2 <- se2[-idx]
    theta <- theta[-idx]
  }
  # when there are no finite values in any of these, we need to return NA
  if (length(b1) == 0 | length(b2) == 0 | length(se2) == 0 | length(se2) == 0) {
    warning(paste('no finite values present in one of vectors, will return NA. 
  b1:', as.character(length(b1))), '
  b2:', as.character(length(b2)), '
  se1:', as.character(length(se1)), '
  se2:', as.character(length(se2)))
    return(matrix(c(NA, NA, NA), nrow = 1, ncol = 3, dimnames = list(NA, c('r', 'se_r', 'p'))))
  }

  var_b1 <- var(b1, na.rm = T) - mean(se1^2, na.rm = T)
  var_b2 <- var(b2, na.rm = T) - mean(se2^2, na.rm = T)
  if (var_b1 < 0) {
    var_b1 <- var(b1, na.rm = T)
  }
  if (var_b2 < 0) {
    var_b2 <- var(b2, na.rm = T)
  }
  cov_b1_b2 <- cov(b1, b2, use = "complete.obs") - mean(theta, na.rm = T) * sqrt(mean(se1^2, na.rm = T) * mean(se2^2, na.rm = T))
  r <- cov_b1_b2 / sqrt(var_b1 * var_b2)

  r_jack <- c()
  n <- length(b1)
  for (k in 1:n) {
    b1_jack <- b1[-k]
    se1_jack <- se1[-k]
    var_b1_jack <- var(b1_jack, na.rm = T) - mean(se1_jack^2, na.rm = T)
    b2_jack <- b2[-k]
    se2_jack <- se2[-k]
    var_b2_jack <- var(b2_jack, na.rm = T) - mean(se2_jack^2, na.rm = T)
    if (var_b1_jack < 0) {
      var_b1_jack <- var(b1_jack, na.rm = T)
    }
    if (var_b2_jack < 0) {
      var_b2_jack <- var(b2_jack, na.rm = T)
    }
    theta_jack <- theta[-k]
    cov_e1_jack_e2_jack <- mean(theta_jack, na.rm = T) * sqrt(mean(se1_jack^2, na.rm = T) * mean(se2_jack^2, na.rm = T))
    cov_b1_b2_jack <- cov(b1_jack, b2_jack, use = "complete.obs") - cov_e1_jack_e2_jack
    r_tmp <- cov_b1_b2_jack / sqrt(var_b1_jack * var_b2_jack)
    r_jack <- c(r_jack, r_tmp)
  }
  r_mean <- mean(r_jack, na.rm = T)
  idx <- which(is.na(r_jack))
  if (length(idx) > 0) {
    se_r <- sqrt((n - 1) / n * sum((r_jack[-idx] - r_mean)^2))
  } else {
    se_r <- sqrt((n - 1) / n * sum((r_jack - r_mean)^2))
  }

  p <- pchisq((r / se_r)**2, df = 1, lower.tail = FALSE)

  res <- cbind(r, se_r, p)
  return(res)
}


get_stats_qtl_matches <- function(table_per_match, name_split='_vs_', 
                                  significance_column_replicating_emperical='fdr', 
                                  significance_column_replicating_nominal='p',
                                  significance_column_replicating_in_emperical='fdr',
                                  significance_column_replicating_in_nominal='p',
                                  significance_cutoff_replicating_emperical=0.05, 
                                  significance_cutoff_replicating_nominal=0.05, 
                                  significance_cutoff_replicating_in_emperical=0.05, 
                                  significance_cutoff_replicating_in_nominal=0.05, 
                                  score_column_replicating='zscore', 
                                  score_column_replicating_in='zscore', 
                                  beta_column_replicating='beta', 
                                  beta_column_replicating_in='beta', 
                                  se_column_replicating='se', 
                                  se_column_replicating_in='se', 
                                  allele_column_replicating='assessed_allele', 
                                  allele_column_replicating_in='assessed_allele', 
                                  cor_method='spearman') {
  # prepare a list of tables of all the comparisons
  stats_per_combination <- list()
  # check each of the tables
  for (combination in names(table_per_match)) {
    print(combination)
    # extract the two names
    replicating_name <- strsplit(combination, name_split)[[1]][1]
    replicating_in_name <- strsplit(combination, name_split)[[1]][2]
    # extract the table
    replication_table <- table_per_match[[combination]]
    # init variables
    replicated_emperical_emperical_in_replicating <- NA
    nominal_to_nominal_zscore_correlation <- NA
    emperical_to_nominal_zscore_correlation <- NA
    emperical_to_emperical_zscore_correlation <- NA
    nominal_to_nominal_concordance <- NA
    emperical_to_nominal_concordance <- NA
    emperical_to_emperical_concordance <- NA
    nominal_to_nominal_rb <- NA
    emperical_to_nominal_rb <- NA
    emperical_to_all_rb <- NA
    emperical_to_emperical_rb <- NA
    # if they are the same, we don't have to do much
    if (replicating_name == replicating_in_name) {
      # we check how many are significant
      n_sig <- NULL
      if (isTRUE(significance_cutoff_replicating_emperical)) {
        n_sig <- nrow(replication_table[
          replication_table[[paste0(replicating_name, '_', significance_column_replicating_emperical, '.x')]] == T, ])
      } else {
        n_sig <- nrow(replication_table[
          replication_table[[paste0(replicating_name, '_', significance_column_replicating_emperical, '.x')]] < significance_cutoff_replicating_emperical, ])
      }
      # and then all of these will be the same
      replicated_emperical_emperical_in_replicating <- n_sig
      replicated_emperical_nominal_in_replicating <- n_sig
      replicated_emperical_tested_in_replicating <- n_sig
      replicated_emperical_nominal_in_replicating <- n_sig
      # these will all be one
      nominal_to_nominal_zscore_correlation <- 1
      emperical_to_nominal_zscore_correlation <- 1
      emperical_to_emperical_zscore_correlation <- 1
      nominal_to_nominal_concordance <- 1
      emperical_to_nominal_concordance <- 1
      emperical_to_emperical_concordance <- 1
      nominal_to_nominal_rb <- 1
      emperical_to_nominal_rb <- 1
      emperical_to_all_rb <- 1
      emperical_to_emperical_rb <- 1
    }
    else {
      # check how many significant in replicating, are present in the other
      replicated_emperical_tested_in_replicating <- NULL
      # using the boolean value in the column if it was a boolean
      if (isTRUE(significance_cutoff_replicating_emperical)) {
        replicated_emperical_tested_in_replicating <- nrow(replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] == T, ])
      } else {
        # otherwise use it as a cutoff
        replicated_emperical_tested_in_replicating <- nrow(replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] < significance_cutoff_replicating_emperical, ])
      }
      
      # subset to emperical only in where we are replicating
      replication_table_emp_to_all <- NULL
      # if the significance cutoff is a T/F we don't use it as a cutoff
      if (isTRUE(significance_cutoff_replicating_emperical)) {
        replication_table_emp_to_all <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] == T, 
        ]
      } else {
        replication_table_emp_to_all <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] < significance_cutoff_replicating_emperical, 
        ]
      }
      # and the beta
      beta_replicating_in <- replication_table_emp_to_all[[paste(replicating_in_name, beta_column_replicating_in, sep = '_')]]
      # check which have the same allelic direction
      alleles_differ_locs <- which(replication_table_emp_to_all[[paste(replicating_name, allele_column_replicating, sep = '_')]] != replication_table_emp_to_all[[paste(replicating_in_name, allele_column_replicating_in, sep = '_')]])
      # and flip direction of betas to reflect this
      beta_replicating_in[alleles_differ_locs] <- -1 * beta_replicating_in[alleles_differ_locs]
      # calculate Rb
     emp_to_all_rb_table <- calcu_cor_true(b1 = replication_table_emp_to_all[[paste(replicating_name, beta_column_replicating, sep = '_')]], se1 = replication_table_emp_to_all[[paste(replicating_name, se_column_replicating, sep = '_')]], b2 = beta_replicating_in, se2 = replication_table_emp_to_all[[paste(replicating_in_name, se_column_replicating_in, sep = '_')]])
      emperical_to_all_rb <- emp_to_all_rb_table[1, 'r']
      
      # subset to nominal in both
      replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_nominal, sep = '_')]] < significance_cutoff_replicating_nominal &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_nominal, sep = '_')]] < significance_cutoff_replicating_in_nominal, 
      ]
      # get the Z scores
      zscore_replicating <- replication_table[[paste(replicating_name, score_column_replicating, sep = '_')]]
      zscore_replicating_in <- replication_table[[paste(replicating_in_name, score_column_replicating_in, sep = '_')]]
      # and the beta
      beta_replicating_in <- replication_table[[paste(replicating_in_name, beta_column_replicating_in, sep = '_')]]
      # check which have the same allelic direction
      alleles_differ_locs <- which(replication_table[[paste(replicating_name, allele_column_replicating, sep = '_')]] != replication_table[[paste(replicating_in_name, allele_column_replicating_in, sep = '_')]])
      # and flip direction of z score and betas to reflect this
      zscore_replicating_in[alleles_differ_locs] <- -1 * zscore_replicating_in[alleles_differ_locs]
      beta_replicating_in[alleles_differ_locs] <- -1 * beta_replicating_in[alleles_differ_locs]
      # get the correlation of the two
      nominal_to_nominal_zscore_correlation <- cor(zscore_replicating, zscore_replicating_in, method = cor_method)
      # and concordance
      nominal_to_nominal_concordance <- sum(sign(zscore_replicating) == sign(zscore_replicating_in)) / length(zscore_replicating)
      # and the rb
      #nominal_to_nominal_rb <- 1 - mean(abs(((zscore_replicating_in - zscore_replicating) / zscore_replicating)))
      nominal_to_nominal_rb_table <- calcu_cor_true(b1 = replication_table[[paste(replicating_name, beta_column_replicating, sep = '_')]], se1 = replication_table[[paste(replicating_name, se_column_replicating, sep = '_')]], b2 = beta_replicating_in, se2 = replication_table[[paste(replicating_in_name, se_column_replicating_in, sep = '_')]])
      nominal_to_nominal_rb <- nominal_to_nominal_rb_table[1, 'r']
      
      # subset the replicating to emperical for replicating
      if (isTRUE(significance_cutoff_replicating_emperical)) {
        # if the cutoff is just a 'T' value, we use that as the filter
        replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] == T &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_nominal, sep = '_')]] < significance_cutoff_replicating_in_nominal, 
        ]
      } else {
        replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] < significance_cutoff_replicating_emperical &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_nominal, sep = '_')]] < significance_cutoff_replicating_in_nominal, 
        ]
      }
      
      # check how many significant in replicating, are nominally significant in the other
      replicated_emperical_nominal_in_replicating <- nrow(replication_table)
      # get the Z scores
      zscore_replicating <- replication_table[[paste(replicating_name, score_column_replicating, sep = '_')]]
      zscore_replicating_in <- replication_table[[paste(replicating_in_name, score_column_replicating_in, sep = '_')]]
      # and the beta
      beta_replicating_in <- replication_table[[paste(replicating_in_name, beta_column_replicating_in, sep = '_')]]
      # check which have the same allelic direction
      alleles_differ_locs <- which(replication_table[[paste(replicating_name, allele_column_replicating, sep = '_')]] != replication_table[[paste(replicating_in_name, allele_column_replicating_in, sep = '_')]])
      # and flip direction of z score to reflect this
      zscore_replicating_in[alleles_differ_locs] <- -1 * zscore_replicating_in[alleles_differ_locs]
      beta_replicating_in[alleles_differ_locs] <- -1 * beta_replicating_in[alleles_differ_locs]
      # get the correlation of the two
      emperical_to_nominal_zscore_correlation <- cor(zscore_replicating, zscore_replicating_in, method = cor_method)
      # and concordance
      emperical_to_nominal_concordance <- sum(sign(zscore_replicating) == sign(zscore_replicating_in)) / length(zscore_replicating)
      # and the rb
      #emperical_to_nominal_rb <- 1 - mean(abs(((zscore_replicating_in - zscore_replicating) / zscore_replicating)))
      emperical_to_nominal_rb_table <- calcu_cor_true(b1 = replication_table[[paste(replicating_name, beta_column_replicating, sep = '_')]], se1 = replication_table[[paste(replicating_name, se_column_replicating, sep = '_')]], b2 = beta_replicating_in, se2 = replication_table[[paste(replicating_in_name, se_column_replicating_in, sep = '_')]])
      emperical_to_nominal_rb <- emperical_to_nominal_rb_table[1, 'r']
      
      # subset the replicating to emperical for both
      if (isTRUE(significance_cutoff_replicating_emperical) & isTRUE(significance_cutoff_replicating_in_emperical)) {
        # subset both just on that T value
        replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] == T &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_emperical, sep = '_')]] == T, 
        ]
      }
      else if(isTRUE(significance_cutoff_replicating_emperical)) {
        # or only one
        replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] == T &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_emperical, sep = '_')]] < significance_cutoff_replicating_in_emperical, 
        ]
      }
      else if(isTRUE(significance_cutoff_replicating_in_emperical)) {
        # or the other
        replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] < significance_cutoff_replicating_emperical &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_emperical, sep = '_')]] == T, 
        ]
      }
      else {
        # or on actual values
        replication_table <- replication_table[
          replication_table[[paste(replicating_name, significance_column_replicating_emperical, sep = '_')]] < significance_cutoff_replicating_emperical &
          replication_table[[paste(replicating_in_name, significance_column_replicating_in_emperical, sep = '_')]] < significance_cutoff_replicating_in_emperical, 
        ]
      }
      
      # check how many significant in replicating, are also significant in the other
      replicated_emperical_emperical_in_replicating <- nrow(replication_table)
      # get the Z scores
      zscore_replicating <- replication_table[[paste(replicating_name, score_column_replicating, sep = '_')]]
      zscore_replicating_in <- replication_table[[paste(replicating_in_name, score_column_replicating_in, sep = '_')]]
      # and the beta
      beta_replicating_in <- replication_table[[paste(replicating_in_name, beta_column_replicating_in, sep = '_')]]
      # check which have the same allelic direction
      alleles_differ_locs <- which(replication_table[[paste(replicating_name, allele_column_replicating, sep = '_')]] != replication_table[[paste(replicating_in_name, allele_column_replicating_in, sep = '_')]])
      # and flip direction of z score to reflect this
      zscore_replicating_in[alleles_differ_locs] <- -1 * zscore_replicating_in[alleles_differ_locs]
      beta_replicating_in[alleles_differ_locs] <- -1 * beta_replicating_in[alleles_differ_locs]
      # get the correlation of the two
      emperical_to_emperical_zscore_correlation <- cor(zscore_replicating, zscore_replicating_in, method = cor_method)
      # and concordance
      emperical_to_emperical_concordance <- sum(sign(zscore_replicating) == sign(zscore_replicating_in)) / length(zscore_replicating)
      # and the rb
      #emperical_to_emperical_rb <- 1 - mean(abs(((zscore_replicating_in - zscore_replicating) / zscore_replicating)))
      emperical_to_emperical_rb_table <- calcu_cor_true(b1 = replication_table[[paste(replicating_name, beta_column_replicating, sep = '_')]], se1 = replication_table[[paste(replicating_name, se_column_replicating, sep = '_')]], b2 = beta_replicating_in, se2 = replication_table[[paste(replicating_in_name, se_column_replicating_in, sep = '_')]])
       emperical_to_emperical_rb <- emperical_to_emperical_rb_table[1, 'r']
      
    }
    # put it all in a table
      stats_combination <- data.frame(
        'replicating' = c(replicating_name), 
        'replicating_in' = c(replicating_in_name), 
        'n_sig_tested' = c(replicated_emperical_tested_in_replicating), 
        'n_sig_nom' = c(replicated_emperical_nominal_in_replicating), 
        'n_sig_both' = c(replicated_emperical_emperical_in_replicating), 
        'cor_nom_nom' = c(nominal_to_nominal_zscore_correlation), 
        'cor_emp_nom' = c(emperical_to_nominal_zscore_correlation), 
        'cor_emp_emp' = c(emperical_to_emperical_zscore_correlation), 
        'con_nom_nom' = c(nominal_to_nominal_concordance), 
        'con_emp_nom' = c(emperical_to_nominal_concordance), 
        'con_emp_emp' = c(emperical_to_emperical_concordance), 
        'rb_nom_nom' = c(nominal_to_nominal_rb), 
        'rb_emp_nom' = c(emperical_to_nominal_rb), 
        'rb_emp_emp' = c(emperical_to_emperical_rb), 
        'rb_emp_all' = c(emperical_to_all_rb))
      # put in the list
      stats_per_combination[[combination]] <- stats_combination
  }
  # merge all tables
  stats_combination_all <- do.call('rbind', stats_per_combination)
  return(stats_combination_all)
}


plot_replication_stats <- function(replication_stats, replicating_column='replicating', replicating_in_column='replicating_in', matching_value_to_text=list('n_sig_tested' = 'N sig:'), comparing_value_to_text=list('n_sig_both' = 'N sig both:', 'n_sig_tested' = 'N test both:', 'cor_emp_nom' = 'nom cor:'), colour_column='cor_emp_nom', angle_labels=F, use_label_dict=T, legendless=F, paper_style=T, round_decimals=2, low_color='blue', mid_color='white', high_color='red', mid_value=0, category_plot_order=NULL, text_size=6) {
  # round values if required
  if (!is.null(round_decimals)) {
    for (col in colnames(replication_stats)) {
      if (is.numeric(replication_stats[[col]])) {
        replication_stats[[col]] <- round(replication_stats[[col]], digits = round_decimals)
      }
    }
  }
  # check each row of this table
  replication_stats[['display_text']] <- apply(replication_stats, 1, FUN = function(x) {
    # get the replicating cell type
    replicating <- x[[replicating_column]]
    # and what we are replicating in
    replicating_in <- x[[replicating_in_column]]
    # create the text
    final_text <- NULL
    # check if they are the same
    if (replicating == replicating_in) {
      # then we use this list
      list_to_check <- matching_value_to_text
    }
    else {
      # otherwise we use the other list
      list_to_check <- comparing_value_to_text
    }
    # check each column in the matching list
    for (column_to_check in names(list_to_check)) {
      # make the new piece of text by getting the matching text, and the value from the table
      display_text_part <- paste0(list_to_check[[column_to_check]], as.character(x[[column_to_check]]))
      # check if we have any text
      if (is.null(final_text)) {
        final_text <- display_text_part
      }
      else {
        # if we have, paste together
        final_text <- paste(final_text, display_text_part, sep = '\n')
      }
    }
    return(final_text)
  })
  # remap names if requested
  if (use_label_dict) {
    replication_stats[[replicating_column]] <- remap_with_label_dict(replication_stats[[replicating_column]])
    replication_stats[[replicating_in_column]] <- remap_with_label_dict(replication_stats[[replicating_in_column]])
  }
  # order labels if requested
  if (!is.null(category_plot_order)) {
    # double check if we have the labels
    all_labels <- unique(c(replication_stats[[replicating_column]], replication_stats[[replicating_in_column]]))
    # check if there is any difference between what we have and the categories
    labels_missing <- setdiff(all_labels, category_plot_order)
    # and stop it there are
    if (length(labels_missing) > 0) {
      stop(paste('category_plot_order does not contain all values in categories, missing are:', paste(labels_missing, sep = ',')))
    }
    replication_stats[[replicating_column]] <- factor(replication_stats[[replicating_column]], levels = category_plot_order)
    replication_stats[[replicating_in_column]] <- factor(replication_stats[[replicating_in_column]], levels = category_plot_order)
  }
  # now make the plot (use the !! rlang::sym(variable_name) synthax to be able to use a variable for ggplot)
  p <- ggplot(data=replication_stats, aes(x=!! rlang::sym(replicating_column), y=!! rlang::sym(replicating_in_column), fill=!! rlang::sym(colour_column))) + geom_tile() + scale_fill_gradient2(low=low_color, mid = mid_color, high=high_color, midpoint = mid_value) + geom_text(aes(label=display_text), size = text_size)
  # some options
  if(legendless){
    p <- p + theme(legend.position = 'none')
  }
  if (paper_style) {
    p <- p + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white"))
  }
  if (angle_labels) {
    p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  }
  return(p)
}

match_lcl_to_caqtls <- function(lcl_sumstats, caqtl_output_loc, cts=c('B', 'CD4T', 'CD8T', 'DC', 'monocyte', 'NK')) {
  # we'll store matched info per cell type
  lcl_per_ct <- list()
  # check each cell type
  for (ct in cts) {
    # we'll read the LCL ocombinedpcombined per chromosome, so we'll store that in a list first
    lcl_per_chromosome <- list()
    b_per_chromosome <- list()
    # we'll check each chromosome
    for (chromosome in 1:22) {
      # progress
      message(paste('doing chromosome', chromosome))
      # paste together the paths
      lcl_chromosome_loc <- paste0(lcl_caqtl_loc, '/qtl_results_all_qval_', chromosome, '.txt.gz')
      b_chromosome_loc <- paste0(caqtl_output_loc, '/', ct, '/', '/qtl_results_all_qval_', chromosome, '.txt.gz')
      # read this ocombinedpcombined
      lcl_chromosome <- fread(lcl_chromosome_loc, header = T, sep = '\t')
      b_chromosome <- fread(b_chromosome_loc, header = T, sep = '\t')
      # add the QTL explicitly
      b_chromosome[['qtl']] <- paste0(b_chromosome[['feature_id']], '_', b_chromosome[['snp_chromosome']], ':', b_chromosome[['snp_position']])
      # add the Zscore
      b_chromosome[['zscore']] <- b_chromosome[['beta']] / b_chromosome[['beta_se']]
      # get the positions, we need them later
      b_combined_caqtl_significant_chromosome_positions <- unique(b_chromosome[, c('feature_id', 'feature_start', 'feature_end')])
      # let's reduce the data to what is strictly necessary
      b_chromosome <- b_chromosome[, c('qtl', 'feature_id', 'zscore', 'assessed_allele', 'beta', 'beta_se', 'p_value')]
      # and rename columns so they don't conflict with the lcl data
      colnames(b_chromosome) <- c('qtl', 'feature_id', paste0(ct, '_zscore'), paste0(ct, '_assesed_allele'), paste0(ct, '_beta'), paste0(ct, '_se'), paste0(ct, '_p'))
      # put in the b list
      b_per_chromosome[[paste0('chr', chromosome)]] <- b_chromosome
    
      # harmonize region name
      lcl_chromosome[['feature_id']] <- paste('chr', gsub(':', '-', lcl_chromosome[['feature_id']]), sep = '')
    
      # get only positions for this chromosome
      lcl_chromosome_positions <- unique(lcl_chromosome[, c('feature_id', 'feature_start', 'feature_end')])
      # get the ranges
      lcl_chromosome_iranges <- IRanges(start = lcl_chromosome_positions[['feature_start']], end = lcl_chromosome_positions[['feature_end']])
      # and make those iranges
      b_combined_caqtl_significant_chromosome_iranges <- IRanges(b_combined_caqtl_significant_chromosome_positions[['feature_start']], end = b_combined_caqtl_significant_chromosome_positions[['feature_end']])
      # find overlaps
      feature_chromosome_overlaps <- findOverlaps(b_combined_caqtl_significant_chromosome_iranges, lcl_chromosome_iranges)
      # extract overlapping ranges
      overlapping_ranges <- pintersect(lcl_chromosome_iranges[subjectHits(feature_chromosome_overlaps)], b_combined_caqtl_significant_chromosome_iranges[queryHits(feature_chromosome_overlaps)])
      # create a  table for the overlaps
      overlaps_table <- data.table(
        'feature_id' = lcl_chromosome_positions[['feature_id']][subjectHits(feature_chromosome_overlaps)],
        'overlap_start' = start(overlapping_ranges),
        'overlap_end' = end(overlapping_ranges)
      )
      # add these positions
      lcl_chromosome <- merge(lcl_chromosome, overlaps_table, by = 'feature_id', all.x = T, allow.cartesian=TRUE)
      # remove the ones we cannot remap
      lcl_chromosome <- lcl_chromosome[!is.na(lcl_chromosome[['overlap_start']]), ]
      # # add the qtl column
      lcl_chromosome[['qtl']] <- paste0('chr', lcl_chromosome[['feature_chromosome']], '-', lcl_chromosome[['overlap_start']], '-', lcl_chromosome[['overlap_end']], '_', lcl_chromosome[['snp_chromosome']], ':', lcl_chromosome[['snp_position']])
      # calculate the Z
      lcl_chromosome[['zscore']] <- lcl_chromosome[['beta']] / lcl_chromosome[['beta_se']]
      # order by that z
      lcl_chromosome <- lcl_chromosome[order(abs(lcl_chromosome[['zscore']]), decreasing = T), ]
      # if there were multiple overlapping ranges, keep the most significant one
      lcl_chromosome <- lcl_chromosome[!duplicated(lcl_chromosome[['qtl']]), ]
      # subset to the column we want
      lcl_chromosome <- lcl_chromosome[, c('qtl', 'feature_id', 'zscore', 'assessed_allele', 'beta', 'beta_se', 'p_value')]
      # and rename columns so they don't conflict with the lcl data
      colnames(lcl_chromosome) <- c('qtl', 'feature_id', 'lcl_zscore', 'lcl_assesed_allele', 'lcl_beta', 'lcl_se', 'lcl_p')
      # # and pcombined in the list
      lcl_per_chromosome[[paste0('chr', chromosome)]] <- lcl_chromosome
    }
    # merge all the lcl chromosomes
    lcl_caqtls <- do.call('rbind', lcl_per_chromosome)
    b_caqtls <- do.call('rbind', b_per_chromosome)
    
    # add B&H
    lcl_caqtls[['lcl_bh']] <- p.adjust(lcl_caqtls[['lcl_p']], method = 'BH')
    # now merge the two tables
    b_combined_top_and_lcl_caqtl <- merge(x = lcl_caqtls, y = b_caqtls, by = 'qtl')
    # and flip the z score if in the opposite direction
    b_combined_top_and_lcl_caqtl[['lcl_zscore_signed']] <- b_combined_top_and_lcl_caqtl[['lcl_zscore']]
    b_combined_top_and_lcl_caqtl[b_combined_top_and_lcl_caqtl[[paste0(ct, '_assesed_allele')]] != b_combined_top_and_lcl_caqtl[['lcl_assesed_allele']], 'lcl_zscore_signed'] <- -1 *     b_combined_top_and_lcl_caqtl[b_combined_top_and_lcl_caqtl[[paste0(ct, '_assesed_allele')]] != b_combined_top_and_lcl_caqtl[['lcl_assesed_allele']], 'lcl_zscore']
    # put in the list
    lcl_per_ct[[paste('lcl', 'vs', ct, sep = '_')]] <- b_combined_top_and_lcl_caqtl
  }
  return(lcl_per_ct)
}


```

```{r acat_setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# this is taken from https://github.com/yaowuliu/ACAT/blob/master/R/ACAT.R

#'
#' Aggregated Cauchy Assocaition Test
#'
#' A p-value combination method using the Cauchy distribution.
#'
#'
#'
#' @param weights a numeric vector/matrix of non-negative weights for the combined p-values. When it is NULL, the equal weights are used.
#' @param Pvals a numeric vector/matrix of p-values. When it is a matrix, each column of p-values is combined by ACAT.
#' @param is.check logical. Should the validity of \emph{Pvals} (and \emph{weights}) be checked? When the size of \emph{Pvals} is large and one knows \emph{Pvals} is valid, then the checking part can be skipped to save memory.
#' @return The p-value(s) of ACAT.
#' @author Yaowu Liu
#' @examples p.values<-c(2e-02,4e-04,0.2,0.1,0.8);ACAT(Pvals=p.values)
#' @examples ACAT(matrix(runif(1000),ncol=10))
#' @references Liu, Y., & Xie, J. (2019). Cauchy combination test: a powerful test with analytic p-value calculation
#' under arbitrary dependency structures. \emph{Journal of American Statistical Association},115(529), 393-402. (\href{https://amstat.tandfonline.com/doi/abs/10.1080/01621459.2018.1554485}{pub})
#' @export
ACAT<-function(Pvals,weights=NULL,is.check=TRUE){
    Pvals<-as.matrix(Pvals)
    if (is.check){
        #### check if there is NA
        if (sum(is.na(Pvals))>0){
            stop("Cannot have NAs in the p-values!")
        }
        #### check if Pvals are between 0 and 1
        if ((sum(Pvals<0)+sum(Pvals>1))>0){
            stop("P-values must be between 0 and 1!")
        }
        #### check if there are pvals that are either exactly 0 or 1.
        is.zero<-(colSums(Pvals==0)>=1)
        is.one<-(colSums(Pvals==1)>=1)
        if (sum((is.zero+is.one)==2)>0){
            stop("Cannot have both 0 and 1 p-values in the same column!")
        }

        if (sum(is.zero)>0){
            warning("There are p-values that are exactly 0!")
        }
        if (sum(is.one)>0){
            warning("There are p-values that are exactly 1!")
        }

    }
    #### Default: equal weights. If not, check the validity of the user supplied weights and standadize them.
    if (is.null(weights)){
        is.weights.null<-TRUE
    }else{
        is.weights.null<-FALSE
        weights<-as.matrix(weights)
        if (sum(dim(weights)!=dim(Pvals))>0){
            stop("The dimensions of weights and Pvals must be the same!")
        }else if (is.check & (sum(weights<0)>0)){
            stop("All the weights must be nonnegative!")
        }else{
            w.sum<-colSums(weights)
            if (sum(w.sum<=0)>0){
                stop("At least one weight should be positive in each column!")
            }else{
                for (j in 1:ncol(weights)){
                    weights[,j]<-weights[,j]/w.sum[j]
                }
            }
        }

    }

    #### check if there are very small non-zero p values and calcuate the cauchy statistics
    is.small<-(Pvals<1e-15)
    if (is.weights.null){
         Pvals[!is.small]<-tan((0.5-Pvals[!is.small])*pi)
         Pvals[is.small]<-1/Pvals[is.small]/pi
         cct.stat<-colMeans(Pvals)
    }else{
         Pvals[!is.small]<-weights[!is.small]*tan((0.5-Pvals[!is.small])*pi)
         Pvals[is.small]<-(weights[is.small]/Pvals[is.small])/pi
         cct.stat<-colSums(Pvals)
    }
    #### return the ACAT p value(s).
    pval<-pcauchy(cct.stat,lower.tail = F)
    return(pval)
}

#'
#' A set-based test that uses ACAT to combine the variant-level p-values.
#'
#'
#' @param G a numeric matrix or dgCMatrix with each row as a different individual and each column as a separate gene/snp. Each genotype should be coded as 0, 1, 2.
#' @param obj an output object of the \code{\link{NULL_Model}} function.
#' @param weights.beta a numeric vector of parameters for the beta weights for the weighted kernels. If you want to use your own weights, please use the “weights” parameter. It will be ignored if “weights” parameter is not null.
#' @param weights a numeric vector of weights for the SNP p-values. When it is NULL, the beta weight with the “weights.beta” parameter is used.
#' @param mac.thresh a threshold of the minor allele count (MAC). The Burden test will be used to aggregate the SNPs with MAC less than this thrshold.
#' @return The p-value of ACAT-V.
#' @details The Burden test is first used to aggregate very rare variants with Minor Allele Count (MAC) < \emph{mac.thresh} (e.g., 10), and a Burden p-value is obtained. For each of the variants with MAC >= \emph{mac.thresh}, a variant-level p-value is calculated. Then, ACAT is used to combine the variant-level p-values and the Burden test p-value of very rare variants.
#'
#' If \emph{weights.beta} is used, then the weight for the Burden test p-value is demetermined by the average Minor Allele Frequency (MAF) of the variants with MAC < \emph{mac.thresh}; if the user-specified \emph{weights} is used, then the weight for the Burden test p-value is the average of \emph{weights} of the variants with MAC < \emph{mac.thresh}.
#'
#' Note that the \emph{weights} here are for the SNP p-vlaues. In SKAT, the weights are for the SNP score test statistics. To transfrom the SKAT weights to the \emph{weights} here, one can use the formula that \emph{weights} = (skat_weights)^2*MAF*(1-MAF).
#'
#' @author Yaowu Liu
#' @references Liu, Y., et al. (2019). ACAT: A fast and powerful p value combination
#' method for rare-variant analysis in sequencing studies.
#' \emph{American Journal of Humann Genetics 104}(3), 410-421.
#' (\href{https://www.sciencedirect.com/science/article/pii/S0002929719300023}{pub})
#' @examples  library(Matrix)
#' @examples  data(Geno)
#' @examples  G<-Geno[,1:100] # Geno is a dgCMatrix of genotypes
#' @examples  Y<-rnorm(nrow(G)); Z<-matrix(rnorm(nrow(G)*4),ncol=4)
#' @examples  obj<-NULL_Model(Y,Z)
#' @examples  ACAT_V(G,obj)
#' @export
ACAT_V<-function(G,obj,weights.beta=c(1,25),weights=NULL,mac.thresh=10){
    ### check weights
    if (!is.null(weights) && length(weights)!=ncol(G)){
        stop("The length of weights must equal to the number of variants!")
    }

    mac<-Matrix::colSums(G)
    ### remove SNPs with mac=0
    if (sum(mac==0)>0){
        G<-G[,mac>0,drop=FALSE]
        weights<-weights[mac>0]
        mac<-mac[mac>0]
        if (length(mac)==0){
            stop("The genotype matrix do not have non-zero element!")
        }
    }
    ### p and n
    p<-length(mac)
    n<-nrow(G)
    ###

    if (sum(mac>mac.thresh)==0){  ## only Burden
        pval<-Burden(G,obj, weights.beta = weights.beta, weights = weights)
    }else if (sum(mac<=mac.thresh)==0){ ## only cauchy method
        if (is.null(weights)){
            MAF<-mac/(2*n)
            W<-(dbeta(MAF,weights.beta[1],weights.beta[2])/dbeta(MAF,0.5,0.5))^2
        }else{
            W<-weights
        }

        Mpvals<-Get.marginal.pval(G,obj)
        pval<-ACAT(Mpvals,W)
    }else{  ## Burden + Cauchy method
        is.very.rare<-mac<=mac.thresh
        weights.sparse<-weights[is.very.rare]
        weights.dense<-weights[!is.very.rare]
        pval.dense<-Burden(G[,is.very.rare,drop=FALSE],obj, weights.beta = weights.beta, weights = weights.sparse)

        Mpvals<-Get.marginal.pval(G[,!is.very.rare,drop=FALSE],obj)

        Mpvals<-c(Mpvals,pval.dense)
        if (is.null(weights)){
            MAF<-mac/(2*n)
            mafs<-c(MAF[!is.very.rare],mean(MAF[is.very.rare])) ## maf for p-values
            W<-(dbeta(mafs,weights.beta[1],weights.beta[2])/dbeta(mafs,0.5,0.5))^2
        }else{
            W<-c(weights.dense,mean(weights.sparse))
        }


        is.keep<-rep(T,length(Mpvals))
        is.keep[which(Mpvals==1)]<-F  ## remove p-values of 1.
        pval<-ACAT(Mpvals[is.keep],W[is.keep])
    }
    return(pval)
}

#'
#'
#' Get parameters and residuals from the NULL model
#'
#' Compute model parameters and residuals for ACAT-V
#'
#'
#' @param Y a numeric vector of outcome phenotypes.
#' @param Z a numeric matrix of covariates. Z must be full-rank. Do not include intercept in Z. The intercept will be added automatically.
#' @return This function returns an object that has model parameters and residuals of the NULL model of no association between genetic variables and outcome phenotypes. After obtaining it, please use \code{\link{ACAT_V}} function to conduct the association test.
#' @details \emph{Y} could only be continuous or binary. If \emph{Y} is continuous, a linear regression model is fitted. If \emph{Y} is binary, it must be coded as 0,1 and a logistic model is fitted.
#' @author Yaowu Liu
#' @examples  Y<-rnorm(10000)
#' @examples  Z<-matrix(rnorm(10000*4),ncol=4)
#' @examples  obj<-NULL_Model(Y,Z)
#' @export
NULL_Model<-function(Y,Z=NULL){
    n<-length(Y)
    #### check the type of Y
    if ((sum(Y==0)+sum(Y==1))==n){
        out_type<-"D"
    }else{
        out_type<-"C"
    }
    #### Add intercept
    Z.tilde<-cbind(rep(1,length(Y)),Z)
    if (out_type=="C"){
        #### estimate of sigma square
        Z.med<-Z.tilde%*%solve(chol(t(Z.tilde)%*%Z.tilde))   ## Z.med%*%t(Z.med) is the projection matrix of Z.tilde
        Y.res<-as.vector(Y-(Y%*%Z.med)%*%t(Z.med))
        sigma2<-sum(Y.res^2)/(n-ncol(Z.med))
        #### output
        res<-list()
        res[["out_type"]]<-out_type
        res[["Z.med"]]<-Z.med
        res[["Y.res"]]<-Y.res
        res[["sigma2"]]<-sigma2
    }else if (out_type=="D"){
        #### fit null model
        g<-glm(Y~0+Z.tilde,family = "binomial")
        prob.est<-g[["fitted.values"]]
        #### unstandarized residuals
        Y.res<-(Y-prob.est)
        ### Sigma when rho=0
        sigma2.Y<-prob.est*(1-prob.est)  ### variance of each Y_i
        ### output
        res<-list()
        res[["out_type"]]<-out_type
        res[["Z.tilde"]]<-Z.tilde
        res[["Y.res"]]<-Y.res
        res[["sigma2.Y"]]<-sigma2.Y
    }
    return(res)
}




Get.marginal.pval<-function(G,obj){
    ### check obj
    if (names(obj)[1]!="out_type"){
        stop("obj is not calculated from MOAT_NULL_MODEL!")
    }else{
        out_type<-obj[["out_type"]]
        if (out_type=="C"){
            if (!all.equal(names(obj)[2:length(obj)],c("Z.med","Y.res","sigma2"))){
                stop("obj is not calculated from MOAT_NULL_MODEL!")
            }else{
                Z.med<-obj[["Z.med"]]
                Y.res<-obj[["Y.res"]]
                n<-length(Y.res)
                SST<-obj[["sigma2"]]*(n-ncol(Z.med))
            }
        }else if (out_type=="D"){
            if (!all.equal(names(obj)[2:length(obj)],c("Z.tilde","Y.res","sigma2.Y"))){
                stop("obj is not calculated from MOAT_NULL_MODEL!")
            }else{
                Z.tilde<-obj[["Z.tilde"]]
                Y.res<-obj[["Y.res"]]
                sigma2.Y<-obj[["sigma2.Y"]]
                n<-length(Y.res)
            }
        }
    }

    if (class(G)!="matrix" && class(G)!="dgCMatrix"){
        stop("The class of G must be matrix or dgCMatrix!")
    }

    if (out_type=="C"){
        G_tX.med<-as.matrix(Matrix::crossprod(Z.med,G))
        ### Sigma^2 of G
        Sigma2.G<-Matrix::colSums(G^2)-Matrix::colSums(G_tX.med^2)
        SSR<-as.vector((Y.res%*%G)^2/Sigma2.G)
        SSR[Sigma2.G<=0]<-0
        df.2<-n-1-ncol(Z.med)
        t.stat<-suppressWarnings(sqrt(SSR/((SST-SSR)/df.2)))
        marginal.pvals<-2*pt(t.stat,(n-1-ncol(Z.med)),lower.tail = FALSE)
    }else if (out_type=="D"){
        Z.stat0<-as.vector(Y.res%*%G)
        ### Sigma when rho=0
        tG_X.tilde_sigma2<-as.matrix(Matrix::crossprod(G,Z.tilde*sigma2.Y))
        Sigma2.G<-Matrix::colSums(G^2*sigma2.Y)-diag(tG_X.tilde_sigma2%*%solve(t(Z.tilde)%*%(Z.tilde*sigma2.Y))%*%t(tG_X.tilde_sigma2))
        marginal.pvals<-2*pnorm(abs(Z.stat0)/sqrt(Sigma2.G),lower.tail = FALSE)
    }

    return(marginal.pvals)
}


Burden<-function(G,obj,kernel="linear.weighted",weights.beta=c(1,25),weights=NULL){
    ### check obj
    if (names(obj)[1]!="out_type"){
        stop("obj is not calculated from NULL_MODEL!")
    }else{
        out_type<-obj[["out_type"]]
        if (out_type=="C"){
            if (!all.equal(names(obj)[2:length(obj)],c("Z.med","Y.res","sigma2"))){
                stop("obj is not calculated from NULL_MODEL!")
            }else{
                Z.med<-obj[["Z.med"]]
                Y.res<-obj[["Y.res"]]/sqrt(obj[["sigma2"]])  ## rescaled residules
                n<-length(Y.res)
            }
        }else if (out_type=="D"){
            if (!all.equal(names(obj)[2:length(obj)],c("Z.tilde","Y.res","sigma2.Y"))){
                stop("obj is not calculated from NULL_MODEL!")
            }else{
                Z.tilde<-obj[["Z.tilde"]]
                Y.res<-obj[["Y.res"]]
                sigma2.Y<-obj[["sigma2.Y"]]
                n<-length(Y.res)
            }
        }
    }
    ### MAF
    MAF<-Matrix::colSums(G)/(2*dim(G)[1])
    p<-length(MAF)
    #### weights
    if (kernel=="linear.weighted"){
        if (is.null(weights)){
            W<-dbeta(MAF,weights.beta[1],weights.beta[2])
        }else{
            if (length(weights)==p){
                W<-weights
            }else{
                stop("The length of weights must equal to the number of variants!")
            }
        }

    }else if (kernel=="linear"){
        W<-rep(1,p)
    }else{
        stop("The kernel name is not valid!")
    }

    ###### if G is sparse or not
    if (class(G)=="matrix" || class(G)=="dgCMatrix"){
        if (out_type=="C"){
            Z.stat.sum<-as.vector((Y.res%*%G)%*%W)
            Gw<-G%*%W
            sigma.z<-sqrt(sum(Gw^2)-sum((t(Z.med)%*%(Gw))^2))
        }else if (out_type=="D"){
            Z.stat.sum<-as.vector((Y.res%*%G)%*%W)
            Gw<-as.vector(G%*%W)
            sigma.z<-sum(Gw^2*sigma2.Y)-((Gw*sigma2.Y)%*%Z.tilde)%*%solve(t(Z.tilde)%*%(Z.tilde*sigma2.Y))%*%t((Gw*sigma2.Y)%*%Z.tilde)
            sigma.z<-as.vector(sqrt(sigma.z))
        }
    }else{
        stop("The class of G must be matrix or dgCMatrix!")
    }

    V<-Z.stat.sum/sigma.z
    Q<-V^2   ## Q test statistic
    pval<-1-pchisq(Q,df=1)
    return(pval)
}

```

```{r path_setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

####################
# Main Code        #
####################

# location of caQTL
caqtl_output_combined_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/caqtl/sc-eqtlgen/output/L1/combined/'

```

```{r get_lcl_combined_overlap_opposite, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# location of the LCL caQTLs
lcl_caqtl_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/caqtl/replication//lcl/'

# we'll read the LCL ocombinedpcombined per chromosome, so we'll store that in a list first
lcl_per_chromosome <- list()
b_per_chromosome <- list()
# we'll check each chromosome
for (chromosome in 1:22) {
  # progress
  message(paste('doing chromosome', chromosome))
  # paste together the paths
  lcl_chromosome_loc <- paste0(lcl_caqtl_loc, '/qtl_results_all_qval_', chromosome, '.txt.gz')
  b_chromosome_loc <- paste0(caqtl_output_combined_loc, '/B/', '/qtl_results_all_qval_', chromosome, '.txt.gz')
  # read this ocombinedpcombined
  lcl_chromosome <- fread(lcl_chromosome_loc, header = T, sep = '\t')
  b_chromosome <- fread(b_chromosome_loc, header = T, sep = '\t')
  # add the QTL explicitly
  b_chromosome[['qtl']] <- paste0(b_chromosome[['feature_id']], '_', b_chromosome[['snp_chromosome']], ':', b_chromosome[['snp_position']])
  # add the Zscore
  b_chromosome[['zscore']] <- b_chromosome[['beta']] / b_chromosome[['beta_se']]
  # get the positions, we need them later
  b_combined_caqtl_significant_chromosome_positions <- unique(b_chromosome[, c('feature_id', 'feature_start', 'feature_end')])
  # let's reduce the data to what is strictly necessary
  b_chromosome <- b_chromosome[, c('qtl', 'feature_id', 'zscore', 'assessed_allele', 'beta', 'beta_se', 'p_value')]
  # and rename columns so they don't conflict with the lcl data
  colnames(b_chromosome) <- c('qtl', 'feature_id', 'mo_zscore', 'mo_assesed_allele', 'mo_beta', 'mo_se', 'mo_p')
  # put in the b list
  b_per_chromosome[[paste0('chr', chromosome)]] <- b_chromosome

  # harmonize region name
  lcl_chromosome[['feature_id']] <- paste('chr', gsub(':', '-', lcl_chromosome[['feature_id']]), sep = '')
  # get the cauchy p value
  message(paste('adding cauchy p values for chromosome', chromosome))
  # we need to add the acat p values for each feature first
  # lcl_acat_corrected_l <- list()
  # # check each feature
  # for (feature in unique(lcl_chromosome[['feature_id']])) {
  #   # subset to that feature
  #   lcl_feature <- lcl_chromosome[
  #       !is.na(lcl_chromosome[['feature_id']]) & 
  #       lcl_chromosome[['feature_id']] == feature, 
  #   ]
  #   # take the number of variants
  #   nvariants <- nrow(lcl_feature)
  #   # replace the zeroes with the smallest value possible
  #   lcl_feature[['lcl_p_safe']] <- lcl_feature[['p_value']]
  #   if (nrow(lcl_feature[lcl_feature[['p_value']] == 0, ] > 0)) {
  #     lcl_feature[lcl_feature[['p_value']] == 0, ][['lcl_p_safe']] <- .Machine$double.xmin
  #   }
  #   # and replace the 1 values as suggested
  #   if (nrow(lcl_feature[lcl_feature[['p_value']] == 1, ]) > 0) {
  #     lcl_feature[lcl_feature[['p_value']] == 1, ][['lcl_p_safe']] <- 1-1/nvariants
  #   }
  #   # get the cauchy p value
  #   lcl_feature[['lcl_p_caucy']] <- ACAT(lcl_feature[['lcl_p_safe']])
  #   # put in the list
  #   lcl_acat_corrected_l[[feature]] <- lcl_feature
  # }
  # library(foreach)
  # library(doParallel)
  # 
  # # setup parallel backend to use multiple CPUs
  # cores=8
  # cl <- makeCluster(cores)
  # registerDoParallel(cl)
  # # get the unique features
  # unique_features <- unique(lcl_chromosome[['feature_id']])
  # # do a parallel run
  # lcl_acat_corrected_l = foreach(i=1:length(unique_features)) %dopar%  {
  #   # get the feature
  #   feature <- unique_features[i]
  #   # subset to that feature
  #   lcl_feature <- lcl_chromosome[
  #       !is.na(lcl_chromosome[['feature_id']]) &
  #       lcl_chromosome[['feature_id']] == feature,
  #   ]
  #   # # take the number of variants
  #   # nvariants <- nrow(lcl_feature)
  #   # # replace the zeroes with the smallest value possible
  #   # lcl_feature[['lcl_p_safe']] <- lcl_feature[['p_value']]
  #   # if (nrow(lcl_feature[lcl_feature[['p_value']] == 0, ] > 0)) {
  #   #   lcl_feature[lcl_feature[['p_value']] == 0, ][['lcl_p_safe']] <- .Machine$double.xmin
  #   # }
  #   # # and replace the 1 values as suggested
  #   # if (nrow(lcl_feature[lcl_feature[['p_value']] == 1, ]) > 0) {
  #   #   lcl_feature[lcl_feature[['p_value']] == 1, ][['lcl_p_safe']] <- 1-1/nvariants
  #   # }
  #   # lcl_feature[['lcl_p_caucy']] <- ACAT(lcl_feature[['lcl_p_safe']])
  #   lcl_feature[['lcl_p_caucy']] <- cauchyR::cauchy(lcl_feature[['p_value']])
  #   return(lcl_feature)
  # }
  # merge all the cauchy lcl outputs
  # lcl_acat_corrected <- do.call('rbind', lcl_acat_corrected_l)
  # # fix the column names
  # colnames(lcl_acat_corrected) <- gsub('^chr\\d+\\.', '', colnames(lcl_acat_corrected))
  # # overwrite original
  # lcl_chromosome <- lcl_acat_corrected

  # get only positions for this chromosome
  lcl_chromosome_positions <- unique(lcl_chromosome[, c('feature_id', 'feature_start', 'feature_end')])
  # get the ranges
  lcl_chromosome_iranges <- IRanges(start = lcl_chromosome_positions[['feature_start']], end = lcl_chromosome_positions[['feature_end']])
  # and make those iranges
  b_combined_caqtl_significant_chromosome_iranges <- IRanges(b_combined_caqtl_significant_chromosome_positions[['feature_start']], end = b_combined_caqtl_significant_chromosome_positions[['feature_end']])
  # find overlaps
  feature_chromosome_overlaps <- findOverlaps(b_combined_caqtl_significant_chromosome_iranges, lcl_chromosome_iranges)
  # extract overlapping ranges
  overlapping_ranges <- pintersect(lcl_chromosome_iranges[subjectHits(feature_chromosome_overlaps)], b_combined_caqtl_significant_chromosome_iranges[queryHits(feature_chromosome_overlaps)])
  # create a  table for the overlaps
  overlaps_table <- data.table(
    'feature_id' = lcl_chromosome_positions[['feature_id']][subjectHits(feature_chromosome_overlaps)],
    'overlap_start' = start(overlapping_ranges),
    'overlap_end' = end(overlapping_ranges)
  )
  # add these positions
  lcl_chromosome <- merge(lcl_chromosome, overlaps_table, by = 'feature_id', all.x = T, allow.cartesian=TRUE)
  # remove the ones we cannot remap
  lcl_chromosome <- lcl_chromosome[!is.na(lcl_chromosome[['overlap_start']]), ]
  # # add the qtl column
  lcl_chromosome[['qtl']] <- paste0('chr', lcl_chromosome[['feature_chromosome']], '-', lcl_chromosome[['overlap_start']], '-', lcl_chromosome[['overlap_end']], '_', lcl_chromosome[['snp_chromosome']], ':', lcl_chromosome[['snp_position']])
  # calculate the Z
  lcl_chromosome[['zscore']] <- lcl_chromosome[['beta']] / lcl_chromosome[['beta_se']]
  # order by that z
  lcl_chromosome <- lcl_chromosome[order(abs(lcl_chromosome[['zscore']]), decreasing = T), ]
  # if there were multiple overlapping ranges, keep the most significant one
  lcl_chromosome <- lcl_chromosome[!duplicated(lcl_chromosome[['qtl']]), ]
  # # subset to the column we want
  # lcl_chromosome <- lcl_chromosome[, c('qtl', 'feature_id', 'zscore', 'assessed_allele', 'beta', 'beta_se', 'p_value', 'lcl_p_caucy')]
  # # and rename columns so they don't conflict with the lcl data
  # colnames(lcl_chromosome) <- c('qtl', 'feature_id', 'lcl_zscore', 'lcl_assesed_allele', 'lcl_beta', 'lcl_se', 'lcl_p', 'lcl_p_caucy')
  # subset to the column we want
  lcl_chromosome <- lcl_chromosome[, c('qtl', 'feature_id', 'zscore', 'assessed_allele', 'beta', 'beta_se', 'p_value')]
  # and rename columns so they don't conflict with the lcl data
  colnames(lcl_chromosome) <- c('qtl', 'feature_id', 'lcl_zscore', 'lcl_assesed_allele', 'lcl_beta', 'lcl_se', 'lcl_p')
  # # and pcombined in the list
  # lcl_per_chromosome[[paste0('chr', chromosome)]] <- lcl_chromosome
  # # save in the meantime as well
  # write.table(lcl_chromosome, gzfile(paste0('~/tables/mo_lcl_cauchy_chr', chromosome, '.tsv.gz')), sep = '\t', row.names = F, col.names = T)
}
# merge all the lcl chromosomes
lcl_caqtls <- do.call('rbind', lcl_per_chromosome)
b_caqtls <- do.call('rbind', b_per_chromosome)

# add B&H
lcl_caqtls[['lcl_bh']] <- p.adjust(lcl_caqtls[['lcl_p']], method = 'BH')

```

```{r get_lcl_combined_overlap_opposite_acat, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# # add a cauchy q value
# lcl_acat_qs <- unique(lcl_acat_corrected[, c('feature_id', 'lcl_p_caucy')])
# lcl_acat_qs[['lcl_q_cauchy']] <- qvalue(lcl_acat_corrected[['lcl_p_caucy']])$qvalues
# # add the caucy qvalue
# lcl_caqtls[['lcl_q_cauchy']] <- lcl_acat_qs[match(lcl_acat_corrected[['feature_id']], lcl_acat_qs[['feature_id']]), ][['lcl_q_cauchy']]

# now merge the two tables
b_combined_and_lcl_caqtl <- merge(x = b_caqtls, y = lcl_caqtls, by = 'qtl')
# and flip the z score if in the opposite direction
b_combined_and_lcl_caqtl[['lcl_zscore_signed']] <- b_combined_and_lcl_caqtl[['lcl_zscore']]
b_combined_and_lcl_caqtl[b_combined_and_lcl_caqtl[['mo_assesed_allele']] != b_combined_and_lcl_caqtl[['lcl_assesed_allele']], 'lcl_zscore_signed'] <- -1 * b_combined_and_lcl_caqtl[b_combined_and_lcl_caqtl[['mo_assesed_allele']] != b_combined_and_lcl_caqtl[['lcl_assesed_allele']], 'lcl_zscore']

```

```{r save_lcl_combined_overlap, include=TRUE, fig.width=5, fig.height=5}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# where to save
lcl_to_b_overlap_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/caqtl/replication/lcl/mo_matched_caqtl_lcl_vs_b.tsv.gz'
# save the file
write.table(b_combined_and_lcl_caqtl, gzfile(lcl_to_b_overlap_loc), row.names = F, col.names = T, sep = '\t', quote = F)

# just the b caqtls as well
lcl_all_caqtls_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/caqtl/replication/lcl/mo_lcl_caqtls_all.tsv.gz'
write.table(b_caqtls, gzfile(lcl_all_caqtls_loc), row.names = F, col.names = T, sep = '\t', quote = F)

```

```{r get_lcl_combined_overlap_opposite_top, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# now filter by the significant effects
b_combined_and_lcl_caqtl_sig_lcl <- b_combined_and_lcl_caqtl[
  b_combined_and_lcl_caqtl[['lcl_bh']] < 0.05, 
]
# then order by effect size
b_combined_and_lcl_caqtl_top_lcl <- b_combined_and_lcl_caqtl_sig_lcl[
  order(abs(b_combined_and_lcl_caqtl_sig_lcl[['lcl_zscore_signed']]), decreasing = T), 
  
]
# the keep the top effects
b_combined_and_lcl_caqtl_top_lcl <- b_combined_and_lcl_caqtl_top_lcl[
  !duplicated(b_combined_and_lcl_caqtl_top_lcl[['feature_id.y']]), 
  
]
# then do MTC on the caQTL output, replicating only significant effects
b_combined_and_lcl_caqtl_top_lcl[['mo_rep_bh']] <- p.adjust(b_combined_and_lcl_caqtl_top_lcl[['mo_p']], method = 'BH')

```

```{r save_lcl_combined_overlap_fdr, include=TRUE, fig.width=5, fig.height=5}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# write just the significant ones as well
b_caqtls_sig <- b_caqtls[
  b_caqtls[['lcl_bh']] < 0.05, 
]
lcl_bh005_caqtls_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/caqtl/replication/lcl/mo_lcl_caqtls_bh005.tsv.gz'
write.table(b_caqtls_sig, gzfile(lcl_bh005_caqtls_loc), row.names = F, col.names = T, sep = '\t', quote = F)

```

```{r plot_lcl_combined_overlap, include=TRUE, fig.width=5, fig.height=5}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)


# and use that for significance of the LCL caQTLs
b_combined_and_lcl_caqtl_top_lcl[['lcl_significant']] <- b_combined_and_lcl_caqtl_top_lcl[['lcl_bh']] < 0.05
b_combined_and_lcl_caqtl_top_lcl[['mo_rep_significant']] <- b_combined_and_lcl_caqtl_top_lcl[['mo_rep_bh']] < 0.05

# keep only what is significant
b_combined_and_lcl_caqtl_top_lcl_plot <- b_combined_and_lcl_caqtl_top_lcl[
  b_combined_and_lcl_caqtl_top_lcl[['lcl_significant']] == T &
  b_combined_and_lcl_caqtl_top_lcl[['mo_rep_significant']] == T, ]

# get the minimal significant z for lcl
min_sig_z_lcl <- min(abs(b_combined_and_lcl_caqtl_top_lcl_plot[b_combined_and_lcl_caqtl_top_lcl_plot[['lcl_significant']] == T, 'lcl_zscore_signed']))
min_sig_z_mo <- min(abs(b_combined_and_lcl_caqtl_top_lcl_plot[b_combined_and_lcl_caqtl_top_lcl_plot[['mo_rep_significant']] == T, 'mo_zscore']))
# and the max z
max_sig_z_lcl <- max(abs(b_combined_and_lcl_caqtl_top_lcl_plot[b_combined_and_lcl_caqtl_top_lcl_plot[['lcl_significant']] == T, 'lcl_zscore_signed']))
max_sig_z_mo <- max(abs(b_combined_and_lcl_caqtl_top_lcl_plot[b_combined_and_lcl_caqtl_top_lcl_plot[['mo_rep_significant']] == T, 'mo_zscore']))

# calculate concordance
n_significant_both <- sum(b_combined_and_lcl_caqtl_top_lcl_plot[['lcl_significant']] == T & b_combined_and_lcl_caqtl_top_lcl_plot[['mo_rep_significant']] == T)
n_significant_directed_both <- sum(b_combined_and_lcl_caqtl_top_lcl_plot[['lcl_significant']] == T & b_combined_and_lcl_caqtl_top_lcl_plot[['mo_rep_significant']] == T &
                                     sign(b_combined_and_lcl_caqtl_top_lcl_plot[['lcl_zscore_signed']]) == sign(b_combined_and_lcl_caqtl_top_lcl_plot[['mo_zscore']]))
concordance <- round(n_significant_directed_both / n_significant_both, digits = 3)

# plot the concordance of the two
p <- ggplot(data = b_combined_and_lcl_caqtl_top_lcl_plot, mapping = aes(x = lcl_zscore_signed, y = mo_zscore)) + 
  geom_point(size = 0.2) + 
  xlim(c(max_sig_z_lcl * -1, max_sig_z_lcl * 1)) +
  ylim(c(max_sig_z_mo * -1, max_sig_z_mo * 1)) + 
  # left to right block of non-significant effects
  geom_rect(aes(xmin = -1 * max_sig_z_lcl, xmax = max_sig_z_lcl, ymin = -1 * min_sig_z_mo, ymax = min_sig_z_mo), 
            fill = "white", alpha = 0.005) +
  # bottom to top block of non-significant effects
  geom_rect(aes(xmin = -1 * min_sig_z_lcl, xmax = min_sig_z_lcl, ymin = -1 * max_sig_z_mo, ymax = max_sig_z_mo), 
            fill = "white", alpha = 0.005) +
  # bottom left block
  geom_rect(aes(xmin = -1 * max_sig_z_lcl, xmax = -1 *min_sig_z_lcl, ymin = -1 * max_sig_z_mo, ymax = -1 * min_sig_z_mo), 
            fill = "#0072B2", alpha = 0.01) +
  # bottom right block
  geom_rect(aes(xmin = min_sig_z_lcl, xmax = max_sig_z_lcl, ymin = -1 * max_sig_z_mo, ymax = -1 * min_sig_z_mo), 
            fill = "#D55E00", alpha = 0.01) +
  # top left block
  geom_rect(aes(xmin = -1 * max_sig_z_lcl, xmax = -1 *min_sig_z_lcl, ymin = min_sig_z_mo, ymax = max_sig_z_mo), 
            fill = "#D55E00", alpha = 0.01) + 
  # top right block
  geom_rect(aes(xmin = min_sig_z_lcl, xmax = max_sig_z_lcl, ymin = max_sig_z_mo, ymax = min_sig_z_mo), 
            fill = "#0072B2", alpha = 0.01) + 
  # labels for x and y axis
  xlab('Z-score in LCL caQTLs') +
  ylab('Z-score in multi-omics caQTLs') +
  # vertical negative z ccombinedoff line
  geom_vline(xintercept=c(-1 *min_sig_z_lcl), color="black", size=0.5, linetype = "dashed") +
	# horizonal negative z ccombinedoff line
  geom_hline(yintercept=c(-1 *min_sig_z_mo), color="black", size=0.5, linetype="dashed") +
  # vertical positive z ccombinedoff line
  geom_vline(xintercept=c(min_sig_z_lcl), color="black", size=0.5, linetype = "dashed") +
	# horizonal positive z ccombinedoff line
  geom_hline(yintercept=c(min_sig_z_mo), color="black", size=0.5, linetype="dashed") +
  # make backgrounds white
  theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) + 
  # add the concordance
  annotate("label", x = max_sig_z_lcl * 0.75 , y = max_sig_z_mo * -0.75, label = paste('concordance', concordance, sep = ':\n')) +
  # add the names of the concordant and non-concordant blocks
  annotate("text", x = max_sig_z_lcl * -0.70 , y = max_sig_z_mo * 0.75, label = 'discordant', colour = '#D55E00', fontface = 'bold') +
  # add the names of the concordant and non-concordant blocks
  annotate("text", x = max_sig_z_lcl * 0.70 , y = max_sig_z_mo * 0.75, label = 'concordant', colour = '#0072B2', fontface = 'bold') +
  # add the title
  ggtitle('Concordance of caQTL effects between LCL\nand multi-omics B cells')
p

# save this plot
ggsave('~/plots/mo_scatter_mo_b_combined_vs_lcl_caqtl.pdf', width=5, height=5)

```

```{r get_lcl_combined_overlap, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# get overlap per ct
combined_caqtl_to_lcl <- match_lcl_to_caqtls(lcl_caqtl_loc, caqtl_output_combined_loc)

```

```{r ave_lcl_combined_overlap, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# get overlap per ct
combined_caqtl_to_lcl_loc <- '~/tables/lcl_mo_caqtl_overlap.rds'
saveRDS(combined_caqtl_to_lcl, combined_caqtl_to_lcl_loc)

```

```{r reformat_lcl_combined_overlap, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# save in a new list
combined_caqtl_to_lcl_refdr <- list()
# check each cell type
for (comp in names(combined_caqtl_to_lcl)) {
  # extract the cell type from the name (lcl_vs_b for example)
  ct <- strsplit(comp, '_vs_')[[1]][2]
  # extract the table
  ct_table <- combined_caqtl_to_lcl[[comp]]
  # subset to what is significant in LCL
  ct_table <- ct_table[
    ct_table[['lcl_bh']] < 0.05, 
  ]
  # then order by effect size
  ct_table <- ct_table[
    order(abs(ct_table[['lcl_zscore_signed']]), decreasing = T), 
    
  ]
  # the keep the top effects
  ct_table <- ct_table[
    !duplicated(ct_table[['feature_id.y']]), 
    
  ]
  # then do MTC on the caQTL output, replicating only significant effects
  ct_table[[paste0(ct, '_bh')]] <- p.adjust(ct_table[[paste0(ct, '_p')]], method = 'BH')
  # add significance
  ct_table[[paste0(ct, '_significant')]] <- ct_table[[paste0(ct, '_bh')]] < 0.05
  # put that in list
  combined_caqtl_to_lcl_refdr[[comp]] <- ct_table
}

```

```{r lcl_replication_stats, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in caQTLs across cell types
lcl_celltype_stats <- get_stats_qtl_matches(combined_caqtl_to_lcl_refdr, significance_column_replicating_emperical='bh', 
                                  significance_column_replicating_nominal='p',
                                  significance_column_replicating_in_emperical='bh',
                                  significance_column_replicating_in_nominal='p')

```

```{r save_lcl_replication_stats, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# get overlap per ct
lcl_celltype_stats_loc <- '~/tables/mo_lcl_replication_stats.tsv.gz'
write.table(lcl_celltype_stats, gzfile(lcl_celltype_stats_loc), row.names = F, col.names = T, sep = '\t', quote = F)

```

```{r load_lcl_replication_stats, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# get overlap per ct
lcl_celltype_stats_loc <- '~/tables/mo_lcl_replication_stats.tsv.gz'
lcl_celltype_stats <- fread(lcl_celltype_stats_loc, header = T, sep = '\t')

```

```{r plot_lcl_combined_overlap, include=TRUE, fig.width=3, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in caQTLs across cell types
caqtl_lcl_celltype_stat_p_alt <- plot_replication_stats(data.frame('replicating' = rep('lcl', times = 6), 'replicating_in' = c('B', 'CD4T','CD8T', 'DC', 'monocyte', 'NK'), 'rb_emp_all'=c(.61, .54, .50, .43, .38, .46)), mid_value = 0, comparing_value_to_text=list('rb_emp_all' = ''), colour_column = 'rb_emp_all', category_plot_order = c('LCL B', 'B', 'CD4+ T', 'CD8+ T', 'NK', 'DC', 'Monocyte'), text_size = 8, legendless = T, matching_value_to_text=list('n_sig_tested' = '')) +
  xlab('Cell type replicating') +
  ylab('Cell type replicating in') +
  ggtitle('LCL replication') +
  labs(fill="Rb") +
  theme(
    # X label font size
    axis.title.x = element_text(size = 24), 
    # Y label font size
    axis.title.y = element_text(size = 24), 
    # X tick font size
    axis.text.x = element_text(size = 19), 
    # Y tick font size
    axis.text.y = element_text(size = 19), 
    # title size
    title = element_text(size = 28)
  )

# display image
caqtl_lcl_celltype_stat_p_alt
# save the image
ggsave('~/plots/mo_lcl_caqtl_replication_alt.pdf', plot = caqtl_lcl_celltype_stat_p_alt, width = 3, height = 8)

# extract legends as well
caqtl_lcl_celltype_stat_p_alt_legend <- get_legend(plot_replication_stats(data.frame('replicating' = rep('lcl', times = 6), 'replicating_in' = c('B', 'CD4T','CD8T', 'DC', 'monocyte', 'NK'), 'rb_emp_all'=c(.61, .54, .50, .43, .38, .46)), mid_value = 0, comparing_value_to_text=list('rb_emp_all' = ''), colour_column = 'rb_emp_all', category_plot_order = c('LCL B', 'B', 'CD4+ T', 'CD8+ T', 'NK', 'DC', 'Monocyte'), text_size = 8, legendless = F, matching_value_to_text=list('n_sig_tested' = '')) + labs(fill="Rb"))
# and save those
ggsave('~/plots/mo_lcl_caqtl_replication_alt_legend.pdf', plot = caqtl_lcl_celltype_stat_p_alt_legend, width = 1, height = 2)

```
```{r plot_lcl_combined_overlap, include=TRUE, fig.width=3, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# check replication in caQTLs across cell types
caqtl_lcl_celltype_stat_p_alt <- plot_replication_stats(lcl_celltype_stats, mid_value = 0, comparing_value_to_text=list('rb_emp_all' = ''), colour_column = 'rb_emp_all', category_plot_order = c('LCL B', 'B', 'CD4+ T', 'CD8+ T', 'NK', 'DC', 'Monocyte'), text_size = 8, legendless = T, matching_value_to_text=list('n_sig_tested' = '')) +
  xlab('Cell type replicating') +
  ylab('Cell type replicating in') +
  ggtitle('LCL replication') +
  labs(fill="Rb") +
  theme(
    # X label font size
    axis.title.x = element_text(size = 24), 
    # Y label font size
    axis.title.y = element_text(size = 24), 
    # X tick font size
    axis.text.x = element_text(size = 19), 
    # Y tick font size
    axis.text.y = element_text(size = 19), 
    # title size
    title = element_text(size = 28)
  )

# display image
caqtl_lcl_celltype_stat_p_alt
# save the image
ggsave('~/plots/mo_lcl_caqtl_replication_alt.pdf', plot = caqtl_lcl_celltype_stat_p_alt, width = 3, height = 8)

# extract legends as well
caqtl_lcl_celltype_stat_p_alt_legend <- get_legend(plot_replication_stats(lcl_celltype_stats, mid_value = 0, comparing_value_to_text=list('rb_emp_all' = ''), colour_column = 'rb_emp_all', category_plot_order = c('LCL B', 'B', 'CD4+ T', 'CD8+ T', 'NK', 'DC', 'Monocyte'), text_size = 8, legendless = F, matching_value_to_text=list('n_sig_tested' = '')) + labs(fill="Rb"))
# and save those
ggsave('~/plots/mo_lcl_caqtl_replication_alt_legend.pdf', plot = caqtl_lcl_celltype_stat_p_alt_legend, width = 1, height = 2)

```
