---
title: "mo_plot_independent_qtls"
author: "Roy Oelen"
date: "2025-05-20"
output: html_document
---

```{r header, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#!/usr/bin/env Rscript
############################################################################################################################
# Authors: Roy Oelen
# Name: mo_plot_independent_qtls.Rmd
# Function: plot independent QTLs
############################################################################################################################
```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

####################
# libraries        #
####################

library(data.table)
library(ggplot2)
library(cowplot)


```

```{r functions, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# Functions        #
####################

#' get a label dict that replaces the posix safe names into printable versions
#' 
#' @returns a label dict that replaces the posix safe names into printable versions
#' label_dict_names <- get_label_dict()
get_label_dict <- function() {
  label_dict <- list()
  label_dict[['CD4_T_cells']] <- 'CD4+ T cells'
  label_dict[['CD8_T_cells']] <- 'CD8+ T cells'
  label_dict[['CD4T']] <- 'CD4+ T'
  label_dict[['CD8T']] <- 'CD8+ T'
  label_dict[['CD4_T']] <- 'CD4+ T'
  label_dict[['CD8_T']] <- 'CD8+ T'
  label_dict[['Dendritic_cells']] <- 'Dendritic cells'
  label_dict[['Endothelial_cells']] <- 'Endothelial cells'
  label_dict[['Fibroblasts']] <- 'Fibroblasts'
  label_dict[['Glia_cells']] <- 'Glia cells'
  label_dict[['Mast_cells']] <- 'MAST cells'
  label_dict[['Mature_absorptive_enterocytes']] <- 'Mature absorptive enterocytes'
  label_dict[['Mature_secretory_enterocytes']] <- 'Mature secretory enterocytes'
  label_dict[['Memory_B']] <- 'Memory B cells'
  label_dict[['Monocytes']] <- 'Monocytes'
  label_dict[['monocyte']] <- 'Monocyte'
  label_dict[['Mono']] <- 'Monocyte'
  label_dict[['Plasma_cells']] <- 'Plasma cells'
  label_dict[['Stem_cells']] <- 'Stem cells'
  label_dict[['Stromal_cells']] <- 'Stromal cells'
  label_dict[['T_others']] <- 'other T cells'
  label_dict[['Transit_amplifying_cells']] <- 'Transit amplifying cells'
  label_dict[['AI']] <- 'Actively Inflamed'
  label_dict[['NI']] <- 'Non-Inflamed'
  return(label_dict)
}


rename_labels <- function(vector_to_rename) {
  # get the labels that are present
  label_renaming <- get_label_dict()
  # now check which labels we are missing
  missing_renames <- setdiff(unique(vector_to_rename), names(label_renaming))
  # add those renames as not being renames
  for (missing_rename in missing_renames) {
    label_renaming[[missing_rename]] <- missing_rename
  }
  # now replace each value with the rename
  renamed_vector <- as.vector(unlist(label_renaming[vector_to_rename]))
  # and return that
  return(renamed_vector)
}


remap_with_label_dict <- function(vector_of_names) {
  # get the label dict
  relabels <- get_label_dict()
  # get the labels available for renaming
  labels_available <- names(relabels)
  # get the ones we cant remap
  unmappable <- setdiff(unique(vector_of_names), labels_available)
  # report on those
  if (length(unmappable) > 0) {
    print(paste('cannot remap the following names, they will be returned unchanged:', paste(unmappable, collapse = ',')))
    # and put those in our remapping list as their originals
    relabels[unmappable] <- unmappable
  }
  # now actually do the remapping
  remapped <- as.vector(unlist(relabels[vector_of_names]))
  return(remapped)
}


get_color_coding_dict <- function() {
	# medhigh
  color_coding_dict <- list()
  color_coding_dict[["B"]] <- "#71BC4B"
  #color_coding_dict[['CD4_T_cells']] <- '#7FC97F'
  color_coding_dict[['CD4_T_cells']] <- '#153057'
  color_coding_dict[['CD4T']] <- '#153057'
	#color_coding_dict[['CD8_T_cells']] <- '#BEAED4'
	color_coding_dict[['CD8_T_cells']] <- '#009DDB'
	color_coding_dict[['CD8T']] <- '#009DDB'
	#color_coding_dict[['Dendritic_cells']] <- '#FDC086'
	color_coding_dict[['Dendritic_cells']] <- '#965EC8'
	color_coding_dict[['DC']] <- '#965EC8'
	color_coding_dict[['Endothelial_cells']] <- '#FFFFB3'
	color_coding_dict[['Fibroblasts']] <- '#386CB0'
	color_coding_dict[['Glia_cells']] <- '#F0027F'
	color_coding_dict[['Mast_cells']] <- '#BF5B17'
	color_coding_dict[['Mature_absorptive_enterocytes']] <- '#A6CEE3'
	color_coding_dict[['Mature_secretory_enterocytes']] <- '#1B9E77'
	color_coding_dict[['Memory_B']] <- '#D95F02'
	color_coding_dict[['Microfold_cell']] <- '#BEAED4'
	#color_coding_dict[['Monocytes']] <- '#7570B3'
	color_coding_dict[['Monocyte']] <- '#EDBA1B'
	color_coding_dict[['monocyte']] <- '#EDBA1B'
	color_coding_dict[['Naive_B_cells']] <- '#FDC086'
	color_coding_dict[['NK']] <- '#E64B50'
	#color_coding_dict[['Plasma_cells']] <- '#E7298A'
	color_coding_dict[['Plasma_cells']] <- '#DB8E00'
	color_coding_dict[['Stem_cells']] <- '#66A61E'
	color_coding_dict[['Stromal_cells']] <- '#8DD3C7'
	#color_coding_dict[['T_others']] <- '#A6761D'
	color_coding_dict[['T_others']] <- '#FF63B6'
	color_coding_dict[['Transit_amplifying_cells']] <- '#FF7F00'
	color_coding_dict[['disconcordant']] <- 'gray'
  #color_coding_dict[['CD4+ T cells']] <- '#7FC97F'
  color_coding_dict[['CD4+ T cells']] <- '#153057'
  color_coding_dict[['CD4+ T']] <- '#153057'
	#color_coding_dict[['CD8+ T cells']] <- '#BEAED4'
	color_coding_dict[['CD8+ T cells']] <- '#009DDB'
	color_coding_dict[['CD8+ T']] <- '#009DDB'
	#color_coding_dict[['Dendritic cells']] <- '#FDC086'
	color_coding_dict[['Dendritic cells']] <- '#965EC8'
	color_coding_dict[['Endothelial cells']] <- '#FFFFB3'
	color_coding_dict[['Endothelial\ncells']] <- '#FFFFB3'
	color_coding_dict[['Fibroblasts']] <- '#386CB0'
	color_coding_dict[['Glia cells']] <- '#F0027F'
	color_coding_dict[['MAST cells']] <- '#BF5B17'
	color_coding_dict[['Mature absorptive enterocytes']] <- '#A6CEE3'
	color_coding_dict[['Mature\nabsorptive\nenterocytes']] <- '#A6CEE3'
	color_coding_dict[['Mature secretory enterocytes']] <- '#1B9E77'
	color_coding_dict[['Mature secretory\nenterocytes']] <- '#1B9E77'
	color_coding_dict[['Memory B cells']] <- '#D95F02'
	#color_coding_dict[['Monocytes']] <- '#7570B3'
	color_coding_dict[['Microfold cells']] <- '#BEAED4'
	color_coding_dict[['Monocytes']] <- '#EDBA1B'
	color_coding_dict[['Naive B cells']] <- '#FDC086'
	#color_coding_dict[['Plasma cells']] <- '#E7298A'
	color_coding_dict[['Plasma cells']] <- '#DB8E00'
	color_coding_dict[['Stem cells']] <- '#66A61E'
	color_coding_dict[['Stromal cells']] <- '#8DD3C7'
	#color_coding_dict[['other T cells']] <- '#A6761D'
	color_coding_dict[['other T cells']] <- '#FF63B6'
	color_coding_dict[['Transit amplifying cells']] <- '#FF7F00'
	color_coding_dict[['Transit\namplifying cells']] <- '#FF7F00'
	color_coding_dict[['disconcordant']] <- 'gray'
	# up and down regulation will be added to, we need a whitening percentage
	pct_whitening <- 40
	# then we will check each cell type
	for (cell_type in names(color_coding_dict)) {
	  # the up color is the same as the regular one
	  color_coding_dict[[paste(cell_type, 'up')]] <- color_coding_dict[[cell_type]]
	  # but the down one will have a more faded colour
	  color_coding_dict[[paste(cell_type, 'down')]] <- colorRampPalette(c(color_coding_dict[[cell_type]], "white"))(100)[pct_whitening]
	  # we'll do something similiar when we have multiple conditions
	  color_coding_dict[[paste(cell_type, 'combined')]] <- color_coding_dict[[cell_type]]
	  color_coding_dict[[paste(cell_type, 'UT')]] <- colorRampPalette(c(color_coding_dict[[cell_type]], "white"))(100)[pct_whitening]
	  color_coding_dict[[paste(cell_type, '24hCA')]] <- colorRampPalette(c(color_coding_dict[[cell_type]], "black"))(100)[pct_whitening]
	}
	# general
	color_coding_dict[['AI']] <- 'darkblue'
	color_coding_dict[['NI']] <- 'darkred'
	color_coding_dict[['Actively Inflamed']] <- 'darkblue'
	color_coding_dict[['Non-Inflamed']] <- 'darkred'
	return(color_coding_dict)
}


split_string_with_max_length <- function(string, max_length=15) {
  # split the string on the space first
  words <- strsplit(string, ' ')[[1]]
  # and initial pasted string
  final_string <- ''
  # and the temporary string
  tmp_string <- ''
  # check each word
  for (word in words) {
    # get the lenght of the temporary string
    tmp_len <- nchar(tmp_string)
    # get the length of the word
    word_len <- nchar(word)
    # length of the final string
    final_len <- nchar(final_string)
    # check if adding the next word would make us go over the limit
    if ((tmp_len + word_len) > max_length) {
      if (final_len > 0) {
        # add the temporary word to the final string if it was not empty
        final_string <- paste(final_string, '\n', tmp_string, sep = '')
      }
      else{
        # if there was not final string yet, it will just become that temporary string
        final_string <- tmp_string
      }
      # reset the temporary string
      tmp_string <- word
    }
    else{
      # otherwise add it to the temporary string
      if (tmp_len > 0) {
        tmp_string <- paste(tmp_string, word)
      }
      # or set if the temporary string was empty
      else{
        tmp_string <- word
      }
    }
  }
  # add last word
  if (nchar(paste(final_string, tmp_string)) > max_length) {
    if (nchar(final_string) == 0) {
      final_string <- tmp_string
    }
    else if (nchar(tmp_string > 0)) {
      final_string <- paste(final_string, '\n', tmp_string, sep = '')
    }
    else{
      # nothing the final string is as it is
    }
  }
  else {
    if (nchar(final_string) == 0) {
      final_string <- tmp_string
    }
    else if(nchar(tmp_string) == 0){
      # nothing, the final string is as is
    }
    else{
      final_string <- paste(final_string, ' ', tmp_string, sep = '')
    }
  }
  # add the last word
  return(final_string)
}


split_strings_with_max_length <- function(strings, max_length=15) {
  strings_split <- sapply(strings, FUN = function(x){
    split_string_with_max_length(x, max_length)
  })
  strings_split <- as.vector(strings_split)
  return(strings_split)
}


#' get the eGenes per cell type from QTL output
#' 
#' @param qtl_output_loc base location of the QTL output per cell type
#' @param output_file which output file to read for the results
#' @param gene_column which column to use as the gene identifier
#' @returns a list with the output tables per cell type
#' 
get_output_per_celltype_limix <- function(qtl_output_loc, output_file='qtl_results_all_qval_allchroms_fdr005_significant_cs.tsv.gz', gene_column='feature_id', significance_column='feature_q_value', significance_cutoff=0.05, verbose=T, add_nominal_cutoff=T, nominal_p_value_column='p_value') {
  # get the folders in the directory, which should be the cell types
  cell_types <- list.dirs(qtl_output_loc, full.names = F, recursive = F)
  # we will store the results in a list for now
  egenes_per_celltype <- list()
  # check each cell type
  for (cell_type in cell_types) {
    # paste together the full path
    full_cell_type_path <- paste(qtl_output_loc, '/', cell_type, '/', output_file, sep = '')
    # log if requested
    if (verbose) {
      print(paste('reading', full_cell_type_path))
    }
    # read the file
    cell_type_output <- read.table(full_cell_type_path, sep = '\t', header = T)
    # filter the results on significance
    if (!is.null(significance_column)) {
      # print progress if requested
      if (verbose) {
        print(paste('variant+phenotype before filtering', nrow(cell_type_output)))
      }
      # filter
      cell_type_output <- cell_type_output[
        !is.na(cell_type_output[[significance_column]]) &
          cell_type_output[[significance_column]] < significance_cutoff, 
      ]
      if (verbose) {
        print(paste('variant+phenotype after filtering', nrow(cell_type_output)))
      }
      # add nominal cutoff by first getting the top effects
      cell_type_output_top <- cell_type_output[order(cell_type_output[[nominal_p_value_column]]), ]
      cell_type_output_top <- cell_type_output_top[!duplicated(cell_type_output_top[[gene_column]]), ]
      # get the highest still significant p value
      max_sig_p <- max(cell_type_output_top[[nominal_p_value_column]])
      # and add that to the output
      cell_type_output[['nominal_p_value_cutoff']] <- max_sig_p
    }
    # add to the list
    egenes_per_celltype[[cell_type]] <- cell_type_output
  }
  # turn into a dataframe
  return(egenes_per_celltype)
}


get_credible_sets_output <- function(output_table_per_celltype, feature_column='feature_id', cs_column='CS', item_column='cell_type') {
  # filter on pval_nominal_threshold_global
  eqtl_outputs_filtered <- list()
  for (ct in names(output_table_per_celltype)) {
    # extract this eQTL output
    ct_eqtl_output <- output_table_per_celltype[[ct]]
    # # filter on the pval threshold
    # ct_eqtl_output <- ct_eqtl_output[ct_eqtl_output[['p_value']] < ct_eqtl_output[['pval_nominal_threshold_global']], ]
    # get the unique combinations of features and credible sets
    ct_eqtl_feature_cs <- unique(ct_eqtl_output[, c(feature_column, cs_column)])
    # get features with NA values
    ct_eqtl_feature_cs_na <- ct_eqtl_feature_cs[is.na(ct_eqtl_feature_cs[[cs_column]]), feature_column]
    # and the ones without
    ct_eqtl_feature_cs_nona <- ct_eqtl_feature_cs[!is.na(ct_eqtl_feature_cs[[cs_column]]), feature_column]
    # get the ones which are only with na
    ct_eqtl_feature_cs_onlyna <- setdiff(ct_eqtl_feature_cs_na, ct_eqtl_feature_cs_nona)
    # for the only NA ones, do L1
    ct_eqtl_feature_cs[ct_eqtl_feature_cs[[feature_column]] %in% ct_eqtl_feature_cs_onlyna, cs_column] <- 'L1'
    # then remove the NA ones
    ct_eqtl_feature_cs <- ct_eqtl_feature_cs[!is.na(ct_eqtl_feature_cs[[cs_column]]), ]
    # add the cell type
    ct_eqtl_feature_cs[[item_column]] <- ct
    # put it back in the list
    eqtl_outputs_filtered[[ct]] <- ct_eqtl_feature_cs
  }
  return(eqtl_outputs_filtered)
}


credible_sets_to_numbers_primary_and_other <- function(output_table_per_celltype, feature_column='feature_id', cs_column='CS') {
  # create a table to put results in
  nrs_table <- data.frame(
    'celltype' = rep(NA, times = length(names(output_table_per_celltype)) * 2), 
    'effect' = rep(NA, times = length(names(output_table_per_celltype)) * 2), 
    'number' = rep(NA, times = length(names(output_table_per_celltype)) * 2)
  )
  # check each cell type
  for (i in 1 : length(names(output_table_per_celltype))) {
    # extract cell type
    cell_type <- names(output_table_per_celltype)[i]
    # get the table
    ct_table <- output_table_per_celltype[[cell_type]]
    # get the unique features
    unique_features_ct <- unique(ct_table[[feature_column]])
    # get how many effects
    n_effects <- nrow(ct_table)
    # and how many unique effects
    n_unique_effects <- length(unique_features_ct)
    # which means there are non-primary effects
    n_non_primary_effects <- n_effects - n_unique_effects
    # put that into the table
    nrs_table[(i * 2 - 1), 'celltype'] <- cell_type
    nrs_table[(i * 2), 'celltype'] <- cell_type
    nrs_table[(i * 2 - 1), 'effect'] <- 'primary'
    nrs_table[(i * 2), 'effect'] <- 'additional'
    nrs_table[(i * 2 - 1), 'number'] <- n_unique_effects
    nrs_table[(i * 2), 'number'] <- n_non_primary_effects
    print(nrs_table)
  }
  return(nrs_table)
}


cs_number_to_name <- function(cs_number_or_name) {
  # this is our list with the mapping
  name_mapping <- list()
  name_mapping[['1']] <- 'primary'
  name_mapping[['2']] <- 'secondary'
  name_mapping[['3']] <- 'tertiary'
  name_mapping[['4']] <- 'quaternary'
  name_mapping[['5']] <- 'quinary'
  name_mapping[['6']] <- 'senary'
  name_mapping[['7']] <- 'septenary'
  name_mapping[['8']] <- 'octonary'
  name_mapping[['9']] <- 'nonary'
  name_mapping[['10']] <- 'senary'
  # now also do them with the 'L' added
  for (effect in names(name_mapping)) {
    name_mapping[[paste0('l', effect)]] <- name_mapping[[effect]]
    name_mapping[[paste0('L', effect)]] <- name_mapping[[effect]]
  }
  # check if the number or name was in the list
  if (as.character(cs_number_or_name) %in% names(name_mapping)) {
    return(name_mapping[[as.character(cs_number_or_name)]])
  }
  # otherwise just return the original
  else {
    # with a warning
    warning(paste('supplied credible set number or name does not have a string representation, value is returned as unchanged string'))
    return(as.character(cs_number_or_name))
  }
}


credible_sets_to_effect_number <- function(output_table_per_celltype, feature_column='feature_id', cs_column='CS') {
  # we'll store per cell type first
  effect_numbers_per_celltype <- list()
  # we'll check each cell type
  for (cell_type in names(output_table_per_celltype)) {
    # extract for that cell type
    ct_table <- output_table_per_celltype[[cell_type]]
    # now get the number for each credible set
    ct_cs_numbers <- data.frame(table(ct_table[[cs_column]]))
    # order that by the number
    ct_cs_numbers <- ct_cs_numbers[order(ct_cs_numbers[['Freq']], decreasing = T), ]
    # sometimes we'll have L4, but not L3. To account for that, we'll just make a new ordering
    ct_cs_numbers[['effect_nr']] <- 1:nrow(ct_cs_numbers)
    # and then give that a nice name
    ct_cs_numbers[['effect']] <- apply(ct_cs_numbers, 1, function(x){cs_number_to_name(x['effect_nr'])})
    # add the cell type
    ct_cs_numbers[['celltype']] <- cell_type
    # now filter to just what we care about
    ct_cs_numbers <- ct_cs_numbers[, c('celltype', 'effect', 'Freq')]
    # and rename columns to be how we like
    colnames(ct_cs_numbers) <- c('celltype', 'effect', 'number')
    # put in the list
    effect_numbers_per_celltype[[cell_type]] <- ct_cs_numbers
  }
  # merge all tables
  effect_numbers_all <- do.call('rbind', effect_numbers_per_celltype)
  return(effect_numbers_all)
}

credible_sets_to_numbers <- function(output_table_per_celltype, feature_column='feature_id', cs_column='CS', split_effects=F) {
  # initialize variable
  nrs_table <- NULL
  # we might care about primary, secondary, tertiary etc.
  if (split_effects) {
    nrs_table <- credible_sets_to_effect_number(output_table_per_celltype, feature_column = feature_column, cs_column = cs_column)
  }
  # or we just want primary and the rest
  else {
    nrs_table <- credible_sets_to_numbers_primary_and_other(output_table_per_celltype, feature_column = feature_column, cs_column = cs_column)
  }
  return(nrs_table)
}


#' plot in a barplot the number of DE genes per cell type
#' 
#' @param egene_numbers the table containing the number of eenes per cell type
#' @param celltype_column which column of the supplied table has the celltype name
#' @param number_column which column of the supplied table has the number of DE genes
#' @param pointless draw the ticks on the bottom of the plot?
#' @param legendless draw the legend?
#' @param ylim the range for the y-axis
#' @param paper_style use the paper style with more whitespace
#' @param angle_labels angle the x labels 90 degrees?
#' @param use_distinct_colours use the distinct colour palette instead of ggplot defaults (optional, default T)
#' @param use_sampling randomly sample colours from the distinct colour palette (optional, default F)
#' @param color_indices supply specific indices relating to colours to use from the distinct colour palette. Use 'get_available_colours_grid' to get the colours and their indices (optional, unused by default)
#' @param use_label_dict change names to a more pleasing format
#' @param make_labels_multiline make labels multiline if they are long
#' @param x_order to order the values on the x axis
#' @returns a barplot with the number of eGenes per cell type
#' 
cs_numbers_to_plot <- function(egene_numbers, celltype_column='cell_type', number_column='nr', effect_column='effect', pointless=F, legendless=F, ylim=NULL, paper_style=T, angle_labels=T, use_distinct_colours=T, use_sampling=F, color_indices=NULL, use_color_dict=F, use_label_dict=T, split_long_labels_to_lines=T, x_order=NULL) {
  # remap names if requested
  if (use_label_dict) {
    egene_numbers[[celltype_column]] <- remap_with_label_dict(egene_numbers[[celltype_column]])
  }
  # make them multiline
  if (split_long_labels_to_lines) {
    egene_numbers[[celltype_column]] <- split_strings_with_max_length(egene_numbers[[celltype_column]])
  }
  # order the x axis if requested
  if (!is.null(x_order)) {
    egene_numbers[[celltype_column]] <- factor(egene_numbers[[celltype_column]], levels = x_order)
  }
  # make new column of cell type and credible set
  egene_numbers[['cs_ct']] <- paste(egene_numbers[[celltype_column]], egene_numbers[[effect_column]])
  # start plot
  p <- ggplot(mapping = aes(x = egene_numbers[[celltype_column]], y = egene_numbers[[number_column]], fill = egene_numbers[['cs_ct']])) +
    geom_bar(stat='identity', position = 'stack') + 
    xlab(celltype_column) + 
    ylab(number_column) +
    guides(fill=guide_legend(title="effect"))
  # options
  if (use_distinct_colours) {
    # get the unique possible assigments
    possible_assignments <- unique(egene_numbers[['cs_ct']])
    # put into a list
    colour_mapping <- roycols::get_color_list(possible_assignments)
    # add to plot
    p <- p + scale_fill_manual(values = colour_mapping)
  }
  if (use_color_dict) {
    # get the color coding dict
    colour_mapping <- get_color_coding_dict()
    # also rename here then
    if (split_long_labels_to_lines) {
      names(colour_mapping) <- split_strings_with_max_length(names(colour_mapping))
    }
    # check each of the unique values for the effect
    unique_effects <- unique(egene_numbers[[effect_column]])
    # check how many unique effects there are
    n_unique_effects <- length(unique_effects)
    # and go through them
    for (i in 1 : n_unique_effects) {
      # get transparancy
      transparancy <- ((1 / i)) * 100 # this makes sure we have a unique transparancy for the combination of cell type and effect
      # add each effect
      for (celltype in names(colour_mapping)) {
        # and add a transparancy version of that colour
        colour_mapping[[paste(celltype, unique_effects[i])]] <- colorRampPalette(c(colour_mapping[[celltype]], "white"))(101)[101-transparancy]
      }
    }
    # add to plot
    p <- p + scale_fill_manual(values = colour_mapping)
  }
  if(!is.null(ylim)){
    p <- p + ylim(ylim)
  }
  if(pointless){
    p <- p + theme(axis.text.x=element_blank(), 
                   axis.ticks = element_blank())
  }
  if(legendless){
    p <- p + theme(legend.position = 'none')
  }
  if (paper_style) {
    p <- p + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white"))
  }
  if (angle_labels) {
    p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  }
  return(p)
}


#' plot in a barplot the number of DE genes per cell type
#' 
#' @param egene_numbers the table containing the number of eenes per cell type
#' @param celltype_column which column of the supplied table has the celltype name
#' @param number_column which column of the supplied table has the number of DE genes
#' @param pointless draw the ticks on the bottom of the plot?
#' @param legendless draw the legend?
#' @param ylim the range for the y-axis
#' @param paper_style use the paper style with more whitespace
#' @param angle_labels angle the x labels 90 degrees?
#' @param use_distinct_colours use the distinct colour palette instead of ggplot defaults (optional, default T)
#' @param use_sampling randomly sample colours from the distinct colour palette (optional, default F)
#' @param color_indices supply specific indices relating to colours to use from the distinct colour palette. Use 'get_available_colours_grid' to get the colours and their indices (optional, unused by default)
#' @param use_label_dict change names to a more pleasing format
#' @param make_labels_multiline make labels multiline if they are long
#' @param x_order to order the values on the x axis
#' @returns a barplot with the number of eGenes per cell type
#' 
egene_numbers_to_plot <- function(egene_numbers, celltype_column='cell_type', number_column='nr', pointless=F, legendless=F, ylim=NULL, paper_style=T, angle_labels=T, use_distinct_colours=T, use_sampling=F, color_indices=NULL, use_color_dict=F, use_label_dict=T, split_long_labels_to_lines=T, x_order=NULL) {
  # remap names if requested
  if (use_label_dict) {
    egene_numbers[[celltype_column]] <- remap_with_label_dict(egene_numbers[[celltype_column]])
  }
  # make them multiline
  if (split_long_labels_to_lines) {
    egene_numbers[[celltype_column]] <- split_strings_with_max_length(egene_numbers[[celltype_column]])
  }
  # order the x axis if requested
  if (!is.null(x_order)) {
    egene_numbers[[celltype_column]] <- factor(egene_numbers[[celltype_column]], levels = x_order)
  }
  # start plot
  p <- ggplot(mapping = aes(x = egene_numbers[[celltype_column]], y = egene_numbers[[number_column]], fill = egene_numbers[[celltype_column]])) +
    geom_bar(stat='identity') + xlab(celltype_column) + ylab(number_column)
  # options
  if (use_distinct_colours) {
    # get the unique possible assigments
    possible_assignments <- unique(egene_numbers[[celltype_column]])
    # put into a list
    colour_mapping <- roycols::get_color_list(possible_assignments)
    # add to plot
    p <- p + scale_fill_manual(values = colour_mapping)
  }
  if (use_color_dict) {
    # get the color coding dict
    colour_mapping <- get_color_coding_dict()
    # also rename here then
    if (split_long_labels_to_lines) {
      names(colour_mapping) <- split_strings_with_max_length(names(colour_mapping))
    }
    # add to plot
    p <- p + scale_fill_manual(values = colour_mapping)
  }
  if(!is.null(ylim)){
    p <- p + ylim(ylim)
  }
  if(pointless){
    p <- p + theme(axis.text.x=element_blank(), 
                   axis.ticks = element_blank())
  }
  if(legendless){
    p <- p + theme(legend.position = 'none')
  }
  if (paper_style) {
    p <- p + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white"))
  }
  if (angle_labels) {
    p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  }
  return(p)
}


#' get the eGenes per cell type from QTL output
#' 
#' @param qtl_output_loc base location of the QTL output per cell type
#' @returns a list with the output tables per cell type
#' 
get_output_per_celltype_coloc <- function(coloc_output_loc, file_prepend='', file_append='_eqtl_caqtl_coloc.tsv.gz', h4_column='PP.H4.abf') {
  # get the folders in the directory, which should be the cell types
  cell_type_files <- list.files(coloc_output_loc, full.names = F, recursive = F)
  # filter these on the pattern
  cell_type_pattern <- paste0(file_prepend, '.*', file_append, '$')
  cell_type_files <- cell_type_files[grep(cell_type_pattern, cell_type_files)]
  # store the result per cell type
  coloc_per_celltype <- list()
  # check each file
  for (cell_type_file in cell_type_files) {
    # paste the full path together
    cell_type_file_full <- paste0(coloc_output_loc, '/', cell_type_file)
    # read the file
    coloc_celltype <- fread(cell_type_file_full, header = T, sep = '\t')
    # filter on existing h4
    coloc_celltype <- coloc_celltype[!is.na(coloc_celltype[[h4_column]]), ]
    # remove the prepend from the file
    cell_type <- gsub(file_prepend, '', cell_type_file)
    # and the append
    cell_type <- gsub(file_append, '', cell_type)
    # add the cell type to the table
    coloc_celltype[['cell_type']] <- cell_type
    # and put in list
    coloc_per_celltype[[cell_type]] <- coloc_celltype
  }
  return(coloc_per_celltype)
}

```


```{r path_setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

####################
# Main Code        #
####################

# location of the QTL outputs
caqtl_output_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/finemapping/caqtl/sc-eqtlgen/combined_with_qtl/combined/L1/'
eqtl_output_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/finemapping/eqtl/sc-eqtlgen/combined_with_qtl/combined/L1/'

```

```{r read_eqtl_outputs, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# read the eQTL output
eqtl_outputs <- get_output_per_celltype_limix(eqtl_output_loc)

```

```{r filter_eqtl_outputs, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# fix CS with only NA, to be L1
eqtl_outputs_filtered <- get_credible_sets_output(eqtl_outputs)

```

```{r count_eqtl_cs, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# get primary and non-primary effects
eqtl_cs_counts <- credible_sets_to_numbers(eqtl_outputs_filtered, split_effects=F)
# and the full list
eqtl_cs_counts_full <- credible_sets_to_numbers(eqtl_outputs_filtered, split_effects=T)

```

```{r plot_eqtl_cs, include=TRUE, fig.width=8, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# finally plot
p_eqtl_cs_primary_and_other <- cs_numbers_to_plot(eqtl_cs_counts, use_color_dict = T, celltype_column = 'celltype', number_column = 'number') +
  ggtitle('Primary and additional effects in eQTLs')
# both of them
p_eqtl_cs_each <- cs_numbers_to_plot(eqtl_cs_counts_full, use_color_dict = T, celltype_column = 'celltype', number_column = 'number') +
  ggtitle('Primary and additional effects in eQTLs')

# and for the poster
p_eqtl_cs_primary_and_other_poster <- p_eqtl_cs_primary_and_other + 
  xlab('Cell type') +
  ylab('Number of independent eQTLs') +
  theme(legend.position="none") +
  theme(
    plot.title = element_text(size = 24),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20), 
    axis.text.x = element_text(size = 16), 
    axis.text.y = element_text(size = 16)
  )
# add to the others as well
p_eqtl_cs_primary_and_other <- p_eqtl_cs_primary_and_other + 
  xlab('Cell type') +
  ylab('Number of independent eQTLs') +
  theme(legend.position="none") +
  theme(
    plot.title = element_text(size = 24),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20), 
    axis.text.x = element_text(size = 16), 
    axis.text.y = element_text(size = 16)
  )
p_eqtl_cs_each <- p_eqtl_cs_each + 
  xlab('Cell type') +
  ylab('Number of independent eQTLs') +
  theme(legend.position="none") +
  theme(
    plot.title = element_text(size = 24),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20), 
    axis.text.x = element_text(size = 16), 
    axis.text.y = element_text(size = 16)
  )

# save the plots
ggsave(filename = '~/plots/mo_eqtl_cs_primary_and_other.pdf', plot = p_eqtl_cs_primary_and_other, width = 8, height = 8)
ggsave(filename = '~/plots/mo_eqtl_cs_each.pdf', plot = p_eqtl_cs_each, width = 8, height = 8)
ggsave(filename = '~/plots/mo_eqtl_cs_each_poster.pdf', plot = p_eqtl_cs_primary_and_other_poster, width = 8, height = 8)

# show the plots
p_eqtl_cs_primary_and_other
p_eqtl_cs_each

```

```{r read_caqtl_outputs, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# read the caqtl output
caqtl_outputs <- get_output_per_celltype_limix(caqtl_output_loc)

```

```{r filter_caqtl_outputs, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# fix CS with only NA, to be L1
caqtl_outputs_filtered <- get_credible_sets_output(caqtl_outputs)

```

```{r count_caqtl_cs, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# get primary and non-primary effects
caqtl_cs_counts <- credible_sets_to_numbers(caqtl_outputs_filtered, split_effects=F)
# and the full list
caqtl_cs_counts_full <- credible_sets_to_numbers(caqtl_outputs_filtered, split_effects=T)


```

```{r plot_caqtl_cs, include=TRUE, fig.width=8, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# finally plot
p_caqtl_cs_primary_and_other <- cs_numbers_to_plot(caqtl_cs_counts, use_color_dict = T, celltype_column = 'celltype', number_column = 'number') +
  ggtitle('Primary and additional effects in caQTLs')
# both of them
p_caqtl_cs_each <- cs_numbers_to_plot(caqtl_cs_counts_full, use_color_dict = T, celltype_column = 'celltype', number_column = 'number') +
  ggtitle('Primary and additional effects in caQTLs')

# and for the poster
p_caqtl_cs_primary_and_other_poster <- p_caqtl_cs_primary_and_other + 
  xlab('Cell type') +
  ylab('Number of independent caQTLs') +
  theme(legend.position="none") +
  theme(
    plot.title = element_text(size = 24),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20), 
    axis.text.x = element_text(size = 16), 
    axis.text.y = element_text(size = 16)
  )
# add to the others as well
p_caqtl_cs_primary_and_other <- p_caqtl_cs_primary_and_other + 
  xlab('Cell type') +
  ylab('Number of independent caQTLs') +
  theme(legend.position="none") +
  theme(
    plot.title = element_text(size = 24),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20), 
    axis.text.x = element_text(size = 16), 
    axis.text.y = element_text(size = 16)
  )
p_caqtl_cs_each <- p_caqtl_cs_each + 
  xlab('Cell type') +
  ylab('Number of independent caQTLs') +
  theme(legend.position="none") +
  theme(
    plot.title = element_text(size = 24),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20), 
    axis.text.x = element_text(size = 16), 
    axis.text.y = element_text(size = 16)
  )

# save the plots
ggsave(filename = '~/plots/mo_caqtl_cs_primary_and_other.pdf', plot = p_caqtl_cs_primary_and_other, width = 8, height = 8)
ggsave(filename = '~/plots/mo_caqtl_cs_each.pdf', plot = p_caqtl_cs_each, width = 8, height = 8)
ggsave(filename = '~/plots/mo_caqtl_cs_each_poster.pdf', plot = p_caqtl_cs_primary_and_other_poster, width = 8, height = 8)


# show the plots
p_caqtl_cs_primary_and_other
p_caqtl_cs_each

```

```{r filter_variants, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# make filtered lists fo variants
eqtl_outputs_filtered <- list()
for (ct in names(eqtl_outputs)) {
  # extract for that cell type
  eqtl_output_ct <- eqtl_outputs[[ct]]
  # filter on nominal threshold
  eqtl_output_ct <- eqtl_output_ct[eqtl_output_ct[['p_value']] <= eqtl_output_ct[['nominal_p_value_cutoff']], ]
  eqtl_output_ct[eqtl_output_ct[['empirical_feature_p_value']] < 0.05, ]
  # put back into the list
  eqtl_outputs_filtered[[ct]] <- eqtl_output_ct
}

# make filtered lists fo variants
caqtl_outputs_filtered <- list()
for (ct in names(caqtl_outputs)) {
  # extract for that cell type
  caqtl_output_ct <- caqtl_outputs[[ct]]
  # filter on nominal threshold
  caqtl_output_ct <- caqtl_output_ct[caqtl_output_ct[['p_value']] <= caqtl_output_ct[['nominal_p_value_cutoff']], ]
  caqtl_output_ct[caqtl_output_ct[['empirical_feature_p_value']] < 0.05, ]
  # put back into the list
  caqtl_outputs_filtered[[ct]] <- caqtl_output_ct
}

# now merge based on variant
qtl_outputs_overlapping <- list()
for (ct in intersect(names(eqtl_outputs_filtered), names(caqtl_outputs_filtered))) {
  # extract the eqtl
  eqtl_output_ct <- eqtl_outputs_filtered[[ct]]
  # extract the eqtl
  caqtl_output_ct <- caqtl_outputs_filtered[[ct]]
  # subset to just the variant and feature
  eqtl_output_ct <- eqtl_output_ct[, c('snp_id', 'feature_id', 'assessed_allele', 'beta', 'beta_se', 'p_value')]
  caqtl_output_ct <- caqtl_output_ct[, c('snp_id', 'feature_id', 'assessed_allele', 'beta', 'beta_se', 'p_value')]
  # rename the columns
  colnames(eqtl_output_ct) <- c('snp_id', 'feature_eqtl', 'aa_eqtl', 'beta_eqtl', 'se_eqtl', 'p_value_eqtl')
  colnames(caqtl_output_ct) <- c('snp_id', 'feature_caqtl', 'aa_caqtl', 'beta_caqtl', 'se_caqtl', 'p_value_caqtl')
  # merge them
  qtl_output_ct_overlapping <- merge(caqtl_output_ct, eqtl_output_ct, on = 'snp_id')
  # put back into list
  qtl_outputs_overlapping[[ct]] <- qtl_output_ct_overlapping
}

```

```{r plot_overlapping_effects, include=TRUE, fig.width=8, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# we'll make some plots with numbers
ngenes_with_overlapping_snps <- data.frame('cell_type' = rep(NA, times = length(names(qtl_outputs_overlapping))), 'number' = rep(NA, times = length(names(qtl_outputs_overlapping))))
npeaks_with_overlapping_snps <- data.frame('cell_type' = rep(NA, times = length(names(qtl_outputs_overlapping))), 'number' = rep(NA, times = length(names(qtl_outputs_overlapping))))
n_peak_gene_with_overlapping_effects <- data.frame('cell_type' = rep(NA, times = length(names(qtl_outputs_overlapping))), 'number' = rep(NA, times = length(names(qtl_outputs_overlapping))))

# check each cell type
for (i in 1 : length(names(qtl_outputs_overlapping))) {
  # get the cell type
  cell_type <- names(qtl_outputs_overlapping)[i]
  # extract the table
  qtl_output_ct_overlapping <- qtl_outputs_overlapping[[cell_type]]
  # count the number of genes overlapping
  n_genes_with_overlap <- length(unique(qtl_output_ct_overlapping[['feature_eqtl']]))
  # and number of peaks
  n_peaks_with_overlap <- length(unique(qtl_output_ct_overlapping[['feature_caqtl']]))
  # and unique combinations
  n_overlapping_peak_gene <- nrow(unique(qtl_output_ct_overlapping[, c('feature_eqtl', 'feature_caqtl')]))
  # put into the tables
  ngenes_with_overlapping_snps[i, 'cell_type'] <- cell_type
  npeaks_with_overlapping_snps[i, 'cell_type'] <- cell_type
  n_peak_gene_with_overlapping_effects[i, 'cell_type'] <- cell_type
  ngenes_with_overlapping_snps[i, 'number'] <- n_genes_with_overlap
  npeaks_with_overlapping_snps[i, 'number'] <- n_peaks_with_overlap
  n_peak_gene_with_overlapping_effects[i, 'number'] <- n_overlapping_peak_gene
}

# make the actual plots now
p_n_egenes_overlap_caqtl <- egene_numbers_to_plot(ngenes_with_overlapping_snps, celltype_column = 'cell_type', number_column = 'number', legendless = T, use_color_dict = T, use_label_dict = T) +
  xlab('Cell type') +
  ylab('Number of genes') +
  ggtitle('Number of eGenes with variant overlapping caQTL')
p_n_epeaks_overlap_eqtl <- egene_numbers_to_plot(npeaks_with_overlapping_snps, celltype_column = 'cell_type', number_column = 'number', legendless = T, use_color_dict = T, use_label_dict = T) +
  xlab('Cell type') +
  ylab('Number of peaks') +
  ggtitle('Number of ePeaks with variant overlapping eQTL')
p_n_egene_epeak_overlap <- egene_numbers_to_plot(n_peak_gene_with_overlapping_effects, celltype_column = 'cell_type', number_column = 'number', legendless = T, use_color_dict = T, use_label_dict = T) +
  xlab('Cell type') +
  ylab('Number of peak-gene combinatinos') +
  ggtitle('Number of peak-gene pairs with an overlapping variant')

# show the plots
p_n_egenes_overlap_caqtl
p_n_epeaks_overlap_eqtl
p_n_egene_epeak_overlap

```
```{r plot_n_overlapping_effects, include=TRUE, fig.width=8, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# store per cell type first
n_peak_ocurrence_per_celltype <- list()

# check each cell type
for (i in 1 : length(names(qtl_outputs_overlapping))) {
  # get the cell type
  cell_type <- names(qtl_outputs_overlapping)[i]
  # extract the table
  qtl_output_ct_overlapping <- qtl_outputs_overlapping[[cell_type]]
  # get the unique peak-gene combinations
  qtl_output_ct_overlapping_unique <- unique(qtl_output_ct_overlapping[, c('feature_eqtl', 'feature_caqtl')])
  # get the number of peaks per gene
  n_peak_per_gene <- data.frame(table(qtl_output_ct_overlapping_unique[['feature_eqtl']]))
  # next get the occurence of those numbers
  n_peak_per_gene_occurence <- data.frame(table(n_peak_per_gene[['Freq']]))
  # add the cell type
  n_peak_per_gene_occurence[['cell_type']] <- cell_type
  # rename the columns
  colnames(n_peak_per_gene_occurence) <- c('n_peaks', 'nr', 'celltype')
  # make the number of peaks a character vector
  n_peak_per_gene_occurence[['n_peaks']] <- paste(as.character(n_peak_per_gene_occurence[['n_peaks']]), 'peaks')
  # put in list
  n_peak_ocurrence_per_celltype[[cell_type]] <- n_peak_per_gene_occurence
}

# merge everything
n_peak_ocurrence_all <- do.call('rbind', n_peak_ocurrence_per_celltype)

# make the plot
p_n_peak_per_gene <- ggplot(data = n_peak_ocurrence_all[rep(1:nrow(n_peak_ocurrence_all), n_peak_ocurrence_all[['nr']]), , drop = FALSE], mapping = aes(x = nr, fill = celltype)) + 
  geom_density(alpha = 0.5) + 
  scale_fill_manual(values = get_color_coding_dict()[unique(n_peak_ocurrence_all[['celltype']])]) +
  xlab('Number of ePeaks') + 
  ylab('Density') + 
  ggtitle('Number of ePeaks with variant overlapping eGene') + 
  theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white"))

# show the plot
p_n_peak_per_gene

```

```{r get_qtl_coloc_effects}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# location of the eQTL to caQTL coloc output
qtl_coloc_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/colocalization/eqtl_caqtl/'
# read this data
qtl_coloc <- get_output_per_celltype_coloc(qtl_coloc_loc)

# let's just keep the H4 => 0.8 
qtl_coloc_filtered <- list()
for (cell_type in names(qtl_coloc)) {
  # get the table
  qtl_coloc_celltype <- qtl_coloc[[cell_type]]
  # filter
  qtl_coloc_celltype <- qtl_coloc_celltype[!is.na(qtl_coloc_celltype[['PP.H4.abf']]) & qtl_coloc_celltype[['PP.H4.abf']] >= 0.8, ]
  # put back in the list
  qtl_coloc_filtered[[cell_type]] <- qtl_coloc_celltype
}

```

```{r plot_n_colocing_effects, include=TRUE, fig.width=8, fig.height=8}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# we'll make some plots with numbers
ngenes_with_colocing_snps <- data.frame('cell_type' = rep(NA, times = length(names(qtl_coloc_filtered))), 'number' = rep(NA, times = length(names(qtl_coloc_filtered))))
npeaks_with_colocing_snps <- data.frame('cell_type' = rep(NA, times = length(names(qtl_coloc_filtered))), 'number' = rep(NA, times = length(names(qtl_coloc_filtered))))
n_peak_gene_with_colocing_effects <- data.frame('cell_type' = rep(NA, times = length(names(qtl_coloc_filtered))), 'number' = rep(NA, times = length(names(qtl_coloc_filtered))))

# check each cell type
for (i in 1 : length(names(qtl_coloc_filtered))) {
  # get the cell type
  cell_type <- names(qtl_coloc_filtered)[i]
  # extract the table
  qtl_output_ct_colocing <- qtl_coloc_filtered[[cell_type]]
  # count the number of genes colocing
  n_genes_with_coloc <- length(unique(qtl_output_ct_colocing[['trait2']]))
  # and number of peaks
  n_peaks_with_coloc <- length(unique(qtl_output_ct_colocing[['trait1']]))
  # and unique combinations
  n_colocing_peak_gene <- nrow(unique(qtl_output_ct_colocing[, c('trait2', 'trait1')]))
  # put into the tables
  ngenes_with_colocing_snps[i, 'cell_type'] <- cell_type
  npeaks_with_colocing_snps[i, 'cell_type'] <- cell_type
  n_peak_gene_with_colocing_effects[i, 'cell_type'] <- cell_type
  ngenes_with_colocing_snps[i, 'number'] <- n_genes_with_coloc
  npeaks_with_colocing_snps[i, 'number'] <- n_peaks_with_coloc
  n_peak_gene_with_colocing_effects[i, 'number'] <- n_colocing_peak_gene
}

# make the actual plots now
p_n_egenes_coloc_caqtl <- egene_numbers_to_plot(ngenes_with_colocing_snps, celltype_column = 'cell_type', number_column = 'number', legendless = T, use_color_dict = T, use_label_dict = T) +
  xlab('Cell type') +
  ylab('Number of genes') +
  ggtitle('Number of eGenes with variant colocing caQTL')
p_n_epeaks_coloc_eqtl <- egene_numbers_to_plot(npeaks_with_colocing_snps, celltype_column = 'cell_type', number_column = 'number', legendless = T, use_color_dict = T, use_label_dict = T) +
  xlab('Cell type') +
  ylab('Number of peaks') +
  ggtitle('Number of ePeaks with variant colocing eQTL')
p_n_egene_epeak_coloc <- egene_numbers_to_plot(n_peak_gene_with_colocing_effects, celltype_column = 'cell_type', number_column = 'number', legendless = T, use_color_dict = T, use_label_dict = T) +
  xlab('Cell type') +
  ylab('Number of peak-gene combinatinos') +
  ggtitle('Number of peak-gene pairs with an colocing variant')

# show the plots
p_n_egenes_coloc_caqtl
p_n_epeaks_coloc_eqtl
p_n_egene_epeak_coloc

```

```{r export_tables, include=TRUE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# base location of overlapping effects
overlapping_effects_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/eqtl_caqtl_overlap/combined/L1/'
# check each cell type
for (cell_type in names(qtl_outputs_overlapping)) {
  # paste the path together
  cell_type_path <- paste(overlapping_effects_loc, cell_type, 'eqtl_caqtl_overlapping_variants.tsv.gz', sep = '/')
  # write the table
  write.table(qtl_outputs_overlapping[[cell_type]], gzfile(cell_type_path), row.names = F, col.names = T, sep = '\t', quote = F)
  # make a checksum
  mdfiver::create_md5_for_file(cell_type_path)
}

# finally also do the outer join of all cell types
overlapping_effect_with_ct <- list()
# check each cell type
for (cell_type in names(qtl_outputs_overlapping)) {
  # add cell type as explicit column, and put into new list
  overlapping_effect_with_ct[[cell_type]] <- cbind(
    qtl_outputs_overlapping[[cell_type]], 
    data.frame('cell_type' = rep(cell_type, times = nrow(qtl_outputs_overlapping[[cell_type]])))
  )
}
# merge all those
overlapping_effect_all <- do.call('rbind', overlapping_effect_with_ct)
# make a folder
dir.create(paste(overlapping_effects_loc, 'all', sep = '/'))
# make a path
all_cell_types_path <- paste(overlapping_effects_loc, 'all', 'eqtl_caqtl_overlapping_variants.tsv.gz', sep = '/')
# write the table
write.table(overlapping_effect_all, gzfile(all_cell_types_path), row.names = F, col.names = T, sep = '\t', quote = F)
# make a checksum
mdfiver::create_md5_for_file(all_cell_types_path)

# finally also just take the combination of region and gene
overlapping_effects_region_to_gene <- unique(overlapping_effect_all[, c('feature_caqtl', 'feature_eqtl')])
# order
overlapping_effects_region_to_gene <- overlapping_effects_region_to_gene[order(overlapping_effects_region_to_gene[['feature_caqtl']], overlapping_effects_region_to_gene[['feature_eqtl']]), ]
# which we will place somewhere
combined_overlapping_region_to_gene_loc <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/cre_eqtl/eqtl_caqtl_overlap/combined/confinements/region_to_peak_variant_overlaps.tsv.gz'
# and write
write.table(overlapping_effects_region_to_gene, gzfile(combined_overlapping_region_to_gene_loc), row.names = F, col.names = F, sep = '\t', quote = F)
# and make checksum
mdfiver::create_md5_for_file(combined_overlapping_region_to_gene_loc)

```

