---
title: "mo_analyse_dar_output"
author: "Roy Oelen"
date: "2024-07-14"
output: html_document
---

```{r header, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#!/usr/bin/env Rscript
############################################################################################################################
# Authors: Roy Oelen
# Name: mo_analyse_dar_output.Rmd
# Function: plot DAR output
############################################################################################################################
```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

####################
# libraries        #
####################

# for plotting
library(ggplot2)
library(cowplot)
library(roycols)
library(RColorBrewer)
library(UpSetR)
library(grid)

```

```{r functions, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# Functions        #
####################

#' get a label dict that replaces the posix safe names into printable versions
#' 
#' @returns a label dict that replaces the posix safe names into printable versions
#' label_dict_names <- get_label_dict()
get_label_dict <- function() {
  label_dict <- list()
  # condition combinations
  label_dict[['cUTc24hCA']] <- 'UT-24hCA'
  label_dict[['c24hCAcUT']] <- 'UT-24hCA'
  # conditions
  label_dict[['UT']] <- 'untreated'
  label_dict[['cUT']] <- 'untreated'
  label_dict[['24hCA']] <- '24h Candida'
  label_dict[['c24hCA']] <- '24h Candida'
  # major cell types
  label_dict[["Bulk"]] <- "bulk-like"
  label_dict[["CD4T"]] <- "CD4+ T"
  label_dict[["CD8T"]] <- "CD8+ T"
  label_dict[["monocyte"]] <- "monocyte"
  label_dict[["NK"]] <- "NK"
  label_dict[["B"]] <- "B"
  label_dict[["DC"]] <- "DC"
  label_dict[["HSPC"]] <- "HSPC"
  label_dict[["plasmablast"]] <- "plasmablast"
  label_dict[["platelet"]] <- "platelet"
  label_dict[["T_other"]] <- "other T"
  # minor cell types
  label_dict[["CD4_TCM"]] <- "CD4 TCM"
  label_dict[["Treg"]] <- "T regulatory"
  label_dict[["CD4_Naive"]] <- "CD4 naive"
  label_dict[["CD4_CTL"]] <- "CD4 CTL"
  label_dict[["CD8_TEM"]] <- "CD8 TEM"
  label_dict[["cMono"]] <- "cMono"
  label_dict[["CD8_TCM"]] <- "CD8 TCM"
  label_dict[["ncMono"]] <- "ncMono"
  label_dict[["cDC2"]] <- "cDC2"
  label_dict[["B_intermediate"]] <- "B intermediate"
  label_dict[["NKdim"]] <- "NK dim"
  label_dict[["pDC"]] <- "pDC"
  label_dict[["ASDC"]] <- "ASDC"
  label_dict[["CD8_Naive"]] <- "CD8 naive"
  label_dict[["MAIT"]] <- "MAIT"
  label_dict[["CD8_Proliferating"]] <- "CD8 proliferating"
  label_dict[["CD4_TEM"]] <- "CD4 TEM"
  label_dict[["B_memory"]] <- "B memory"
  label_dict[["NKbright"]] <- "NK bright"
  label_dict[["B_naive"]] <- "B naive"
  label_dict[["gdT"]] <- "gamma delta T"
  label_dict[["CD4_Proliferating"]] <- "CD4 proliferating"
  label_dict[["NK_Proliferating"]] <- "NK proliferating"
  label_dict[["cDC1"]] <- "cDC1"
  label_dict[["ILC"]] <- "ILC"
  label_dict[["dnT"]] <- "double negative T"
  return(label_dict)
}


rename_labels <- function(vector_to_rename) {
  # get the labels that are present
  label_renaming <- get_label_dict()
  # now check which labels we are missing
  missing_renames <- setdiff(unique(vector_to_rename), names(label_renaming))
  # add those renames as not being renames
  for (missing_rename in missing_renames) {
    label_renaming[[missing_rename]] <- missing_rename
  }
  # now replace each value with the rename
  renamed_vector <- as.vector(unlist(label_renaming[vector_to_rename]))
  # and return that
  return(renamed_vector)
}


get_color_coding_dict <- function() {
	# set the condition colors
  color_coding <- list()
  color_coding[["UTBaseline"]] <- "khaki2"
  color_coding[["UTt24h"]] <- "khaki4"
  color_coding[["UTt8w"]] <- "paleturquoise1"
  color_coding[["Baselinet24h"]] <- "paleturquoise3"
  color_coding[["Baselinet8w"]] <- "rosybrown1"
  color_coding[["t24ht8w"]] <- "rosybrown3"
  color_coding[["UT\nBaseline"]] <- "khaki2"
  color_coding[["UT\nt24h"]] <- "khaki4"
  color_coding[["UT\nt8w"]] <- "paleturquoise1"
  color_coding[["Baseline\nt24h"]] <- "paleturquoise3"
  color_coding[["Baseline\nt8w"]] <- "rosybrown1"
  color_coding[["t24h\nt8w"]] <- "rosybrown3"
  color_coding[["UT-Baseline"]] <- "khaki2"
  color_coding[["UT-t24h"]] <- "khaki4"
  color_coding[["UT-t8w"]] <- "paleturquoise1"
  color_coding[["Baseline-t24h"]] <- "paleturquoise3"
  color_coding[["Baseline-t8w"]] <- "rosybrown1"
  color_coding[["t24h-t8w"]] <- "rosybrown3"
  color_coding[["UT-t0"]] <- "khaki2"
  color_coding[["UT-t24h"]] <- "khaki4"
  color_coding[["UT-t8w"]] <- "paleturquoise1"
  color_coding[["HC-t0"]] <- "khaki2"
  color_coding[["HC-t24h"]] <- "khaki4"
  color_coding[["HC-t8w"]] <- "paleturquoise1"
  color_coding[["t0-t24h"]] <- "paleturquoise3"
  color_coding[["t0-t8w"]] <- "rosybrown1"
  color_coding[["t24h-t8w"]] <- "rosybrown3"
  # set condition colors
  color_coding[["HC"]] <- "grey"
  color_coding[["Control"]] <- "grey"
  color_coding[["C"]] <- "grey"
  color_coding[["t0"]] <- "#ff7101"
  color_coding[["t24h"]] <- "#e12a62"
  color_coding[["t8w"]] <- "#3B0550"
  color_coding[["t6-8w"]] <- "#3B0550"
  # set the cell type colors
  color_coding[["Bulk"]] <- "black"
  color_coding[["CD4T"]] <- "#153057"
  color_coding[["CD8T"]] <- "#009DDB"
  color_coding[["monocyte"]] <- "#EDBA1B"
  color_coding[["NK"]] <- "#E64B50"
  color_coding[["B"]] <- "#71BC4B"
  color_coding[["DC"]] <- "#965EC8"
  color_coding[["CD4+ T"]] <- "#153057"
  color_coding[["CD8+ T"]] <- "#009DDB"
  # other cell type colors
  color_coding[["HSPC"]] <- "#009E94"
  color_coding[["platelet"]] <- "#9E1C00"
  color_coding[["plasmablast"]] <- "#DB8E00"
  color_coding[["other T"]] <- "#FF63B6"
  return(color_coding)
}


#' get the LFC for each gene from an output file processed by limma dream
#' 
#' @param mast.output.loc the location of the output file
#' @param p.val.column the column in the file that has the P value to filtr on
#' @param p.val.cutoff the p-value cutoff to use for filtering
#' @returns the filtered table for that output file
#' 
get_gene_and_lfc_limma <- function(limma.output.loc, p.val.column='p.bonferroni', p.val.cutoff=0.05){
  # read the output
  de.output <- read.table(limma.output.loc, header = T, sep = '\t', stringsAsFactors = F)
  # subset to what is significant
  de.output.significant <- de.output[de.output[[p.val.column]] < p.val.cutoff, ]
  return(de.output.significant)
}

#' get the LFC for each gene from an output file in bed format
#' 
#' @param mast.output.loc the location of the output file
#' @param p.val.column the column in the file that has the P value to filtr on
#' @param p.val.cutoff the p-value cutoff to use for filtering
#' @returns the filtered table for that output file
#' 
get_gene_and_lfc_bed <- function(limma.output.loc, p.val.column='p.bonferroni', p.val.cutoff=0.05){
  # read the output
  de.output <- read.table(limma.output.loc, header = T, sep = '\t', stringsAsFactors = F, check.names = F, comment.char = '')
  # subset to what is significant
  de.output.significant <- de.output
  if (!is.null(p.val.column) & !is.null(p.val.cutoff)) {
    de.output.significant <- de.output[de.output[[p.val.column]] < p.val.cutoff, ]
  }
  return(de.output.significant)
}

#' get the LFC for each gene from an output file in bed format
#' 
#' @param mast.output.loc the location of the output file
#' @param p.val.column the column in the file that has the P value to filtr on
#' @param p.val.cutoff the p-value cutoff to use for filtering
#' @returns the filtered table for that output file
#' 
get_gene_and_lfc_bed_headless <- function(limma.output.loc, p.val.column=NULL, p.val.cutoff=NULL){
  # read the output
  de.output <- read.table(limma.output.loc, header = F, sep = '\t', stringsAsFactors = F, check.names = F, comment.char = '')
  # subset to what is significant
  de.output.significant <- de.output
  if (!is.null(p.val.column) & !is.null(p.val.cutoff)) {
    de.output.significant <- de.output[de.output[[p.val.column]] < p.val.cutoff, ]
  }
  return(de.output.significant)
}


#' get the LFC for each gene from an output file created by a DE method
#' 
#' @param de.output.loc the location of the output file
#' @param de_method the DE method used (mast_standalone, mast_seurat, bed or limma)
#' @param p.val.column the column in the file that has the P value to filter on
#' @param p.val.cutoff the p-value cutoff to use for filtering
#' @returns the filtered table for that output file
#' 
get_de_output <- function(de.output.loc, de_method, p.val.column='bonferroni', p.val.cutoff=0.05){
  # use the correct method
  de.output <- NULL
  if (de_method == 'limma'){
    de.output <- get_gene_and_lfc_limma(de.output.loc, p.val.column = p.val.column, p.val.cutoff = p.val.cutoff)
  }
  else if (de_method == 'bed') {
    de.output <- get_gene_and_lfc_bed(de.output.loc, p.val.column = p.val.column, p.val.cutoff = p.val.cutoff)
  }
  else if (de_method == 'bed_headless') {
    de.output <- get_gene_and_lfc_bed_headless(de.output.loc, p.val.column = p.val.column, p.val.cutoff = p.val.cutoff)
  }
  else{
    print('de_method not valid, valid options are: limma')
  }
  return(de.output)
}

#' get the LFC for each gene from each output file created by a DE method
#' 
#' @param de_output_path the folder containing the DE results
#' @param de_method the DE method used (mast_standalone, mast_seurat or limma)
#' @param p.val.column the column in the file that has the P value to filter on
#' @param p.val.cutoff the p-value cutoff to use for filtering
#' @returns a list of tables per output file, with in each entry a table with the filtered table for that output file
#' 
get_de_genes_per_celltype <- function(de_output_path, de_method, pval_column='p.bonferroni', p_val_cutoff=0.05, pattern='*_condition_final.nominal_significant.tsv.gz$') {
  # list files in directory
  files_dir <- list.files(de_output_path, full.names = T, pattern = pattern)
  # keep track of results per celltype
  results_per_ct <- list()
  # check each file
  for (output_file in files_dir) {
    # get the output
    output <- get_de_output(output_file, de_method = de_method, p.val.column = pval_column, p.val.cutoff = p_val_cutoff)
    # get the basename of the file
    basename_file <- basename(output_file)
    basename_file <- sub(pattern = "(.*?)\\..*$", replacement = "\\1", basename_file)
    # add to the list
    results_per_ct[[basename_file]] <- output
  }
  return(results_per_ct)
}

#' get the number of DE genes per output file
#' 
#' @param de_output_path the DE output table per cell type in a list, with the names being the cell types
#' @param celltype_snip part of the string remove from the cell type annotation to make the name look nicer
#' @param p.val.column the column in the file that has the P value to filter on
#' @param p.val.cutoff the p-value cutoff to use for filtering
#' @returns a table with the 'celltype' as the first column, and the 'number' as the second column
#' 
de_outputs_to_table <- function(de_output_per_celltype, celltype_snip='_condition_final', p_val_column='p.bonferroni', p_val_cutoff=0.05, collapse_column=NULL) {
  # create a new dataframe
  nr_df <- data.frame(celltype = rep(NA, times = length(names(de_output_per_celltype))),
                      number = rep(0, times = length(names(de_output_per_celltype))))
  # check each celltype
  for (i in 1:length(names(de_output_per_celltype))) {
    # extract the cell type
    celltype <- names(de_output_per_celltype)[i]
    # extract the results
    output <- de_output_per_celltype[[celltype]]
    # filter by significance
    output <- output[output[[p_val_column]] < p_val_cutoff, ]
    # if we have a collapse column, we can group effects that share something together, such as the gene
    if (!is.null(collapse_column)) {
      output <- output[!duplicated(output[[collapse_column]]), ]
    }
    # count how many results
    nr_genes <- nrow(output)
    # snip something from the name if requested
    celltype_snipped <- celltype
    if (!is.null(celltype_snip)) {
      celltype_snipped <- gsub(celltype_snip, '', celltype)
    }
    # add to the dataframe
    nr_df[i, 'celltype'] <- celltype_snipped
    nr_df[i, 'number'] <- nr_genes
  }
  return(nr_df)
}

#' plot in a barplot the number of DE genes per cell type
#' 
#' @param de_numbers the table containing the number of DE genes per cell type
#' @param celltype_column which column of the supplied table has the celltype name
#' @param number_column which column of the supplied table has the number of DE genes
#' @param pointless draw the ticks on the bottom of the plot?
#' @param legendless draw the legend?
#' @param ylim the range for the y-axis
#' @param paper_style use the paper style with more whitespace
#' @param angle_labels angle the x labels 90 degrees?
#' @returns a barplot with the number of DE genes per cell type
#' 
de_gene_numbers_to_plot <- function(de_numbers, celltype_column='celltype', number_column='number', pointless=F, legendless=F, ylim=NULL, paper_style=T, angle_labels=T, use_label_dict=F) {
  # rename labels if requested
  if (use_label_dict) {
    de_numbers[[celltype_column]] <- rename_labels(as.character(de_numbers[[celltype_column]]))
  }
  p <- ggplot(mapping = aes(x = de_numbers[[celltype_column]], y = de_numbers[[number_column]], fill = de_numbers[[celltype_column]])) +
    geom_bar(stat='identity') + xlab(celltype_column) + ylab(number_column)
  # options
  if(!is.null(ylim)){
    p <- p + ylim(ylim)
  }
  if(pointless){
    p <- p + theme(axis.text.x=element_blank(), 
                   axis.ticks = element_blank())
  }
  if(legendless){
    p <- p + theme(legend.position = 'none')
  }
  if (paper_style) {
    p <- p + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white"))
  }
  if (angle_labels) {
    p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  }
  return(p)
}



plot_DE_sharing_per_celltype <- function(de_table_per_ct, feature_column='feature', pval_column='p.bonferroni', sig_pval=0.05, only_positive=F, only_negative=F, lfc_column='metafc', use_label_dict=T, use_color_dict=T){
  DE_genes_per_ct <- list()
  # get the DE genes for each cell type
  for(cell_type in names(de_table_per_ct)){
    # grab entry
    de_table <- de_table_per_ct[[cell_type]]
    # filter to only include the significant results
    if (!is.null(pval_column) & !is.null(sig_pval)) {
       de_table <- de_table[de_table[[pval_column]] < sig_pval, ]
    }
    # filter for only the positive lfc if required
    if(only_positive){
      de_table <- de_table[de_table[[lfc_column]] < 0, ]
    }
    # filter for only the positive lfc if required
    if(only_negative){
      de_table <- de_table[de_table[[lfc_column]] > 0, ]
    }
    # we just care about the gene names
    sig_genes <- NULL
    if (is.null(feature_column)) {
      sig_genes <- rownames(mast)
    }
    else {
      sig_genes <- de_table[[feature_column]]
    }
    # store these for the cell type
    DE_genes_per_ct[[cell_type]] <- sig_genes
  }
  if(use_label_dict){
    names(DE_genes_per_ct) <- rename_labels(names(DE_genes_per_ct))
  }
  queries <- list()
  sets.bar.color <- 'black'
  if(use_color_dict){
    # create df to store the number of each set, so we know how to order
    nrs_df <- NULL
    # add the colors for the cell types
    for(i in 1:length(names(DE_genes_per_ct))){
      cell_type <- names(DE_genes_per_ct)[i]
      # add for the singles in the intersection sizes
      ct_list <- list(
        query = intersects,
        params = list(cell_type),
        color = get_color_coding_dict()[[cell_type]],
        active = T)
      queries[[i]] <- ct_list
      # add for the DF to order the set sizes
      numbers_row <- data.frame(ct=c(cell_type), nr=c(length(DE_genes_per_ct[[cell_type]])), stringsAsFactors = F)
      if(is.null(nrs_df)){
        nrs_df <- numbers_row
      }
      else{
        nrs_df <- rbind(nrs_df, numbers_row)
      }
    }
    # get the order of the sets
    ordered_cts <- nrs_df[order(nrs_df$nr, decreasing = T), 'ct']
    # add the colors for the sets
    sets.bar.color <- unlist(get_color_coding_dict()[ordered_cts])
    upset(fromList(DE_genes_per_ct), order.by = 'freq', nsets = length(DE_genes_per_ct), queries = queries, sets.bar.color=sets.bar.color)
  }
  else {
    upset(fromList(DE_genes_per_ct), order.by = 'freq', nsets = length(DE_genes_per_ct))
  }
  
  #return(DE_genes_per_ct)
}


get_dars_vs_eregulon <- function(dars_per_topic, eregulons_table, dars_feature_column='feature', eregulon_feature_column='Region', dars_significance_column=NULL, dars_significance_cutoff=0.05) {
  # make a table with all of the numbers
  dars_vs_eregulons_numbers <- data.frame(matrix(, nrow = length(names(dars_per_topic)), ncol = 3))
  colnames(dars_vs_eregulons_numbers) <- c('topic', 'n_dars', 'n_eregulons')
  # check each topic
  for (i in 1:length(names(dars_per_topic))) {
    # get the topic
    topic <- names(dars_per_topic)[i]
    # extract the dars for that topic
    topic_dars <- dars_per_topic[[topic]]
    # subset to significance if requested
    if (!is.null(dars_significance_column)) {
      topic_dars <- topic_dars[topic_dars[[dars_significance_column]] < dars_significance_cutoff, ]
    }
    # get the number of dars
    n_dars <- nrow(topic_dars)
    # now check now many of those overlap with an eregulon
    eregulons_topic <- eregulons_table[eregulons_table[[eregulon_feature_column]] %in% topic_dars[[dars_feature_column]], ]
    # and the the number of eregulons
    n_eregs <- nrow(eregulons_topic)
    # now put all of that in the table
    dars_vs_eregulons_numbers[i, ] <- c(topic, n_dars, n_eregs)
  }
  # make sure the columns are numeric
  dars_vs_eregulons_numbers[['n_dars']] <- as.numeric(dars_vs_eregulons_numbers[['n_dars']])
  dars_vs_eregulons_numbers[['n_eregulons']] <- as.numeric(dars_vs_eregulons_numbers[['n_eregulons']])
  return(dars_vs_eregulons_numbers)
}


topic_memberships_to_table <- function(topic_membership_table, topic_regex='Topic\\d*') {
  # get the columns in the table
  all_columns <- colnames(topic_membership_table)
  # get the topic ones
  topic_columns <- all_columns[grepl(topic_regex, all_columns)]
  # create a table with the numbers
  n_per_topic <- data.frame(matrix(, nrow = length(topic_columns), ncol = 2))
  # set column names
  colnames(n_per_topic) <- c('topic', 'ncell')
  # now check each topic
  for (i in 1 : length(topic_columns)) {
    # get the table
    topic_true_false <- data.frame(table(topic_membership_table[[topic_columns[i]]]))
    # get the number we care about
    ncell <- topic_true_false[topic_true_false[['Var1']] == 'True', 'Freq']
    # put that into the table
    n_per_topic[i, ] <- c(topic_columns[i], ncell)
  }
  # make sure that is numeric
  n_per_topic[['ncell']] <- as.numeric(n_per_topic[['ncell']])
  return(n_per_topic)
}

```

```{r setup_paths, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

####################
# Main Code        #
####################

# get the stimulation output
limma_stim_base_output_path <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/differential_accessibility/limma_dream/output/stimulation/pct01/'
# get the stimulation output where we didn't correct for the lane
limma_stim_nolane_base_output_path <- '/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/differential_accessibility/limma_dream/output/stimulation/pct01/nolane/'

```

```{r plot_stim_numbers, include=TRUE, fig.width=10, fig.height=5}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# get the output per celltype
de_genes_limma_stim <- get_de_genes_per_celltype(limma_stim_base_output_path, de_method = 'limma', pattern = '*_condition_final.wpermfdr.wgene.tsv.gz$')
# fix up names
names(de_genes_limma_stim) <- gsub('_condition_final', '', names(de_genes_limma_stim))
# get the numbers as well
de_genes_limma_stim_numbers <- de_outputs_to_table(de_genes_limma_stim)
# plot them
de_gene_numbers_to_plot(de_genes_limma_stim_numbers, legendless = T, use_label_dict = T) + 
  ylab('Number of DARs') + 
  xlab('Cell type') + 
  ggtitle('Number of DARs using Limma') +
  scale_fill_manual(values = get_color_coding_dict())

```

```{r plot_stim_sharing, include=TRUE, fig.width=10, fig.height=5}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# plot the sharing of region
plot_DE_sharing_per_celltype(de_genes_limma_stim)

```

```{r plot_stim_sharing, include=TRUE, fig.width=10, fig.height=5}

# get the output per celltype when not correcting for lane
de_genes_limma_stim_nolane <- get_de_genes_per_celltype(limma_stim_nolane_base_output_path, de_method = 'limma')
# fix up names
names(de_genes_limma_stim_nolane) <- gsub('_condition_final', '', names(de_genes_limma_stim_nolane))
# make new list with the different runs for the same celltype
de_genes_mono_different_runs <- list('without lane' = de_genes_limma_stim_nolane[['monocyte']], 'with lane' = de_genes_limma_stim[['monocyte']])
de_genes_cd8t_different_runs <- list('without lane' = de_genes_limma_stim_nolane[['CD8T']], 'with lane' = de_genes_limma_stim[['CD8T']])
# plot overlap
plot_DE_sharing_per_celltype(de_genes_mono_different_runs, use_label_dict = F, use_color_dict = F)
grid.text("correcting vs not correcting for lane in DAR identification for monocytes",x = 0.65, y=0.95, gp=gpar(fontsize=10))
plot_DE_sharing_per_celltype(de_genes_cd8t_different_runs, use_label_dict = F, use_color_dict = F)
grid.text("correcting vs not correcting for lane in DAR identification for CD8+ T",x = 0.65, y=0.95, gp=gpar(fontsize=10))

```
```{r plot_archr_sharing, include=TRUE, fig.width=10, fig.height=5}

# read the UT regions from archR
archr_ut_mono <- read.table('/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/scenicplus_workdir/pycistopic/monocytes_all_cells/region_sets/model_20_topics/DARS_stim_unstim/UT.bed', header = F, sep = '\t')
# paste features
archr_ut_mono_features <- paste(archr_ut_mono$V1, archr_ut_mono$V2, archr_ut_mono$V3, sep = '-')
# 24hCA as well
archr_24hca_mono <- read.table('/groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/scenicplus_workdir/pycistopic/monocytes_all_cells/region_sets/model_20_topics/DARS_stim_unstim/24hCA.bed', header = F, sep = '\t')
archr_24hca_mono_features <- paste(archr_24hca_mono$V1, archr_24hca_mono$V2, archr_24hca_mono$V3, sep = '-')
# now get just lists for limma
de_genes_limma_stim_nolane_features <- de_genes_limma_stim_nolane[['monocyte']][de_genes_limma_stim_nolane[['monocyte']][['p.bonferroni']] < 0.05, 'feature']
de_genes_limma_stim_features <- de_genes_limma_stim[['monocyte']][de_genes_limma_stim[['monocyte']][['p.bonferroni']] < 0.05, 'feature']

# make new list with the different runs for the same celltype
de_genes_mono_w_archr <- list('without lane' = de_genes_limma_stim_nolane_features, 'with lane' = de_genes_limma_stim_features, 'UT archR' = archr_ut_mono_features, '24hCA archR' = archr_24hca_mono_features)
# plot overlap
upset(fromList(de_genes_mono_w_archr), order.by = 'freq')
grid.text("DAR identification for monocytes archR and limma",x = 0.65, y=0.95, gp=gpar(fontsize=10))

# get total DARs
archr_dars <- unique(c(archr_ut_mono_features, archr_ut_mono_features))
limma_dars <- de_genes_limma_stim_nolane_features
all_dars <- unique(c(archr_dars, de_genes_limma_stim_nolane_features))
overlapping_dars <- intersect(archr_dars, limma_dars)

```
```{r plot_stim_numbers, include=TRUE, fig.width=10, fig.height=5}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# get the numbers as well
de_genes_limma_stim_numbers_genes <- de_outputs_to_table(de_genes_limma_stim, collapse_column = 'gene_id')
# plot them
de_gene_numbers_to_plot(de_genes_limma_stim_numbers_genes, legendless = T, use_label_dict = T) + 
  ylab('Number of DAR-linked genes') + 
  xlab('Cell type') + 
  ggtitle('Number of DAR-linked genes using Limma') +
  scale_fill_manual(values = get_color_coding_dict())

```

```{r plot_stim_sharing, include=TRUE, fig.width=10, fig.height=5}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# plot the sharing of region
plot_DE_sharing_per_celltype(de_genes_limma_stim, feature_column = 'gene_id')

```

```{r plot_topic_sharing, include=TRUE, fig.width=10, fig.height=5}

# location of the DARs
dars_topics_mono_loc <- '/groups/umcg-franke-scrna/tmp01/projects/multiome/ongoing/differential_accessibility/limma_dream/output/topics20_otsu_imputed_confined_ncell5_001/monocyte/merged_regions/'
dars_topics_mono <- get_de_genes_per_celltype(dars_topics_mono_loc, 'limma', pval_column='p.bonferroni', p_val_cutoff=0.05, pattern='*.nominal_significant.tsv.gz$')
# remove the prepend
names(dars_topics_mono) <- gsub('monocyte_', '', names(dars_topics_mono))
# and plot the sharing
plot_DE_sharing_per_celltype(dars_topics_mono, use_label_dict = F, use_color_dict = F)

```

```{r plot_topic_sharing_prev, include=TRUE, fig.width=10, fig.height=5}

# location of the DARs
dars_topics_mono_prev_loc <- '/groups/umcg-franke-scrna/tmp01/projects/multiome/ongoing/scenicplus_workdir/pycistopic/monocytes_all_cells/region_sets/model_20_topics/Topics_otsu/'
dars_topics_mono_prev <- get_de_genes_per_celltype(dars_topics_mono_prev_loc, 'bed_headless', pval_column=NULL, p_val_cutoff=NULL, pattern='*.bed$')
# keep joint topics
dars_topics_mono_prev <- dars_topics_mono_prev[intersect(names(dars_topics_mono), names(dars_topics_mono_prev))]
# rename feature by pasting together the columns
for (topic in names(dars_topics_mono_prev)) {
  # get table
  topic_tbl <- dars_topics_mono_prev[[topic]]
  # add new column
  topic_tbl[['feature']] <- paste(topic_tbl[['V1']], topic_tbl[['V2']], topic_tbl[['V3']], sep = '-')
  # put back into list
  dars_topics_mono_prev[[topic]] <- topic_tbl
}

# and plot the sharing
plot_DE_sharing_per_celltype(dars_topics_mono_prev, use_label_dict = F, use_color_dict = F, feature_column = 'feature', pval_column = NULL)

```

```{r plot_topic_sharing_prev_and_new, include=TRUE, fig.width=20, fig.height=10}

# make a new list with both of the dar methods
dars_topics_mono_both <- list()
# loop through the first one
for (topic in names(dars_topics_mono_prev)) {
  # get table
  topic_tbl <- dars_topics_mono_prev[[topic]]
  # put in the new list
  dars_topics_mono_both[[paste(topic, 'wilcoxon')]] <- topic_tbl
}
# now the new one
for (topic in names(dars_topics_mono)) {
  # get table
  topic_tbl <- dars_topics_mono[[topic]]
  # put in the new list
  dars_topics_mono_both[[paste(topic, 'limma')]] <- topic_tbl
}

# and make the plot again
plot_DE_sharing_per_celltype(dars_topics_mono_both, use_label_dict = F, use_color_dict = F, feature_column = 'feature', pval_column = NULL)

```

```{r plot_topic_sharing_prev_and_new_all, include=TRUE, fig.width=20, fig.height=10}

# merge all the previous ones
dars_topics_mono_prev_all <- do.call('rbind', dars_topics_mono_prev)
# and all the new ones
dars_topics_mono_new_all <- do.call('rbind', dars_topics_mono)
# put into a list
dars_topics_mono_new_vs_prev <- list('wilcoxon' = dars_topics_mono_prev_all, 'limma' = dars_topics_mono_new_all)

# and make the plot
plot_DE_sharing_per_celltype(dars_topics_mono_new_vs_prev, use_label_dict = F, use_color_dict = F, feature_column = 'feature', pval_column = NULL)

```

```{r plot_topic_sharing_prev_and_new_all, include=TRUE, fig.width=20, fig.height=10}

# get eregulons of limma
limma_eregulons_loc <- '/groups/umcg-franke-scrna/tmp01/projects/multiome/ongoing/scenicplus_workdir/scplus_pipeline_limma_001/output/eRegulon_direct.tsv'
limma_eregulons <- read.table(limma_eregulons_loc, header = T, sep = '\t')
# set region as feature
limma_eregulons[['feature']] <- gsub(':', '-', limma_eregulons[['Region']])
# add these to the list
dars_topics_mono_new_vs_prev[['limma_eregulons']] <- limma_eregulons
# previous eregulons
prev_eregulons_loc <- '/groups/umcg-franke-scrna/tmp01/projects/multiome/ongoing/scenicplus_workdir/scplus_pipeline/monocyte/eRegulon_direct_mono_20_topics.tsv'
prev_eregulons <- read.table(prev_eregulons_loc, header = T, sep = '\t')
prev_eregulons[['feature']] <- gsub(':', '-', prev_eregulons[['Region']])
# subset the eregulons to ones we have DARs for
prev_eregulons <- prev_eregulons[prev_eregulons[['feature']] %in% dars_topics_mono_prev_all[['feature']], ]
dars_topics_mono_new_vs_prev[['prev_eregulons']] <- prev_eregulons

# now the eregs of the 10k monos
k10_regulons_loc <- '/groups/umcg-franke-scrna/tmp01/projects/multiome/ongoing/scenicplus_workdir/scenicplus_pipeline/monocytes/model_10k_mono_20_topics/eRegulon_direct.tsv'
k10_eregulons <- read.table(k10_regulons_loc, header = T, sep = '\t')
k10_eregulons[['feature']] <- gsub(':', '-', k10_eregulons[['Region']])
# and the dars
dars_topics_10k_loc <- '/groups/umcg-franke-scrna/tmp01/projects/multiome/ongoing/scenicplus_workdir/pycistopic/monocytes_10000_cells_20_topics/region_sets/Topics_otsu/'
dars_topics_10k <- get_de_genes_per_celltype(dars_topics_10k_loc, 'bed_headless', pval_column=NULL, p_val_cutoff=NULL, pattern='*.bed$')
# add feature
for (topic_10k in names(dars_topics_10k)) {
  # for each topic, add the feature
  dars_topics_10k_topic <- dars_topics_10k[[topic_10k]]
  dars_topics_10k_topic[['feature']] <- paste(dars_topics_10k_topic[['V1']], dars_topics_10k_topic[['V2']], dars_topics_10k_topic[['V3']], sep = '-')
  dars_topics_10k[[topic_10k]] <- dars_topics_10k_topic
}
# and add those
dars_topics_10k_all <- do.call('rbind', dars_topics_10k)
# add column of feature
dars_topics_10k_all[['feature']] <- paste(dars_topics_10k_all[['V1']], dars_topics_10k_all[['V2']], dars_topics_10k_all[['V3']], sep = '-')
# add these
dars_topics_mono_new_vs_prev[['10k_eregulons']] <- k10_eregulons
dars_topics_mono_new_vs_prev[['10k_dars']] <- dars_topics_10k_all

# finally plot the overlap
plot_DE_sharing_per_celltype(dars_topics_mono_new_vs_prev, use_label_dict = F, use_color_dict = F, feature_column = 'feature', pval_column = NULL)
```

```{r plot_ndars_vs_nregulons, include=TRUE, fig.width=20, fig.height=10}

# plot the number of DARs vs the number of eregulons in the wilcoxon analysis
ggplot(data = get_dars_vs_eregulon(dars_topics_mono_prev, prev_eregulons, dars_feature_column = 'feature', eregulon_feature_column = 'feature'), mapping = aes(x = n_dars, y = n_eregulons, col = topic)) + geom_point() + xlim(c(0, 200000)) + ylim(c(0, 10000)) + xlab('number of DARs') + ylab('number of eRegulons') + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) + theme(legend.position = 'none') + ggtitle('number of DARs vs eRegulons with those DARs Wilcoxon')

# plot the number of DARs vs the number of eregulons in the previous 10k cell wilcoxon analysis
ggplot(data = get_dars_vs_eregulon(dars_topics_10k, k10_eregulons, dars_feature_column = 'feature', eregulon_feature_column = 'feature'), mapping = aes(x = n_dars, y = n_eregulons, col = topic)) + geom_point() + xlim(c(0, 80000)) + ylim(c(0, 15000)) + xlab('number of DARs') + ylab('number of eRegulons') + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) + theme(legend.position = 'none') + ggtitle('number of DARs vs eRegulons with those DARs 10k')

# plot the number of DARs vs the number of eregulons in the limma analysis
ggplot(data = get_dars_vs_eregulon(dars_topics_mono, limma_eregulons, dars_feature_column = 'feature', eregulon_feature_column = 'feature'), mapping = aes(x = n_dars, y = n_eregulons, col = topic)) + geom_point() + xlim(c(0, 12000)) + ylim(c(0, 7000)) + xlab('number of DARs') + ylab('number of eRegulons') + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) + theme(legend.position = 'none') + ggtitle('number of DARs vs eRegulons with those DARs limma')

```

```{r plot_ncells_vs_ndars, include=TRUE, fig.width=20, fig.height=10}

# get the binarized topic annotation per cell
topic_memberships_loc <- '/groups/umcg-franke-scrna/tmp01/projects/multiome/ongoing/differential_accessibility/topic_annotations/mo_topic_20_otsu.tsv'
topic_memberships <- read.table(topic_memberships_loc, header = T, sep = '\t')
# now check how many cells are 'True', so assigned to each topic
ncell_topics <- topic_memberships_to_table(topic_memberships)

# get the dars vs eregulons for the wilcoxon and limma
dars_ereg_wilcoxon <- get_dars_vs_eregulon(dars_topics_mono_prev, prev_eregulons, dars_feature_column = 'feature', eregulon_feature_column = 'feature')
dars_ereg_limma <- get_dars_vs_eregulon(dars_topics_mono, limma_eregulons, dars_feature_column = 'feature', eregulon_feature_column = 'feature')

# join the the ncells
dars_ereg_wilcoxon <- merge(dars_ereg_wilcoxon, ncell_topics, by = 'topic')
dars_ereg_limma <- merge(dars_ereg_limma, ncell_topics, by = 'topic')

# now also plot the ncells vs ndars
ggplot(data = dars_ereg_wilcoxon, mapping = aes(x = ncell, y = n_dars, col = topic)) + geom_point() + xlim(c(0, 35000)) + ylim(c(0, 200000)) + xlab('number of cells') + ylab('number of DARs') + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) + theme(legend.position = 'none') + ggtitle('number of cells vs number of DARs Wilcoxon')
# also for limma
ggplot(data = dars_ereg_wilcoxon, mapping = aes(x = ncell, y = n_dars, col = topic)) + geom_point() + xlim(c(0, 35000)) + ylim(c(0, 12000)) + xlab('number of cells') + ylab('number of DARs') + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) + theme(legend.position = 'none') + ggtitle('number of cells vs number of DARs limma')

# and for the eregulons
ggplot(data = dars_ereg_wilcoxon, mapping = aes(x = ncell, y = n_eregulons, col = topic)) + geom_point() + xlim(c(0, 35000)) + ylim(c(0, 8000)) + xlab('number of cells') + ylab('number of eRegulons') + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) + theme(legend.position = 'none') + ggtitle('number of cells vs number of eRegulons Wilcoxon')
# also for limma
ggplot(data = dars_ereg_wilcoxon, mapping = aes(x = ncell, y = n_eregulons, col = topic)) + geom_point() + xlim(c(0, 35000)) + ylim(c(0, 8000)) + xlab('number of cells') + ylab('number of eRegulons') + theme(panel.border = element_rect(color="black", fill=NA, size=1.1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white")) + theme(legend.position = 'none') + ggtitle('number of cells vs number of eRegulons limma')
```
