#!/usr/bin/env Rscript
############################################################################################################################
# Authors: Roy Oelen
# Name: mo_get_ld_pairs.R
# Function: get the variants on the rows of an LD matrix (generated by mo_calc_lds.R), that are in LD with the variants on the columns of an LD matrix
# Example: 
# Rscript mo_get_ld_pairs.R \
#   --matrix_prepend /groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/eqtl/annotations/mo_qtl_variants_tested_ld/1000G_HC/eurpop/moresparse/mo_qtl_variants_tested_cpeaks_overlap_chr \
#   --matrix_append .mtx.gz \
#   --output_loc /groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/eqtl/annotations/mo_qtl_variants_tested_ld/1000G_HC/eurpop/moresparse/mo_qtl_variants_tested_cpeaks_overlap_ld_pairs.tsv.gz \
#   --ld_cutoff 0.8 \
#   --nthreads 4
#
# Example 2: 
# Rscript mo_get_ld_pairs.R \
#   --matrix_prepend /groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/caqtl/sc-eqtlgen/GWAS_enrichment/GWAS_vars/moldpairs/1000G_HC/eurpop/immune-gwas-catalog-download-associations-alt-full-moldpairs \
#   --matrix_append .mtx.gz \
#   --output_loc /groups/umcg-franke-scrna/tmp04/projects/multiome/ongoing/qtl/caqtl/sc-eqtlgen/GWAS_enrichment/GWAS_vars/moldpairs/1000G_HC/eurpop/immune-gwas-catalog-download-associations-alt-full-moldpairs_ld_pairs.tsv.gz \
#   --ld_cutoff 0.8 \
#   --nthreads 4
#
############################################################################################################################

####################
# libraries        #
####################

# table format
library(data.table)
# use sparse matrices
library(Matrix)
# load command line parameters
library(optparse)
# for parallel processing
library(parallel)


####################
# functions        #
####################

is_sparse_symmetric <- function(mat) {
  # check if one of these classes
  if (inherits(mat, "dsTMatrix") ||
      inherits(mat, "dsCMatrix") ||
      inherits(mat, "dsRMatrix")) {
    return(TRUE)
  }
  # otherwise check
  isTRUE(all.equal(mat, t(mat)))
}

process_matrix_symmetric <- function(mat, ld_cutoff) {
  # convert to dgT
  mat <- as(mat, "dgTMatrix")
  
  # keep only upper triangle (i < j)
  keep <- mat@i < mat@j & mat@x > ld_cutoff
  
  # format into table
  ld_pairs <- data.table(
    'index_variant' = rownames(mat)[mat@i[keep] + 1],
    'ld_variant' = colnames(mat)[mat@j[keep] + 1],
    'R2' = mat@x[keep]
  )
  # remove incorrect values
  ld_pairs <- ld_pairs[ld_pairs[['R2']] < 1.001, ]
  
  return(ld_pairs)
}

process_matrix <- function(mat_file, matrix_dir, matrix_append, ld_cutoff, progress_n=10000, transpose_matrix=F) {
  # get the base name of the matrix file
  base <- sub(matrix_append, '', mat_file)
  # paste the x together
  x_names_loc <- paste0(matrix_dir, '/', base, '.x.txt.gz')
  # and y names
  y_names_loc <- paste0(matrix_dir, '/', base, '.y.txt.gz')
  # read the two files
  x_names <- fread(x_names_loc, header = F)[[1]]
  y_names <- fread(y_names_loc, header = F)[[1]]
  # read the matrix
  mat <- readMM(paste0(matrix_dir, '/', mat_file))
  # perform transposition if requested
  if (transpose_matrix) {
    # transpose actual matrix
    mat <- t(mat)
    # swap names
    tmp <- x_names
    x_names <- y_names
    y_names <- tmp
    # say that we do this
    message('doing non-standard column-based LD collection')
  } else {
    message('doing standard row-based LD collection')
  }
  # set the row and column names of the matrix to the variant names
  rownames(mat) <- y_names
  colnames(mat) <- x_names
  # store results of matrix
  ld_pairs_all <- NULL
  # check if symmetric
  if (is_sparse_symmetric(mat)) {
    # warn about transposing if the matrix is symmetric
    if (transpose_matrix) {
      warning(paste('asking for matrix transpose, but matrix is symmetric. parameter is ignored'))
    }
    ld_pairs_all <- process_matrix_symmetric(mat, ld_cutoff)
    # because we do only the triangle, and we want complete pair-wise, we have to duplicate the result
    ld_pairs_all <- rbind(
      ld_pairs_all, 
      data.table('index_variant' = ld_pairs_all[['ld_variant']], 
                 'ld_variant' = ld_pairs_all[['index_variant']],
                 'R2' = ld_pairs_all[['R2']])
    )
  } else {
    # convert to correct matrix format
    mat <- as(mat, "RsparseMatrix")
    # perform transposition if requested
    if (transpose_matrix) {
      # transpose actual matrix
      mat <- t(mat)
      # swap names
      tmp <- x_names
      x_names <- y_names
      y_names <- tmp
      # say that we do this
      message('doing non-standard column-based LD collection')
    } else {
      message('doing standard row-based LD collection')
    }
    # set the row and column names of the matrix to the variant names
    rownames(mat) <- y_names
    colnames(mat) <- x_names
    # get the number of values on the x axis to check
    n <- nrow(mat)
    # make list to store results
    ld_pairs <- list()
    # create progress bar for this chromosome
    # progressbar <- txtProgressBar(min = 0, max = n, style = 3)
    # go through the rows of the matrix and check for values above the ld cutoff
    for (row_i in seq_len(n)) {
      # update progress bar
      # setTxtProgressBar(progressbar, row_i)
      # extract the start and top positions of the non-zero values in the row
      start <- mat@p[row_i] + 1
      end   <- mat@p[row_i + 1]
      # extract the values in the row
      vals <- mat@x[start:end]
      # extract the columns of the non-zero values in the row
      cols <- mat@j[start:end] + 1  # convert to 1‑based indexing
      # create a mask for values above the ld cutoff
      mask <- vals > ld_cutoff
      # also make any NA values into false
      mask[is.na(mask)] <- F
      # if there were any values
      if (any(mask)) {
        out_row_ld <- data.frame(
          'index_variant' = rep(rownames(mat)[row_i], times = sum(mask)),
          'ld_variant' = colnames(mat)[cols[mask]],
          'R2' = vals[mask]
        )
        # remove incorrect values
        out_row_ld <- out_row_ld[out_row_ld[['R2']] < 1.001, ]
        # put in the list
        ld_pairs[[paste(base, row_i)]] <- out_row_ld
      }
      # print progress for chromosome
      if (row_i %% progress_n == 0 || row_i == n) {
        cat(sprintf("%s: %.1f%% (%d / %d)\n",
                    base,
                    100 * row_i / n,
                    row_i,
                    n))
      }
    }
    # close(progressbar)
    # combine the list into a data frame
    ld_pairs_all <- rbindlist(ld_pairs)
  }
  return(ld_pairs_all)
}


####################
# Settings         #
####################

# luck seed
set.seed(7777)
# whether we are in debug mode
debug <- F


####################
# Main code        #
####################

# make command line options
option_list <- list(
  make_option(c("-i", "--matrix_prepend"), type="character", default=NULL, 
              help="plink based path genotype file", metavar="character"),
  make_option(c("-a", "--matrix_append"), type="character", default='.mtx.gz', 
              help="base output file", metavar="character"), 
  make_option(c("-o", "--output_loc"), type="character", default=NULL, 
              help="variant list file (default without header)", metavar="character"),
  make_option(c("-l", "--ld_cutoff"), type="numeric", default=0.8, 
              help="cutoff to consider variants in LD", metavar="numeric"), 
  make_option(c("-n", "--nthreads"), type="numeric", default=NULL, 
              help="number of threads to use", metavar="numeric"), 
  make_option(c("-t", "--transpose_matrix"), action="store_true", default=FALSE,
              help="transpose the matrix so LD is column-based instead or row-based [default: %default]")
)


# initialize optparser
opt_parser <- OptionParser(option_list=option_list)
opt <- parse_args(opt_parser)

# initialize the options in debug mode
if (debug) {
  opt <- list(
    matrix_prepend = '/groups/umcg-fg/tmp04/projects/mpra/generate_panel/mo_qtl_1000g_ld/ld_matrices/mpra_top_qtl_1000g_eur_chr',
    matrix_append = '.mtx.gz',
    output_loc = '/groups/umcg-fg/tmp04/projects/mpra/generate_panel/mo_qtl_1000g_ld/ld_matrices/mpra_top_qtl_1000g_eur_ld_pairs.tsv.gz',
    ld_cutoff = 0.7, 
    nthreads = 4, 
    transpose_matrix = F
  )
}

# set non-optional parameters
matrix_prepend <- NULL
output_loc <- NULL
# read them
if (!is.null(opt[['matrix_prepend']])) {
  matrix_prepend <- opt[['matrix_prepend']]
} else {
  print_help(opt_parser)
  stop("Please provide the path to the matrix files", call.=FALSE)
}
if(!is.null(opt[['output_loc']])) {
  output_loc <- opt[['output_loc']]
} else {
  print_help(opt_parser)
  stop("Please provide the path to the output file", call.=FALSE)
}
# set optional parameters
matrix_append <- opt[['matrix_append']]
ld_cutoff <- opt[['ld_cutoff']]
transpose_matrix <- opt[['transpose_matrix']]
nthreads <- NULL
# if there is a parameter, take it, otherwise it is ncores - 1
if(!is.null(opt[['nthreads']])) {
  nthreads <- opt[['nthreads']]
} else {
  nthreads <- detectCores() - 1
}


# get the directory the files are in
matrix_dir <- dirname(matrix_prepend)
# and the patter for the file
matrix_pattern <- paste0(basename(matrix_prepend), ".*", matrix_append, '$')
# get list of matrix files
matrix_files <- list.files(matrix_dir)
# and filter them
matrix_files <- matrix_files[grepl(matrix_pattern, matrix_files)]
# get the basenames of these
matrix_basenames <- gsub(matrix_append, '', matrix_files)

# initialize result
results_all <- NULL
# do simple approach if the ntrheads is 1
if (nthreads == 1) {
  # store results of matrix
  ld_pairs <- list()
  # check each of these matrices for LD pairs
  for (i in 1 : length(matrix_files)) {
    # read the matrix
    mat <- readMM(paste0(matrix_dir, '/', matrix_files[i]))
    # paste the x together
    x_names_loc <- paste0(matrix_dir, '/', matrix_basenames[i], '.x.txt.gz')
    # and y names
    y_names_loc <- paste0(matrix_dir, '/', matrix_basenames[i], '.y.txt.gz')
    # read the two files
    x_names <- fread(x_names_loc, header = F)[[1]]
    y_names <- fread(y_names_loc, header = F)[[1]]
    # set the row and column names of the matrix to the variant names
    rownames(mat) <- y_names
    colnames(mat) <- x_names
    # check if sym
    if (is_sparse_symmetric(mat)) {
      # warn about transposing if the matrix is symmetric
      if (transpose_matrix) {
        warning(paste('asking for matrix transpose, but matrix is symmetric. parameter is ignored'))
      }
      # use the upper triangle method
      ld_pairs_all <- process_matrix_symmetric(mat, ld_cutoff)
      # because we do only the triangle, and we want complete pair-wise, we have to duplicate the result
      ld_pairs_all <- rbind(
        ld_pairs_all, 
        data.table('index_variant' = ld_pairs_all[['ld_variant']], 
                   'ld_variant' = ld_pairs_all[['index_variant']],
                   'R2' = ld_pairs_all[['R2']])
      )
      # put in the list
      ld_pairs[[matrix_basenames[i]]] <- ld_pairs_all
    } else {
      # convert to correct matrix format
      mat <- as(mat, "RsparseMatrix")
      # set the row and column names of the matrix to the variant names
      rownames(mat) <- y_names
      # get the number of values on the x axis to check
      n <- nrow(mat)
      # create progress bar for this chromosome
      progressbar <- txtProgressBar(min = 0, max = n, style = 3)
      # go through the rows of the matrix and check for values above the ld cutoff
      for (row_i in seq_len(n)) {
        # update progress bar
        setTxtProgressBar(progressbar, row_i)
        # extract the start and top positions of the non-zero values in the row
        start <- mat@p[row_i] + 1
        end   <- mat@p[row_i + 1]
        # extract the values in the row
        vals <- mat@x[start:end]
        # extract the columns of the non-zero values in the row
        cols <- mat@j[start:end] + 1  # convert to 1‑based indexing
        # create a mask for values above the ld cutoff
        mask <- vals > ld_cutoff
        # also make any NA values into false
        mask[is.na(mask)] <- F
        # if there were any values
        if (any(mask)) {
          out_row_ld <- data.frame(
            'index_variant' = rep(rownames(mat)[row_i], times = sum(mask)),
            'ld_variant' = colnames(mat)[cols[mask]],
            'R2' = vals[mask]
          )
          # remove incorrect values
          out_row_ld[out_row_ld[['R2']] < 1.001, ]
          # put in the list
          ld_pairs[[paste(matrix_basenames[i], row_i)]] <- out_row_ld
        }
      }
      close(progressbar)
    }
  }
  results_all <- rbindlist(ld_pairs)

} else {
  # parallel processing for the chromosomes
  results <- mclapply(
    matrix_files,
    FUN = process_matrix,
    matrix_dir = matrix_dir,
    matrix_append = matrix_append,
    ld_cutoff = ld_cutoff, 
    transpose_matrix = transpose_matrix,
    mc.cores = nthreads
  )
  # merge all the results
  results_all <- rbindlist(results)
}

# order
results_all <- results_all[order(results_all[['index_variant']], results_all[['ld_variant']])]
# remove R2 much larger than 1, as these are the NA values
results_all <- results_all[results_all[['R2']] < 1.001, ]

# set output loc as the tsv
output_loc_full <- output_loc
# gz file ends with .gz
if (grepl('.gz$', output_loc)) {
  # gzip if ends with .gz
  output_loc_full <- gzfile(output_loc)
}
# write the result
write.table(results_all, output_loc_full, row.names = F, col.names = T, sep = '\t', quote = F)
# make checksum
mdfiver::create_sha256_for_file(output_loc)
